// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: graph/v1/changes.proto

package graphv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/anaregdesign/lantern/pb/graph/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LanternChangeServiceName is the fully-qualified name of the LanternChangeService service.
	LanternChangeServiceName = "graph.v1.LanternChangeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LanternChangeServiceWatchChangesProcedure is the fully-qualified name of the
	// LanternChangeService's WatchChanges RPC.
	LanternChangeServiceWatchChangesProcedure = "/graph.v1.LanternChangeService/WatchChanges"
)

// LanternChangeServiceClient is a client for the graph.v1.LanternChangeService service.
type LanternChangeServiceClient interface {
	WatchChanges(context.Context, *connect.Request[v1.WatchChangesRequest]) (*connect.ServerStreamForClient[v1.WatchChangesResponse], error)
}

// NewLanternChangeServiceClient constructs a client for the graph.v1.LanternChangeService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLanternChangeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LanternChangeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lanternChangeServiceMethods := v1.File_graph_v1_changes_proto.Services().ByName("LanternChangeService").Methods()
	return &lanternChangeServiceClient{
		watchChanges: connect.NewClient[v1.WatchChangesRequest, v1.WatchChangesResponse](
			httpClient,
			baseURL+LanternChangeServiceWatchChangesProcedure,
			connect.WithSchema(lanternChangeServiceMethods.ByName("WatchChanges")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lanternChangeServiceClient implements LanternChangeServiceClient.
type lanternChangeServiceClient struct {
	watchChanges *connect.Client[v1.WatchChangesRequest, v1.WatchChangesResponse]
}

// WatchChanges calls graph.v1.LanternChangeService.WatchChanges.
func (c *lanternChangeServiceClient) WatchChanges(ctx context.Context, req *connect.Request[v1.WatchChangesRequest]) (*connect.ServerStreamForClient[v1.WatchChangesResponse], error) {
	return c.watchChanges.CallServerStream(ctx, req)
}

// LanternChangeServiceHandler is an implementation of the graph.v1.LanternChangeService service.
type LanternChangeServiceHandler interface {
	WatchChanges(context.Context, *connect.Request[v1.WatchChangesRequest], *connect.ServerStream[v1.WatchChangesResponse]) error
}

// NewLanternChangeServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLanternChangeServiceHandler(svc LanternChangeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lanternChangeServiceMethods := v1.File_graph_v1_changes_proto.Services().ByName("LanternChangeService").Methods()
	lanternChangeServiceWatchChangesHandler := connect.NewServerStreamHandler(
		LanternChangeServiceWatchChangesProcedure,
		svc.WatchChanges,
		connect.WithSchema(lanternChangeServiceMethods.ByName("WatchChanges")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graph.v1.LanternChangeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LanternChangeServiceWatchChangesProcedure:
			lanternChangeServiceWatchChangesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLanternChangeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLanternChangeServiceHandler struct{}

func (UnimplementedLanternChangeServiceHandler) WatchChanges(context.Context, *connect.Request[v1.WatchChangesRequest], *connect.ServerStream[v1.WatchChangesResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternChangeService.WatchChanges is not implemented"))
}
