// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: graph/v1/graph.proto

package graphv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/anaregdesign/lantern/pb/graph/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LanternServiceName is the fully-qualified name of the LanternService service.
	LanternServiceName = "graph.v1.LanternService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LanternServiceIlluminateProcedure is the fully-qualified name of the LanternService's Illuminate
	// RPC.
	LanternServiceIlluminateProcedure = "/graph.v1.LanternService/Illuminate"
	// LanternServiceGetVertexProcedure is the fully-qualified name of the LanternService's GetVertex
	// RPC.
	LanternServiceGetVertexProcedure = "/graph.v1.LanternService/GetVertex"
	// LanternServiceGetVerticesProcedure is the fully-qualified name of the LanternService's
	// GetVertices RPC.
	LanternServiceGetVerticesProcedure = "/graph.v1.LanternService/GetVertices"
	// LanternServicePutVertexProcedure is the fully-qualified name of the LanternService's PutVertex
	// RPC.
	LanternServicePutVertexProcedure = "/graph.v1.LanternService/PutVertex"
	// LanternServicePutVerticesProcedure is the fully-qualified name of the LanternService's
	// PutVertices RPC.
	LanternServicePutVerticesProcedure = "/graph.v1.LanternService/PutVertices"
	// LanternServiceDeleteVertexProcedure is the fully-qualified name of the LanternService's
	// DeleteVertex RPC.
	LanternServiceDeleteVertexProcedure = "/graph.v1.LanternService/DeleteVertex"
	// LanternServiceDeleteVerticesProcedure is the fully-qualified name of the LanternService's
	// DeleteVertices RPC.
	LanternServiceDeleteVerticesProcedure = "/graph.v1.LanternService/DeleteVertices"
	// LanternServiceScanVerticesProcedure is the fully-qualified name of the LanternService's
	// ScanVertices RPC.
	LanternServiceScanVerticesProcedure = "/graph.v1.LanternService/ScanVertices"
	// LanternServiceScanVertexKeysProcedure is the fully-qualified name of the LanternService's
	// ScanVertexKeys RPC.
	LanternServiceScanVertexKeysProcedure = "/graph.v1.LanternService/ScanVertexKeys"
	// LanternServiceSearchVerticesProcedure is the fully-qualified name of the LanternService's
	// SearchVertices RPC.
	LanternServiceSearchVerticesProcedure = "/graph.v1.LanternService/SearchVertices"
	// LanternServiceCountVerticesByPrefixProcedure is the fully-qualified name of the LanternService's
	// CountVerticesByPrefix RPC.
	LanternServiceCountVerticesByPrefixProcedure = "/graph.v1.LanternService/CountVerticesByPrefix"
	// LanternServiceDeleteVerticesByPrefixProcedure is the fully-qualified name of the LanternService's
	// DeleteVerticesByPrefix RPC.
	LanternServiceDeleteVerticesByPrefixProcedure = "/graph.v1.LanternService/DeleteVerticesByPrefix"
	// LanternServiceGetEdgeProcedure is the fully-qualified name of the LanternService's GetEdge RPC.
	LanternServiceGetEdgeProcedure = "/graph.v1.LanternService/GetEdge"
	// LanternServiceGetEdgesProcedure is the fully-qualified name of the LanternService's GetEdges RPC.
	LanternServiceGetEdgesProcedure = "/graph.v1.LanternService/GetEdges"
	// LanternServiceAddEdgeProcedure is the fully-qualified name of the LanternService's AddEdge RPC.
	LanternServiceAddEdgeProcedure = "/graph.v1.LanternService/AddEdge"
	// LanternServiceAddEdgesProcedure is the fully-qualified name of the LanternService's AddEdges RPC.
	LanternServiceAddEdgesProcedure = "/graph.v1.LanternService/AddEdges"
	// LanternServicePutEdgeProcedure is the fully-qualified name of the LanternService's PutEdge RPC.
	LanternServicePutEdgeProcedure = "/graph.v1.LanternService/PutEdge"
	// LanternServicePutEdgesProcedure is the fully-qualified name of the LanternService's PutEdges RPC.
	LanternServicePutEdgesProcedure = "/graph.v1.LanternService/PutEdges"
	// LanternServiceDeleteEdgeProcedure is the fully-qualified name of the LanternService's DeleteEdge
	// RPC.
	LanternServiceDeleteEdgeProcedure = "/graph.v1.LanternService/DeleteEdge"
	// LanternServiceDeleteEdgesProcedure is the fully-qualified name of the LanternService's
	// DeleteEdges RPC.
	LanternServiceDeleteEdgesProcedure = "/graph.v1.LanternService/DeleteEdges"
	// LanternServiceDeleteEdgesByPrefixProcedure is the fully-qualified name of the LanternService's
	// DeleteEdgesByPrefix RPC.
	LanternServiceDeleteEdgesByPrefixProcedure = "/graph.v1.LanternService/DeleteEdgesByPrefix"
	// LanternServiceScanEdgesProcedure is the fully-qualified name of the LanternService's ScanEdges
	// RPC.
	LanternServiceScanEdgesProcedure = "/graph.v1.LanternService/ScanEdges"
	// LanternServiceGetServerStatusProcedure is the fully-qualified name of the LanternService's
	// GetServerStatus RPC.
	LanternServiceGetServerStatusProcedure = "/graph.v1.LanternService/GetServerStatus"
	// LanternServiceGetReplicationStatusProcedure is the fully-qualified name of the LanternService's
	// GetReplicationStatus RPC.
	LanternServiceGetReplicationStatusProcedure = "/graph.v1.LanternService/GetReplicationStatus"
	// LanternServiceBackupSnapshotProcedure is the fully-qualified name of the LanternService's
	// BackupSnapshot RPC.
	LanternServiceBackupSnapshotProcedure = "/graph.v1.LanternService/BackupSnapshot"
)

// LanternServiceClient is a client for the graph.v1.LanternService service.
type LanternServiceClient interface {
	Illuminate(context.Context, *connect.Request[v1.IlluminateRequest]) (*connect.Response[v1.IlluminateResponse], error)
	GetVertex(context.Context, *connect.Request[v1.GetVertexRequest]) (*connect.Response[v1.GetVertexResponse], error)
	// GetVertices reads several vertices in one round trip.
	GetVertices(context.Context, *connect.Request[v1.GetVerticesRequest]) (*connect.Response[v1.GetVerticesResponse], error)
	// PutVertex writes a single vertex. Thin facade over PutVertices.
	PutVertex(context.Context, *connect.Request[v1.PutVertexRequest]) (*connect.Response[v1.PutVertexResponse], error)
	PutVertices(context.Context, *connect.Request[v1.PutVerticesRequest]) (*connect.Response[v1.PutVerticesResponse], error)
	DeleteVertex(context.Context, *connect.Request[v1.DeleteVertexRequest]) (*connect.Response[v1.DeleteVertexResponse], error)
	// DeleteVertices removes several vertices in one round trip.
	DeleteVertices(context.Context, *connect.Request[v1.DeleteVerticesRequest]) (*connect.Response[v1.DeleteVerticesResponse], error)
	// ScanVertices streams vertices whose key starts with the given prefix in
	// ascending order, page by page. Plural-only — prefix scan is inherently
	// plural.
	ScanVertices(context.Context, *connect.Request[v1.ScanVerticesRequest]) (*connect.Response[v1.ScanVerticesResponse], error)
	// ScanVertexKeys streams just the KEYS (no values) of vertices whose key
	// starts with the given prefix, page by page — the wire-efficient backing
	// RPC for the `keys` CLI verb. A non-empty prefix is REQUIRED. Plural-only.
	ScanVertexKeys(context.Context, *connect.Request[v1.ScanVertexKeysRequest]) (*connect.Response[v1.ScanVertexKeysResponse], error)
	// SearchVertices returns vertices ranked by full-text relevance over their
	// content (key + value), optionally scoped to a key prefix. Requires the
	// server-side search index (LANTERN_SEARCH_ENABLED, on by default);
	// returns FAILED_PRECONDITION when disabled. Plural-only — ranked search
	// is inherently plural.
	SearchVertices(context.Context, *connect.Request[v1.SearchVerticesRequest]) (*connect.Response[v1.SearchVerticesResponse], error)
	// CountVerticesByPrefix returns the number of live vertices whose key
	// starts with the given prefix.
	CountVerticesByPrefix(context.Context, *connect.Request[v1.CountVerticesByPrefixRequest]) (*connect.Response[v1.CountVerticesByPrefixResponse], error)
	// DeleteVerticesByPrefix deletes up to `limit` vertices whose key starts
	// with the given prefix. Pass `dry_run = true` to preview the count
	// without mutating state.
	DeleteVerticesByPrefix(context.Context, *connect.Request[v1.DeleteVerticesByPrefixRequest]) (*connect.Response[v1.DeleteVerticesByPrefixResponse], error)
	GetEdge(context.Context, *connect.Request[v1.GetEdgeRequest]) (*connect.Response[v1.GetEdgeResponse], error)
	// GetEdges reads several edges in one round trip.
	GetEdges(context.Context, *connect.Request[v1.GetEdgesRequest]) (*connect.Response[v1.GetEdgesResponse], error)
	// AddEdge is non-idempotent (accumulates weight). Thin facade over AddEdges.
	AddEdge(context.Context, *connect.Request[v1.AddEdgeRequest]) (*connect.Response[v1.AddEdgeResponse], error)
	// AddEdges is non-idempotent (accumulates weight). POST per REST conventions.
	AddEdges(context.Context, *connect.Request[v1.AddEdgesRequest]) (*connect.Response[v1.AddEdgesResponse], error)
	// PutEdge is idempotent (replaces weight). Thin facade over PutEdges.
	PutEdge(context.Context, *connect.Request[v1.PutEdgeRequest]) (*connect.Response[v1.PutEdgeResponse], error)
	// PutEdges is idempotent (replaces weight). PUT per REST conventions.
	PutEdges(context.Context, *connect.Request[v1.PutEdgesRequest]) (*connect.Response[v1.PutEdgesResponse], error)
	DeleteEdge(context.Context, *connect.Request[v1.DeleteEdgeRequest]) (*connect.Response[v1.DeleteEdgeResponse], error)
	// DeleteEdges removes several edges in one round trip.
	DeleteEdges(context.Context, *connect.Request[v1.DeleteEdgesRequest]) (*connect.Response[v1.DeleteEdgesResponse], error)
	// DeleteEdgesByPrefix deletes up to `limit` live edges whose tail key
	// starts with `tail_prefix` AND whose head key starts with `head_prefix`.
	// At least one prefix must be non-empty. Pass `dry_run = true` to preview
	// the count without mutating state. Plural-only — prefix delete is
	// inherently plural.
	DeleteEdgesByPrefix(context.Context, *connect.Request[v1.DeleteEdgesByPrefixRequest]) (*connect.Response[v1.DeleteEdgesByPrefixResponse], error)
	// ScanEdges streams edges whose tail key starts with `tail_prefix` AND
	// whose head key starts with `head_prefix`, in ascending (tail, head)
	// order, page by page. Plural-only — prefix scan is inherently plural.
	ScanEdges(context.Context, *connect.Request[v1.ScanEdgesRequest]) (*connect.Response[v1.ScanEdgesResponse], error)
	// GetServerStatus returns a flat snapshot of the server's identity,
	// build info, configuration ceilings, and current live vertex/edge
	// counts. Read-only and cheap — intended for the admin UI's "Ops"
	// tab and lightweight smoke-test tooling. Auth is the caller's
	// responsibility; no PII is returned.
	GetServerStatus(context.Context, *connect.Request[v1.GetServerStatusRequest]) (*connect.Response[v1.GetServerStatusResponse], error)
	// GetReplicationStatus returns a flat snapshot of the local node's
	// outbound peer-replication state. Read-only — no peer add/remove
	// surface is exposed (see #315 out-of-scope). Cheap to call from a
	// dashboard at any cadence the operator finds useful. On
	// single-instance deployments enabled=false and peers is empty.
	GetReplicationStatus(context.Context, *connect.Request[v1.GetReplicationStatusRequest]) (*connect.Response[v1.GetReplicationStatusResponse], error)
	// BackupSnapshot streams a whole-graph, point-in-time backup: every
	// live vertex and folded edge as a BackupRecord, materialised under a
	// single GraphCache lock (SnapshotGraph). Unlike the replication
	// Snapshot RPC it has NO replication gate — it works on a single node.
	// vertex_prefix optionally scopes the backup to an induced subgraph.
	// The restore side replays records through PutVertices / PutEdges, so
	// there is no dedicated restore RPC.
	BackupSnapshot(context.Context, *connect.Request[v1.BackupSnapshotRequest]) (*connect.ServerStreamForClient[v1.BackupSnapshotResponse], error)
}

// NewLanternServiceClient constructs a client for the graph.v1.LanternService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLanternServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LanternServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lanternServiceMethods := v1.File_graph_v1_graph_proto.Services().ByName("LanternService").Methods()
	return &lanternServiceClient{
		illuminate: connect.NewClient[v1.IlluminateRequest, v1.IlluminateResponse](
			httpClient,
			baseURL+LanternServiceIlluminateProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("Illuminate")),
			connect.WithClientOptions(opts...),
		),
		getVertex: connect.NewClient[v1.GetVertexRequest, v1.GetVertexResponse](
			httpClient,
			baseURL+LanternServiceGetVertexProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("GetVertex")),
			connect.WithClientOptions(opts...),
		),
		getVertices: connect.NewClient[v1.GetVerticesRequest, v1.GetVerticesResponse](
			httpClient,
			baseURL+LanternServiceGetVerticesProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("GetVertices")),
			connect.WithClientOptions(opts...),
		),
		putVertex: connect.NewClient[v1.PutVertexRequest, v1.PutVertexResponse](
			httpClient,
			baseURL+LanternServicePutVertexProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("PutVertex")),
			connect.WithClientOptions(opts...),
		),
		putVertices: connect.NewClient[v1.PutVerticesRequest, v1.PutVerticesResponse](
			httpClient,
			baseURL+LanternServicePutVerticesProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("PutVertices")),
			connect.WithClientOptions(opts...),
		),
		deleteVertex: connect.NewClient[v1.DeleteVertexRequest, v1.DeleteVertexResponse](
			httpClient,
			baseURL+LanternServiceDeleteVertexProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("DeleteVertex")),
			connect.WithClientOptions(opts...),
		),
		deleteVertices: connect.NewClient[v1.DeleteVerticesRequest, v1.DeleteVerticesResponse](
			httpClient,
			baseURL+LanternServiceDeleteVerticesProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("DeleteVertices")),
			connect.WithClientOptions(opts...),
		),
		scanVertices: connect.NewClient[v1.ScanVerticesRequest, v1.ScanVerticesResponse](
			httpClient,
			baseURL+LanternServiceScanVerticesProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("ScanVertices")),
			connect.WithClientOptions(opts...),
		),
		scanVertexKeys: connect.NewClient[v1.ScanVertexKeysRequest, v1.ScanVertexKeysResponse](
			httpClient,
			baseURL+LanternServiceScanVertexKeysProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("ScanVertexKeys")),
			connect.WithClientOptions(opts...),
		),
		searchVertices: connect.NewClient[v1.SearchVerticesRequest, v1.SearchVerticesResponse](
			httpClient,
			baseURL+LanternServiceSearchVerticesProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("SearchVertices")),
			connect.WithClientOptions(opts...),
		),
		countVerticesByPrefix: connect.NewClient[v1.CountVerticesByPrefixRequest, v1.CountVerticesByPrefixResponse](
			httpClient,
			baseURL+LanternServiceCountVerticesByPrefixProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("CountVerticesByPrefix")),
			connect.WithClientOptions(opts...),
		),
		deleteVerticesByPrefix: connect.NewClient[v1.DeleteVerticesByPrefixRequest, v1.DeleteVerticesByPrefixResponse](
			httpClient,
			baseURL+LanternServiceDeleteVerticesByPrefixProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("DeleteVerticesByPrefix")),
			connect.WithClientOptions(opts...),
		),
		getEdge: connect.NewClient[v1.GetEdgeRequest, v1.GetEdgeResponse](
			httpClient,
			baseURL+LanternServiceGetEdgeProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("GetEdge")),
			connect.WithClientOptions(opts...),
		),
		getEdges: connect.NewClient[v1.GetEdgesRequest, v1.GetEdgesResponse](
			httpClient,
			baseURL+LanternServiceGetEdgesProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("GetEdges")),
			connect.WithClientOptions(opts...),
		),
		addEdge: connect.NewClient[v1.AddEdgeRequest, v1.AddEdgeResponse](
			httpClient,
			baseURL+LanternServiceAddEdgeProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("AddEdge")),
			connect.WithClientOptions(opts...),
		),
		addEdges: connect.NewClient[v1.AddEdgesRequest, v1.AddEdgesResponse](
			httpClient,
			baseURL+LanternServiceAddEdgesProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("AddEdges")),
			connect.WithClientOptions(opts...),
		),
		putEdge: connect.NewClient[v1.PutEdgeRequest, v1.PutEdgeResponse](
			httpClient,
			baseURL+LanternServicePutEdgeProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("PutEdge")),
			connect.WithClientOptions(opts...),
		),
		putEdges: connect.NewClient[v1.PutEdgesRequest, v1.PutEdgesResponse](
			httpClient,
			baseURL+LanternServicePutEdgesProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("PutEdges")),
			connect.WithClientOptions(opts...),
		),
		deleteEdge: connect.NewClient[v1.DeleteEdgeRequest, v1.DeleteEdgeResponse](
			httpClient,
			baseURL+LanternServiceDeleteEdgeProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("DeleteEdge")),
			connect.WithClientOptions(opts...),
		),
		deleteEdges: connect.NewClient[v1.DeleteEdgesRequest, v1.DeleteEdgesResponse](
			httpClient,
			baseURL+LanternServiceDeleteEdgesProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("DeleteEdges")),
			connect.WithClientOptions(opts...),
		),
		deleteEdgesByPrefix: connect.NewClient[v1.DeleteEdgesByPrefixRequest, v1.DeleteEdgesByPrefixResponse](
			httpClient,
			baseURL+LanternServiceDeleteEdgesByPrefixProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("DeleteEdgesByPrefix")),
			connect.WithClientOptions(opts...),
		),
		scanEdges: connect.NewClient[v1.ScanEdgesRequest, v1.ScanEdgesResponse](
			httpClient,
			baseURL+LanternServiceScanEdgesProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("ScanEdges")),
			connect.WithClientOptions(opts...),
		),
		getServerStatus: connect.NewClient[v1.GetServerStatusRequest, v1.GetServerStatusResponse](
			httpClient,
			baseURL+LanternServiceGetServerStatusProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("GetServerStatus")),
			connect.WithClientOptions(opts...),
		),
		getReplicationStatus: connect.NewClient[v1.GetReplicationStatusRequest, v1.GetReplicationStatusResponse](
			httpClient,
			baseURL+LanternServiceGetReplicationStatusProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("GetReplicationStatus")),
			connect.WithClientOptions(opts...),
		),
		backupSnapshot: connect.NewClient[v1.BackupSnapshotRequest, v1.BackupSnapshotResponse](
			httpClient,
			baseURL+LanternServiceBackupSnapshotProcedure,
			connect.WithSchema(lanternServiceMethods.ByName("BackupSnapshot")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lanternServiceClient implements LanternServiceClient.
type lanternServiceClient struct {
	illuminate             *connect.Client[v1.IlluminateRequest, v1.IlluminateResponse]
	getVertex              *connect.Client[v1.GetVertexRequest, v1.GetVertexResponse]
	getVertices            *connect.Client[v1.GetVerticesRequest, v1.GetVerticesResponse]
	putVertex              *connect.Client[v1.PutVertexRequest, v1.PutVertexResponse]
	putVertices            *connect.Client[v1.PutVerticesRequest, v1.PutVerticesResponse]
	deleteVertex           *connect.Client[v1.DeleteVertexRequest, v1.DeleteVertexResponse]
	deleteVertices         *connect.Client[v1.DeleteVerticesRequest, v1.DeleteVerticesResponse]
	scanVertices           *connect.Client[v1.ScanVerticesRequest, v1.ScanVerticesResponse]
	scanVertexKeys         *connect.Client[v1.ScanVertexKeysRequest, v1.ScanVertexKeysResponse]
	searchVertices         *connect.Client[v1.SearchVerticesRequest, v1.SearchVerticesResponse]
	countVerticesByPrefix  *connect.Client[v1.CountVerticesByPrefixRequest, v1.CountVerticesByPrefixResponse]
	deleteVerticesByPrefix *connect.Client[v1.DeleteVerticesByPrefixRequest, v1.DeleteVerticesByPrefixResponse]
	getEdge                *connect.Client[v1.GetEdgeRequest, v1.GetEdgeResponse]
	getEdges               *connect.Client[v1.GetEdgesRequest, v1.GetEdgesResponse]
	addEdge                *connect.Client[v1.AddEdgeRequest, v1.AddEdgeResponse]
	addEdges               *connect.Client[v1.AddEdgesRequest, v1.AddEdgesResponse]
	putEdge                *connect.Client[v1.PutEdgeRequest, v1.PutEdgeResponse]
	putEdges               *connect.Client[v1.PutEdgesRequest, v1.PutEdgesResponse]
	deleteEdge             *connect.Client[v1.DeleteEdgeRequest, v1.DeleteEdgeResponse]
	deleteEdges            *connect.Client[v1.DeleteEdgesRequest, v1.DeleteEdgesResponse]
	deleteEdgesByPrefix    *connect.Client[v1.DeleteEdgesByPrefixRequest, v1.DeleteEdgesByPrefixResponse]
	scanEdges              *connect.Client[v1.ScanEdgesRequest, v1.ScanEdgesResponse]
	getServerStatus        *connect.Client[v1.GetServerStatusRequest, v1.GetServerStatusResponse]
	getReplicationStatus   *connect.Client[v1.GetReplicationStatusRequest, v1.GetReplicationStatusResponse]
	backupSnapshot         *connect.Client[v1.BackupSnapshotRequest, v1.BackupSnapshotResponse]
}

// Illuminate calls graph.v1.LanternService.Illuminate.
func (c *lanternServiceClient) Illuminate(ctx context.Context, req *connect.Request[v1.IlluminateRequest]) (*connect.Response[v1.IlluminateResponse], error) {
	return c.illuminate.CallUnary(ctx, req)
}

// GetVertex calls graph.v1.LanternService.GetVertex.
func (c *lanternServiceClient) GetVertex(ctx context.Context, req *connect.Request[v1.GetVertexRequest]) (*connect.Response[v1.GetVertexResponse], error) {
	return c.getVertex.CallUnary(ctx, req)
}

// GetVertices calls graph.v1.LanternService.GetVertices.
func (c *lanternServiceClient) GetVertices(ctx context.Context, req *connect.Request[v1.GetVerticesRequest]) (*connect.Response[v1.GetVerticesResponse], error) {
	return c.getVertices.CallUnary(ctx, req)
}

// PutVertex calls graph.v1.LanternService.PutVertex.
func (c *lanternServiceClient) PutVertex(ctx context.Context, req *connect.Request[v1.PutVertexRequest]) (*connect.Response[v1.PutVertexResponse], error) {
	return c.putVertex.CallUnary(ctx, req)
}

// PutVertices calls graph.v1.LanternService.PutVertices.
func (c *lanternServiceClient) PutVertices(ctx context.Context, req *connect.Request[v1.PutVerticesRequest]) (*connect.Response[v1.PutVerticesResponse], error) {
	return c.putVertices.CallUnary(ctx, req)
}

// DeleteVertex calls graph.v1.LanternService.DeleteVertex.
func (c *lanternServiceClient) DeleteVertex(ctx context.Context, req *connect.Request[v1.DeleteVertexRequest]) (*connect.Response[v1.DeleteVertexResponse], error) {
	return c.deleteVertex.CallUnary(ctx, req)
}

// DeleteVertices calls graph.v1.LanternService.DeleteVertices.
func (c *lanternServiceClient) DeleteVertices(ctx context.Context, req *connect.Request[v1.DeleteVerticesRequest]) (*connect.Response[v1.DeleteVerticesResponse], error) {
	return c.deleteVertices.CallUnary(ctx, req)
}

// ScanVertices calls graph.v1.LanternService.ScanVertices.
func (c *lanternServiceClient) ScanVertices(ctx context.Context, req *connect.Request[v1.ScanVerticesRequest]) (*connect.Response[v1.ScanVerticesResponse], error) {
	return c.scanVertices.CallUnary(ctx, req)
}

// ScanVertexKeys calls graph.v1.LanternService.ScanVertexKeys.
func (c *lanternServiceClient) ScanVertexKeys(ctx context.Context, req *connect.Request[v1.ScanVertexKeysRequest]) (*connect.Response[v1.ScanVertexKeysResponse], error) {
	return c.scanVertexKeys.CallUnary(ctx, req)
}

// SearchVertices calls graph.v1.LanternService.SearchVertices.
func (c *lanternServiceClient) SearchVertices(ctx context.Context, req *connect.Request[v1.SearchVerticesRequest]) (*connect.Response[v1.SearchVerticesResponse], error) {
	return c.searchVertices.CallUnary(ctx, req)
}

// CountVerticesByPrefix calls graph.v1.LanternService.CountVerticesByPrefix.
func (c *lanternServiceClient) CountVerticesByPrefix(ctx context.Context, req *connect.Request[v1.CountVerticesByPrefixRequest]) (*connect.Response[v1.CountVerticesByPrefixResponse], error) {
	return c.countVerticesByPrefix.CallUnary(ctx, req)
}

// DeleteVerticesByPrefix calls graph.v1.LanternService.DeleteVerticesByPrefix.
func (c *lanternServiceClient) DeleteVerticesByPrefix(ctx context.Context, req *connect.Request[v1.DeleteVerticesByPrefixRequest]) (*connect.Response[v1.DeleteVerticesByPrefixResponse], error) {
	return c.deleteVerticesByPrefix.CallUnary(ctx, req)
}

// GetEdge calls graph.v1.LanternService.GetEdge.
func (c *lanternServiceClient) GetEdge(ctx context.Context, req *connect.Request[v1.GetEdgeRequest]) (*connect.Response[v1.GetEdgeResponse], error) {
	return c.getEdge.CallUnary(ctx, req)
}

// GetEdges calls graph.v1.LanternService.GetEdges.
func (c *lanternServiceClient) GetEdges(ctx context.Context, req *connect.Request[v1.GetEdgesRequest]) (*connect.Response[v1.GetEdgesResponse], error) {
	return c.getEdges.CallUnary(ctx, req)
}

// AddEdge calls graph.v1.LanternService.AddEdge.
func (c *lanternServiceClient) AddEdge(ctx context.Context, req *connect.Request[v1.AddEdgeRequest]) (*connect.Response[v1.AddEdgeResponse], error) {
	return c.addEdge.CallUnary(ctx, req)
}

// AddEdges calls graph.v1.LanternService.AddEdges.
func (c *lanternServiceClient) AddEdges(ctx context.Context, req *connect.Request[v1.AddEdgesRequest]) (*connect.Response[v1.AddEdgesResponse], error) {
	return c.addEdges.CallUnary(ctx, req)
}

// PutEdge calls graph.v1.LanternService.PutEdge.
func (c *lanternServiceClient) PutEdge(ctx context.Context, req *connect.Request[v1.PutEdgeRequest]) (*connect.Response[v1.PutEdgeResponse], error) {
	return c.putEdge.CallUnary(ctx, req)
}

// PutEdges calls graph.v1.LanternService.PutEdges.
func (c *lanternServiceClient) PutEdges(ctx context.Context, req *connect.Request[v1.PutEdgesRequest]) (*connect.Response[v1.PutEdgesResponse], error) {
	return c.putEdges.CallUnary(ctx, req)
}

// DeleteEdge calls graph.v1.LanternService.DeleteEdge.
func (c *lanternServiceClient) DeleteEdge(ctx context.Context, req *connect.Request[v1.DeleteEdgeRequest]) (*connect.Response[v1.DeleteEdgeResponse], error) {
	return c.deleteEdge.CallUnary(ctx, req)
}

// DeleteEdges calls graph.v1.LanternService.DeleteEdges.
func (c *lanternServiceClient) DeleteEdges(ctx context.Context, req *connect.Request[v1.DeleteEdgesRequest]) (*connect.Response[v1.DeleteEdgesResponse], error) {
	return c.deleteEdges.CallUnary(ctx, req)
}

// DeleteEdgesByPrefix calls graph.v1.LanternService.DeleteEdgesByPrefix.
func (c *lanternServiceClient) DeleteEdgesByPrefix(ctx context.Context, req *connect.Request[v1.DeleteEdgesByPrefixRequest]) (*connect.Response[v1.DeleteEdgesByPrefixResponse], error) {
	return c.deleteEdgesByPrefix.CallUnary(ctx, req)
}

// ScanEdges calls graph.v1.LanternService.ScanEdges.
func (c *lanternServiceClient) ScanEdges(ctx context.Context, req *connect.Request[v1.ScanEdgesRequest]) (*connect.Response[v1.ScanEdgesResponse], error) {
	return c.scanEdges.CallUnary(ctx, req)
}

// GetServerStatus calls graph.v1.LanternService.GetServerStatus.
func (c *lanternServiceClient) GetServerStatus(ctx context.Context, req *connect.Request[v1.GetServerStatusRequest]) (*connect.Response[v1.GetServerStatusResponse], error) {
	return c.getServerStatus.CallUnary(ctx, req)
}

// GetReplicationStatus calls graph.v1.LanternService.GetReplicationStatus.
func (c *lanternServiceClient) GetReplicationStatus(ctx context.Context, req *connect.Request[v1.GetReplicationStatusRequest]) (*connect.Response[v1.GetReplicationStatusResponse], error) {
	return c.getReplicationStatus.CallUnary(ctx, req)
}

// BackupSnapshot calls graph.v1.LanternService.BackupSnapshot.
func (c *lanternServiceClient) BackupSnapshot(ctx context.Context, req *connect.Request[v1.BackupSnapshotRequest]) (*connect.ServerStreamForClient[v1.BackupSnapshotResponse], error) {
	return c.backupSnapshot.CallServerStream(ctx, req)
}

// LanternServiceHandler is an implementation of the graph.v1.LanternService service.
type LanternServiceHandler interface {
	Illuminate(context.Context, *connect.Request[v1.IlluminateRequest]) (*connect.Response[v1.IlluminateResponse], error)
	GetVertex(context.Context, *connect.Request[v1.GetVertexRequest]) (*connect.Response[v1.GetVertexResponse], error)
	// GetVertices reads several vertices in one round trip.
	GetVertices(context.Context, *connect.Request[v1.GetVerticesRequest]) (*connect.Response[v1.GetVerticesResponse], error)
	// PutVertex writes a single vertex. Thin facade over PutVertices.
	PutVertex(context.Context, *connect.Request[v1.PutVertexRequest]) (*connect.Response[v1.PutVertexResponse], error)
	PutVertices(context.Context, *connect.Request[v1.PutVerticesRequest]) (*connect.Response[v1.PutVerticesResponse], error)
	DeleteVertex(context.Context, *connect.Request[v1.DeleteVertexRequest]) (*connect.Response[v1.DeleteVertexResponse], error)
	// DeleteVertices removes several vertices in one round trip.
	DeleteVertices(context.Context, *connect.Request[v1.DeleteVerticesRequest]) (*connect.Response[v1.DeleteVerticesResponse], error)
	// ScanVertices streams vertices whose key starts with the given prefix in
	// ascending order, page by page. Plural-only — prefix scan is inherently
	// plural.
	ScanVertices(context.Context, *connect.Request[v1.ScanVerticesRequest]) (*connect.Response[v1.ScanVerticesResponse], error)
	// ScanVertexKeys streams just the KEYS (no values) of vertices whose key
	// starts with the given prefix, page by page — the wire-efficient backing
	// RPC for the `keys` CLI verb. A non-empty prefix is REQUIRED. Plural-only.
	ScanVertexKeys(context.Context, *connect.Request[v1.ScanVertexKeysRequest]) (*connect.Response[v1.ScanVertexKeysResponse], error)
	// SearchVertices returns vertices ranked by full-text relevance over their
	// content (key + value), optionally scoped to a key prefix. Requires the
	// server-side search index (LANTERN_SEARCH_ENABLED, on by default);
	// returns FAILED_PRECONDITION when disabled. Plural-only — ranked search
	// is inherently plural.
	SearchVertices(context.Context, *connect.Request[v1.SearchVerticesRequest]) (*connect.Response[v1.SearchVerticesResponse], error)
	// CountVerticesByPrefix returns the number of live vertices whose key
	// starts with the given prefix.
	CountVerticesByPrefix(context.Context, *connect.Request[v1.CountVerticesByPrefixRequest]) (*connect.Response[v1.CountVerticesByPrefixResponse], error)
	// DeleteVerticesByPrefix deletes up to `limit` vertices whose key starts
	// with the given prefix. Pass `dry_run = true` to preview the count
	// without mutating state.
	DeleteVerticesByPrefix(context.Context, *connect.Request[v1.DeleteVerticesByPrefixRequest]) (*connect.Response[v1.DeleteVerticesByPrefixResponse], error)
	GetEdge(context.Context, *connect.Request[v1.GetEdgeRequest]) (*connect.Response[v1.GetEdgeResponse], error)
	// GetEdges reads several edges in one round trip.
	GetEdges(context.Context, *connect.Request[v1.GetEdgesRequest]) (*connect.Response[v1.GetEdgesResponse], error)
	// AddEdge is non-idempotent (accumulates weight). Thin facade over AddEdges.
	AddEdge(context.Context, *connect.Request[v1.AddEdgeRequest]) (*connect.Response[v1.AddEdgeResponse], error)
	// AddEdges is non-idempotent (accumulates weight). POST per REST conventions.
	AddEdges(context.Context, *connect.Request[v1.AddEdgesRequest]) (*connect.Response[v1.AddEdgesResponse], error)
	// PutEdge is idempotent (replaces weight). Thin facade over PutEdges.
	PutEdge(context.Context, *connect.Request[v1.PutEdgeRequest]) (*connect.Response[v1.PutEdgeResponse], error)
	// PutEdges is idempotent (replaces weight). PUT per REST conventions.
	PutEdges(context.Context, *connect.Request[v1.PutEdgesRequest]) (*connect.Response[v1.PutEdgesResponse], error)
	DeleteEdge(context.Context, *connect.Request[v1.DeleteEdgeRequest]) (*connect.Response[v1.DeleteEdgeResponse], error)
	// DeleteEdges removes several edges in one round trip.
	DeleteEdges(context.Context, *connect.Request[v1.DeleteEdgesRequest]) (*connect.Response[v1.DeleteEdgesResponse], error)
	// DeleteEdgesByPrefix deletes up to `limit` live edges whose tail key
	// starts with `tail_prefix` AND whose head key starts with `head_prefix`.
	// At least one prefix must be non-empty. Pass `dry_run = true` to preview
	// the count without mutating state. Plural-only — prefix delete is
	// inherently plural.
	DeleteEdgesByPrefix(context.Context, *connect.Request[v1.DeleteEdgesByPrefixRequest]) (*connect.Response[v1.DeleteEdgesByPrefixResponse], error)
	// ScanEdges streams edges whose tail key starts with `tail_prefix` AND
	// whose head key starts with `head_prefix`, in ascending (tail, head)
	// order, page by page. Plural-only — prefix scan is inherently plural.
	ScanEdges(context.Context, *connect.Request[v1.ScanEdgesRequest]) (*connect.Response[v1.ScanEdgesResponse], error)
	// GetServerStatus returns a flat snapshot of the server's identity,
	// build info, configuration ceilings, and current live vertex/edge
	// counts. Read-only and cheap — intended for the admin UI's "Ops"
	// tab and lightweight smoke-test tooling. Auth is the caller's
	// responsibility; no PII is returned.
	GetServerStatus(context.Context, *connect.Request[v1.GetServerStatusRequest]) (*connect.Response[v1.GetServerStatusResponse], error)
	// GetReplicationStatus returns a flat snapshot of the local node's
	// outbound peer-replication state. Read-only — no peer add/remove
	// surface is exposed (see #315 out-of-scope). Cheap to call from a
	// dashboard at any cadence the operator finds useful. On
	// single-instance deployments enabled=false and peers is empty.
	GetReplicationStatus(context.Context, *connect.Request[v1.GetReplicationStatusRequest]) (*connect.Response[v1.GetReplicationStatusResponse], error)
	// BackupSnapshot streams a whole-graph, point-in-time backup: every
	// live vertex and folded edge as a BackupRecord, materialised under a
	// single GraphCache lock (SnapshotGraph). Unlike the replication
	// Snapshot RPC it has NO replication gate — it works on a single node.
	// vertex_prefix optionally scopes the backup to an induced subgraph.
	// The restore side replays records through PutVertices / PutEdges, so
	// there is no dedicated restore RPC.
	BackupSnapshot(context.Context, *connect.Request[v1.BackupSnapshotRequest], *connect.ServerStream[v1.BackupSnapshotResponse]) error
}

// NewLanternServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLanternServiceHandler(svc LanternServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lanternServiceMethods := v1.File_graph_v1_graph_proto.Services().ByName("LanternService").Methods()
	lanternServiceIlluminateHandler := connect.NewUnaryHandler(
		LanternServiceIlluminateProcedure,
		svc.Illuminate,
		connect.WithSchema(lanternServiceMethods.ByName("Illuminate")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceGetVertexHandler := connect.NewUnaryHandler(
		LanternServiceGetVertexProcedure,
		svc.GetVertex,
		connect.WithSchema(lanternServiceMethods.ByName("GetVertex")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceGetVerticesHandler := connect.NewUnaryHandler(
		LanternServiceGetVerticesProcedure,
		svc.GetVertices,
		connect.WithSchema(lanternServiceMethods.ByName("GetVertices")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServicePutVertexHandler := connect.NewUnaryHandler(
		LanternServicePutVertexProcedure,
		svc.PutVertex,
		connect.WithSchema(lanternServiceMethods.ByName("PutVertex")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServicePutVerticesHandler := connect.NewUnaryHandler(
		LanternServicePutVerticesProcedure,
		svc.PutVertices,
		connect.WithSchema(lanternServiceMethods.ByName("PutVertices")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceDeleteVertexHandler := connect.NewUnaryHandler(
		LanternServiceDeleteVertexProcedure,
		svc.DeleteVertex,
		connect.WithSchema(lanternServiceMethods.ByName("DeleteVertex")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceDeleteVerticesHandler := connect.NewUnaryHandler(
		LanternServiceDeleteVerticesProcedure,
		svc.DeleteVertices,
		connect.WithSchema(lanternServiceMethods.ByName("DeleteVertices")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceScanVerticesHandler := connect.NewUnaryHandler(
		LanternServiceScanVerticesProcedure,
		svc.ScanVertices,
		connect.WithSchema(lanternServiceMethods.ByName("ScanVertices")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceScanVertexKeysHandler := connect.NewUnaryHandler(
		LanternServiceScanVertexKeysProcedure,
		svc.ScanVertexKeys,
		connect.WithSchema(lanternServiceMethods.ByName("ScanVertexKeys")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceSearchVerticesHandler := connect.NewUnaryHandler(
		LanternServiceSearchVerticesProcedure,
		svc.SearchVertices,
		connect.WithSchema(lanternServiceMethods.ByName("SearchVertices")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceCountVerticesByPrefixHandler := connect.NewUnaryHandler(
		LanternServiceCountVerticesByPrefixProcedure,
		svc.CountVerticesByPrefix,
		connect.WithSchema(lanternServiceMethods.ByName("CountVerticesByPrefix")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceDeleteVerticesByPrefixHandler := connect.NewUnaryHandler(
		LanternServiceDeleteVerticesByPrefixProcedure,
		svc.DeleteVerticesByPrefix,
		connect.WithSchema(lanternServiceMethods.ByName("DeleteVerticesByPrefix")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceGetEdgeHandler := connect.NewUnaryHandler(
		LanternServiceGetEdgeProcedure,
		svc.GetEdge,
		connect.WithSchema(lanternServiceMethods.ByName("GetEdge")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceGetEdgesHandler := connect.NewUnaryHandler(
		LanternServiceGetEdgesProcedure,
		svc.GetEdges,
		connect.WithSchema(lanternServiceMethods.ByName("GetEdges")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceAddEdgeHandler := connect.NewUnaryHandler(
		LanternServiceAddEdgeProcedure,
		svc.AddEdge,
		connect.WithSchema(lanternServiceMethods.ByName("AddEdge")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceAddEdgesHandler := connect.NewUnaryHandler(
		LanternServiceAddEdgesProcedure,
		svc.AddEdges,
		connect.WithSchema(lanternServiceMethods.ByName("AddEdges")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServicePutEdgeHandler := connect.NewUnaryHandler(
		LanternServicePutEdgeProcedure,
		svc.PutEdge,
		connect.WithSchema(lanternServiceMethods.ByName("PutEdge")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServicePutEdgesHandler := connect.NewUnaryHandler(
		LanternServicePutEdgesProcedure,
		svc.PutEdges,
		connect.WithSchema(lanternServiceMethods.ByName("PutEdges")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceDeleteEdgeHandler := connect.NewUnaryHandler(
		LanternServiceDeleteEdgeProcedure,
		svc.DeleteEdge,
		connect.WithSchema(lanternServiceMethods.ByName("DeleteEdge")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceDeleteEdgesHandler := connect.NewUnaryHandler(
		LanternServiceDeleteEdgesProcedure,
		svc.DeleteEdges,
		connect.WithSchema(lanternServiceMethods.ByName("DeleteEdges")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceDeleteEdgesByPrefixHandler := connect.NewUnaryHandler(
		LanternServiceDeleteEdgesByPrefixProcedure,
		svc.DeleteEdgesByPrefix,
		connect.WithSchema(lanternServiceMethods.ByName("DeleteEdgesByPrefix")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceScanEdgesHandler := connect.NewUnaryHandler(
		LanternServiceScanEdgesProcedure,
		svc.ScanEdges,
		connect.WithSchema(lanternServiceMethods.ByName("ScanEdges")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceGetServerStatusHandler := connect.NewUnaryHandler(
		LanternServiceGetServerStatusProcedure,
		svc.GetServerStatus,
		connect.WithSchema(lanternServiceMethods.ByName("GetServerStatus")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceGetReplicationStatusHandler := connect.NewUnaryHandler(
		LanternServiceGetReplicationStatusProcedure,
		svc.GetReplicationStatus,
		connect.WithSchema(lanternServiceMethods.ByName("GetReplicationStatus")),
		connect.WithHandlerOptions(opts...),
	)
	lanternServiceBackupSnapshotHandler := connect.NewServerStreamHandler(
		LanternServiceBackupSnapshotProcedure,
		svc.BackupSnapshot,
		connect.WithSchema(lanternServiceMethods.ByName("BackupSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graph.v1.LanternService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LanternServiceIlluminateProcedure:
			lanternServiceIlluminateHandler.ServeHTTP(w, r)
		case LanternServiceGetVertexProcedure:
			lanternServiceGetVertexHandler.ServeHTTP(w, r)
		case LanternServiceGetVerticesProcedure:
			lanternServiceGetVerticesHandler.ServeHTTP(w, r)
		case LanternServicePutVertexProcedure:
			lanternServicePutVertexHandler.ServeHTTP(w, r)
		case LanternServicePutVerticesProcedure:
			lanternServicePutVerticesHandler.ServeHTTP(w, r)
		case LanternServiceDeleteVertexProcedure:
			lanternServiceDeleteVertexHandler.ServeHTTP(w, r)
		case LanternServiceDeleteVerticesProcedure:
			lanternServiceDeleteVerticesHandler.ServeHTTP(w, r)
		case LanternServiceScanVerticesProcedure:
			lanternServiceScanVerticesHandler.ServeHTTP(w, r)
		case LanternServiceScanVertexKeysProcedure:
			lanternServiceScanVertexKeysHandler.ServeHTTP(w, r)
		case LanternServiceSearchVerticesProcedure:
			lanternServiceSearchVerticesHandler.ServeHTTP(w, r)
		case LanternServiceCountVerticesByPrefixProcedure:
			lanternServiceCountVerticesByPrefixHandler.ServeHTTP(w, r)
		case LanternServiceDeleteVerticesByPrefixProcedure:
			lanternServiceDeleteVerticesByPrefixHandler.ServeHTTP(w, r)
		case LanternServiceGetEdgeProcedure:
			lanternServiceGetEdgeHandler.ServeHTTP(w, r)
		case LanternServiceGetEdgesProcedure:
			lanternServiceGetEdgesHandler.ServeHTTP(w, r)
		case LanternServiceAddEdgeProcedure:
			lanternServiceAddEdgeHandler.ServeHTTP(w, r)
		case LanternServiceAddEdgesProcedure:
			lanternServiceAddEdgesHandler.ServeHTTP(w, r)
		case LanternServicePutEdgeProcedure:
			lanternServicePutEdgeHandler.ServeHTTP(w, r)
		case LanternServicePutEdgesProcedure:
			lanternServicePutEdgesHandler.ServeHTTP(w, r)
		case LanternServiceDeleteEdgeProcedure:
			lanternServiceDeleteEdgeHandler.ServeHTTP(w, r)
		case LanternServiceDeleteEdgesProcedure:
			lanternServiceDeleteEdgesHandler.ServeHTTP(w, r)
		case LanternServiceDeleteEdgesByPrefixProcedure:
			lanternServiceDeleteEdgesByPrefixHandler.ServeHTTP(w, r)
		case LanternServiceScanEdgesProcedure:
			lanternServiceScanEdgesHandler.ServeHTTP(w, r)
		case LanternServiceGetServerStatusProcedure:
			lanternServiceGetServerStatusHandler.ServeHTTP(w, r)
		case LanternServiceGetReplicationStatusProcedure:
			lanternServiceGetReplicationStatusHandler.ServeHTTP(w, r)
		case LanternServiceBackupSnapshotProcedure:
			lanternServiceBackupSnapshotHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLanternServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLanternServiceHandler struct{}

func (UnimplementedLanternServiceHandler) Illuminate(context.Context, *connect.Request[v1.IlluminateRequest]) (*connect.Response[v1.IlluminateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.Illuminate is not implemented"))
}

func (UnimplementedLanternServiceHandler) GetVertex(context.Context, *connect.Request[v1.GetVertexRequest]) (*connect.Response[v1.GetVertexResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.GetVertex is not implemented"))
}

func (UnimplementedLanternServiceHandler) GetVertices(context.Context, *connect.Request[v1.GetVerticesRequest]) (*connect.Response[v1.GetVerticesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.GetVertices is not implemented"))
}

func (UnimplementedLanternServiceHandler) PutVertex(context.Context, *connect.Request[v1.PutVertexRequest]) (*connect.Response[v1.PutVertexResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.PutVertex is not implemented"))
}

func (UnimplementedLanternServiceHandler) PutVertices(context.Context, *connect.Request[v1.PutVerticesRequest]) (*connect.Response[v1.PutVerticesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.PutVertices is not implemented"))
}

func (UnimplementedLanternServiceHandler) DeleteVertex(context.Context, *connect.Request[v1.DeleteVertexRequest]) (*connect.Response[v1.DeleteVertexResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.DeleteVertex is not implemented"))
}

func (UnimplementedLanternServiceHandler) DeleteVertices(context.Context, *connect.Request[v1.DeleteVerticesRequest]) (*connect.Response[v1.DeleteVerticesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.DeleteVertices is not implemented"))
}

func (UnimplementedLanternServiceHandler) ScanVertices(context.Context, *connect.Request[v1.ScanVerticesRequest]) (*connect.Response[v1.ScanVerticesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.ScanVertices is not implemented"))
}

func (UnimplementedLanternServiceHandler) ScanVertexKeys(context.Context, *connect.Request[v1.ScanVertexKeysRequest]) (*connect.Response[v1.ScanVertexKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.ScanVertexKeys is not implemented"))
}

func (UnimplementedLanternServiceHandler) SearchVertices(context.Context, *connect.Request[v1.SearchVerticesRequest]) (*connect.Response[v1.SearchVerticesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.SearchVertices is not implemented"))
}

func (UnimplementedLanternServiceHandler) CountVerticesByPrefix(context.Context, *connect.Request[v1.CountVerticesByPrefixRequest]) (*connect.Response[v1.CountVerticesByPrefixResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.CountVerticesByPrefix is not implemented"))
}

func (UnimplementedLanternServiceHandler) DeleteVerticesByPrefix(context.Context, *connect.Request[v1.DeleteVerticesByPrefixRequest]) (*connect.Response[v1.DeleteVerticesByPrefixResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.DeleteVerticesByPrefix is not implemented"))
}

func (UnimplementedLanternServiceHandler) GetEdge(context.Context, *connect.Request[v1.GetEdgeRequest]) (*connect.Response[v1.GetEdgeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.GetEdge is not implemented"))
}

func (UnimplementedLanternServiceHandler) GetEdges(context.Context, *connect.Request[v1.GetEdgesRequest]) (*connect.Response[v1.GetEdgesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.GetEdges is not implemented"))
}

func (UnimplementedLanternServiceHandler) AddEdge(context.Context, *connect.Request[v1.AddEdgeRequest]) (*connect.Response[v1.AddEdgeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.AddEdge is not implemented"))
}

func (UnimplementedLanternServiceHandler) AddEdges(context.Context, *connect.Request[v1.AddEdgesRequest]) (*connect.Response[v1.AddEdgesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.AddEdges is not implemented"))
}

func (UnimplementedLanternServiceHandler) PutEdge(context.Context, *connect.Request[v1.PutEdgeRequest]) (*connect.Response[v1.PutEdgeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.PutEdge is not implemented"))
}

func (UnimplementedLanternServiceHandler) PutEdges(context.Context, *connect.Request[v1.PutEdgesRequest]) (*connect.Response[v1.PutEdgesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.PutEdges is not implemented"))
}

func (UnimplementedLanternServiceHandler) DeleteEdge(context.Context, *connect.Request[v1.DeleteEdgeRequest]) (*connect.Response[v1.DeleteEdgeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.DeleteEdge is not implemented"))
}

func (UnimplementedLanternServiceHandler) DeleteEdges(context.Context, *connect.Request[v1.DeleteEdgesRequest]) (*connect.Response[v1.DeleteEdgesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.DeleteEdges is not implemented"))
}

func (UnimplementedLanternServiceHandler) DeleteEdgesByPrefix(context.Context, *connect.Request[v1.DeleteEdgesByPrefixRequest]) (*connect.Response[v1.DeleteEdgesByPrefixResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.DeleteEdgesByPrefix is not implemented"))
}

func (UnimplementedLanternServiceHandler) ScanEdges(context.Context, *connect.Request[v1.ScanEdgesRequest]) (*connect.Response[v1.ScanEdgesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.ScanEdges is not implemented"))
}

func (UnimplementedLanternServiceHandler) GetServerStatus(context.Context, *connect.Request[v1.GetServerStatusRequest]) (*connect.Response[v1.GetServerStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.GetServerStatus is not implemented"))
}

func (UnimplementedLanternServiceHandler) GetReplicationStatus(context.Context, *connect.Request[v1.GetReplicationStatusRequest]) (*connect.Response[v1.GetReplicationStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.GetReplicationStatus is not implemented"))
}

func (UnimplementedLanternServiceHandler) BackupSnapshot(context.Context, *connect.Request[v1.BackupSnapshotRequest], *connect.ServerStream[v1.BackupSnapshotResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternService.BackupSnapshot is not implemented"))
}
