// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: graph/v1/replication.proto

package graphv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/anaregdesign/lantern/pb/graph/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LanternReplicationServiceName is the fully-qualified name of the LanternReplicationService
	// service.
	LanternReplicationServiceName = "graph.v1.LanternReplicationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LanternReplicationServiceSubscribeProcedure is the fully-qualified name of the
	// LanternReplicationService's Subscribe RPC.
	LanternReplicationServiceSubscribeProcedure = "/graph.v1.LanternReplicationService/Subscribe"
	// LanternReplicationServiceSnapshotProcedure is the fully-qualified name of the
	// LanternReplicationService's Snapshot RPC.
	LanternReplicationServiceSnapshotProcedure = "/graph.v1.LanternReplicationService/Snapshot"
	// LanternReplicationServicePeerStatusProcedure is the fully-qualified name of the
	// LanternReplicationService's PeerStatus RPC.
	LanternReplicationServicePeerStatusProcedure = "/graph.v1.LanternReplicationService/PeerStatus"
)

// LanternReplicationServiceClient is a client for the graph.v1.LanternReplicationService service.
type LanternReplicationServiceClient interface {
	// Subscribe streams replicated mutations to a peer (or CDC consumer)
	// starting at `from_seq` (inclusive). The server replays any in-buffer
	// entries first, then streams live mutations as they are appended.
	//
	// If `from_seq` is below the server's first available seq the call
	// fails with FAILED_PRECONDITION ("gapped") and the caller must
	// snapshot + resubscribe. Slow consumers whose channel backs up may
	// also have the stream terminated with FAILED_PRECONDITION — the
	// remedy is the same.
	//
	// No HTTP gateway annotation: replication is intentionally exposed
	// only as Connect server-streaming (consumed by replication pumps on
	// peer nodes, never directly from browsers).
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.SubscribeResponse], error)
	// Snapshot streams a point-in-time, causally-consistent dump of every
	// live vertex and edge to a bootstrapping peer. The first frame is a
	// SnapshotHeader carrying the (cutoff_seq_per_origin, cutoff_hlc) the
	// server used to materialise the snapshot; the last frame is a
	// SnapshotFooter with the actual vertex / edge counts streamed.
	//
	// Bootstrap stitch contract: after receiving the SnapshotFooter the
	// peer MUST call `Subscribe(from_seq_per_origin = {origin: seq+1 for
	// each (origin, seq) in cutoff_seq_per_origin})` to pick up the live
	// tail. Without that the snapshot and the live stream cannot be glued
	// together without gap or overlap.
	//
	// No HTTP gateway annotation (parity with Subscribe).
	Snapshot(context.Context, *connect.Request[v1.SnapshotRequest]) (*connect.ServerStreamForClient[v1.SnapshotResponse], error)
	// PeerStatus returns the responder's per-origin (last_applied_seq,
	// last_applied_hlc) map. Used by anti-entropy (#186) as the
	// convergence safety net for the Subscribe pump: a periodic
	// PeerStatus poll lets each node detect that the peer's view of
	// some origin is ahead of its own and request the missing tail
	// (via Subscribe(from_seq = local+1)) or — when that returns
	// FailedPrecondition — fall back to Snapshot.
	//
	// The reply set always includes the responder's OWN origin (taken
	// from its mutation log's last appended seq + hlc) plus every
	// remote origin whose mutation has ever been applied via
	// ApplyMutation since process start. Origins the responder has
	// never seen are simply absent from the map.
	//
	// The RPC is intentionally unary and stateless — callers can
	// multiplex it across many peers without holding any server-side
	// resources. Returns Unavailable when the mutation log is unset
	// (single-instance test path).
	PeerStatus(context.Context, *connect.Request[v1.PeerStatusRequest]) (*connect.Response[v1.PeerStatusResponse], error)
}

// NewLanternReplicationServiceClient constructs a client for the graph.v1.LanternReplicationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLanternReplicationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LanternReplicationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lanternReplicationServiceMethods := v1.File_graph_v1_replication_proto.Services().ByName("LanternReplicationService").Methods()
	return &lanternReplicationServiceClient{
		subscribe: connect.NewClient[v1.SubscribeRequest, v1.SubscribeResponse](
			httpClient,
			baseURL+LanternReplicationServiceSubscribeProcedure,
			connect.WithSchema(lanternReplicationServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
		snapshot: connect.NewClient[v1.SnapshotRequest, v1.SnapshotResponse](
			httpClient,
			baseURL+LanternReplicationServiceSnapshotProcedure,
			connect.WithSchema(lanternReplicationServiceMethods.ByName("Snapshot")),
			connect.WithClientOptions(opts...),
		),
		peerStatus: connect.NewClient[v1.PeerStatusRequest, v1.PeerStatusResponse](
			httpClient,
			baseURL+LanternReplicationServicePeerStatusProcedure,
			connect.WithSchema(lanternReplicationServiceMethods.ByName("PeerStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lanternReplicationServiceClient implements LanternReplicationServiceClient.
type lanternReplicationServiceClient struct {
	subscribe  *connect.Client[v1.SubscribeRequest, v1.SubscribeResponse]
	snapshot   *connect.Client[v1.SnapshotRequest, v1.SnapshotResponse]
	peerStatus *connect.Client[v1.PeerStatusRequest, v1.PeerStatusResponse]
}

// Subscribe calls graph.v1.LanternReplicationService.Subscribe.
func (c *lanternReplicationServiceClient) Subscribe(ctx context.Context, req *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.SubscribeResponse], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// Snapshot calls graph.v1.LanternReplicationService.Snapshot.
func (c *lanternReplicationServiceClient) Snapshot(ctx context.Context, req *connect.Request[v1.SnapshotRequest]) (*connect.ServerStreamForClient[v1.SnapshotResponse], error) {
	return c.snapshot.CallServerStream(ctx, req)
}

// PeerStatus calls graph.v1.LanternReplicationService.PeerStatus.
func (c *lanternReplicationServiceClient) PeerStatus(ctx context.Context, req *connect.Request[v1.PeerStatusRequest]) (*connect.Response[v1.PeerStatusResponse], error) {
	return c.peerStatus.CallUnary(ctx, req)
}

// LanternReplicationServiceHandler is an implementation of the graph.v1.LanternReplicationService
// service.
type LanternReplicationServiceHandler interface {
	// Subscribe streams replicated mutations to a peer (or CDC consumer)
	// starting at `from_seq` (inclusive). The server replays any in-buffer
	// entries first, then streams live mutations as they are appended.
	//
	// If `from_seq` is below the server's first available seq the call
	// fails with FAILED_PRECONDITION ("gapped") and the caller must
	// snapshot + resubscribe. Slow consumers whose channel backs up may
	// also have the stream terminated with FAILED_PRECONDITION — the
	// remedy is the same.
	//
	// No HTTP gateway annotation: replication is intentionally exposed
	// only as Connect server-streaming (consumed by replication pumps on
	// peer nodes, never directly from browsers).
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest], *connect.ServerStream[v1.SubscribeResponse]) error
	// Snapshot streams a point-in-time, causally-consistent dump of every
	// live vertex and edge to a bootstrapping peer. The first frame is a
	// SnapshotHeader carrying the (cutoff_seq_per_origin, cutoff_hlc) the
	// server used to materialise the snapshot; the last frame is a
	// SnapshotFooter with the actual vertex / edge counts streamed.
	//
	// Bootstrap stitch contract: after receiving the SnapshotFooter the
	// peer MUST call `Subscribe(from_seq_per_origin = {origin: seq+1 for
	// each (origin, seq) in cutoff_seq_per_origin})` to pick up the live
	// tail. Without that the snapshot and the live stream cannot be glued
	// together without gap or overlap.
	//
	// No HTTP gateway annotation (parity with Subscribe).
	Snapshot(context.Context, *connect.Request[v1.SnapshotRequest], *connect.ServerStream[v1.SnapshotResponse]) error
	// PeerStatus returns the responder's per-origin (last_applied_seq,
	// last_applied_hlc) map. Used by anti-entropy (#186) as the
	// convergence safety net for the Subscribe pump: a periodic
	// PeerStatus poll lets each node detect that the peer's view of
	// some origin is ahead of its own and request the missing tail
	// (via Subscribe(from_seq = local+1)) or — when that returns
	// FailedPrecondition — fall back to Snapshot.
	//
	// The reply set always includes the responder's OWN origin (taken
	// from its mutation log's last appended seq + hlc) plus every
	// remote origin whose mutation has ever been applied via
	// ApplyMutation since process start. Origins the responder has
	// never seen are simply absent from the map.
	//
	// The RPC is intentionally unary and stateless — callers can
	// multiplex it across many peers without holding any server-side
	// resources. Returns Unavailable when the mutation log is unset
	// (single-instance test path).
	PeerStatus(context.Context, *connect.Request[v1.PeerStatusRequest]) (*connect.Response[v1.PeerStatusResponse], error)
}

// NewLanternReplicationServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLanternReplicationServiceHandler(svc LanternReplicationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lanternReplicationServiceMethods := v1.File_graph_v1_replication_proto.Services().ByName("LanternReplicationService").Methods()
	lanternReplicationServiceSubscribeHandler := connect.NewServerStreamHandler(
		LanternReplicationServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(lanternReplicationServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	lanternReplicationServiceSnapshotHandler := connect.NewServerStreamHandler(
		LanternReplicationServiceSnapshotProcedure,
		svc.Snapshot,
		connect.WithSchema(lanternReplicationServiceMethods.ByName("Snapshot")),
		connect.WithHandlerOptions(opts...),
	)
	lanternReplicationServicePeerStatusHandler := connect.NewUnaryHandler(
		LanternReplicationServicePeerStatusProcedure,
		svc.PeerStatus,
		connect.WithSchema(lanternReplicationServiceMethods.ByName("PeerStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graph.v1.LanternReplicationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LanternReplicationServiceSubscribeProcedure:
			lanternReplicationServiceSubscribeHandler.ServeHTTP(w, r)
		case LanternReplicationServiceSnapshotProcedure:
			lanternReplicationServiceSnapshotHandler.ServeHTTP(w, r)
		case LanternReplicationServicePeerStatusProcedure:
			lanternReplicationServicePeerStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLanternReplicationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLanternReplicationServiceHandler struct{}

func (UnimplementedLanternReplicationServiceHandler) Subscribe(context.Context, *connect.Request[v1.SubscribeRequest], *connect.ServerStream[v1.SubscribeResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternReplicationService.Subscribe is not implemented"))
}

func (UnimplementedLanternReplicationServiceHandler) Snapshot(context.Context, *connect.Request[v1.SnapshotRequest], *connect.ServerStream[v1.SnapshotResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternReplicationService.Snapshot is not implemented"))
}

func (UnimplementedLanternReplicationServiceHandler) PeerStatus(context.Context, *connect.Request[v1.PeerStatusRequest]) (*connect.Response[v1.PeerStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternReplicationService.PeerStatus is not implemented"))
}
