// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: graph/v1/security_peer.proto

package graphv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/anaregdesign/lantern/pb/graph/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LanternSecurityPeerServiceName is the fully-qualified name of the LanternSecurityPeerService
	// service.
	LanternSecurityPeerServiceName = "graph.v1.LanternSecurityPeerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LanternSecurityPeerServiceRenewPolicyLeaseProcedure is the fully-qualified name of the
	// LanternSecurityPeerService's RenewPolicyLease RPC.
	LanternSecurityPeerServiceRenewPolicyLeaseProcedure = "/graph.v1.LanternSecurityPeerService/RenewPolicyLease"
)

// LanternSecurityPeerServiceClient is a client for the graph.v1.LanternSecurityPeerService service.
type LanternSecurityPeerServiceClient interface {
	RenewPolicyLease(context.Context, *connect.Request[v1.RenewPolicyLeaseRequest]) (*connect.Response[v1.RenewPolicyLeaseResponse], error)
}

// NewLanternSecurityPeerServiceClient constructs a client for the
// graph.v1.LanternSecurityPeerService service. By default, it uses the Connect protocol with the
// binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use the
// gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLanternSecurityPeerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LanternSecurityPeerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lanternSecurityPeerServiceMethods := v1.File_graph_v1_security_peer_proto.Services().ByName("LanternSecurityPeerService").Methods()
	return &lanternSecurityPeerServiceClient{
		renewPolicyLease: connect.NewClient[v1.RenewPolicyLeaseRequest, v1.RenewPolicyLeaseResponse](
			httpClient,
			baseURL+LanternSecurityPeerServiceRenewPolicyLeaseProcedure,
			connect.WithSchema(lanternSecurityPeerServiceMethods.ByName("RenewPolicyLease")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lanternSecurityPeerServiceClient implements LanternSecurityPeerServiceClient.
type lanternSecurityPeerServiceClient struct {
	renewPolicyLease *connect.Client[v1.RenewPolicyLeaseRequest, v1.RenewPolicyLeaseResponse]
}

// RenewPolicyLease calls graph.v1.LanternSecurityPeerService.RenewPolicyLease.
func (c *lanternSecurityPeerServiceClient) RenewPolicyLease(ctx context.Context, req *connect.Request[v1.RenewPolicyLeaseRequest]) (*connect.Response[v1.RenewPolicyLeaseResponse], error) {
	return c.renewPolicyLease.CallUnary(ctx, req)
}

// LanternSecurityPeerServiceHandler is an implementation of the graph.v1.LanternSecurityPeerService
// service.
type LanternSecurityPeerServiceHandler interface {
	RenewPolicyLease(context.Context, *connect.Request[v1.RenewPolicyLeaseRequest]) (*connect.Response[v1.RenewPolicyLeaseResponse], error)
}

// NewLanternSecurityPeerServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLanternSecurityPeerServiceHandler(svc LanternSecurityPeerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lanternSecurityPeerServiceMethods := v1.File_graph_v1_security_peer_proto.Services().ByName("LanternSecurityPeerService").Methods()
	lanternSecurityPeerServiceRenewPolicyLeaseHandler := connect.NewUnaryHandler(
		LanternSecurityPeerServiceRenewPolicyLeaseProcedure,
		svc.RenewPolicyLease,
		connect.WithSchema(lanternSecurityPeerServiceMethods.ByName("RenewPolicyLease")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graph.v1.LanternSecurityPeerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LanternSecurityPeerServiceRenewPolicyLeaseProcedure:
			lanternSecurityPeerServiceRenewPolicyLeaseHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLanternSecurityPeerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLanternSecurityPeerServiceHandler struct{}

func (UnimplementedLanternSecurityPeerServiceHandler) RenewPolicyLease(context.Context, *connect.Request[v1.RenewPolicyLeaseRequest]) (*connect.Response[v1.RenewPolicyLeaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityPeerService.RenewPolicyLease is not implemented"))
}
