// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: graph/v1/security.proto

package graphv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/anaregdesign/lantern/pb/graph/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LanternSecurityServiceName is the fully-qualified name of the LanternSecurityService service.
	LanternSecurityServiceName = "graph.v1.LanternSecurityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LanternSecurityServiceGetAuthCapabilitiesProcedure is the fully-qualified name of the
	// LanternSecurityService's GetAuthCapabilities RPC.
	LanternSecurityServiceGetAuthCapabilitiesProcedure = "/graph.v1.LanternSecurityService/GetAuthCapabilities"
	// LanternSecurityServiceGetCurrentPrincipalProcedure is the fully-qualified name of the
	// LanternSecurityService's GetCurrentPrincipal RPC.
	LanternSecurityServiceGetCurrentPrincipalProcedure = "/graph.v1.LanternSecurityService/GetCurrentPrincipal"
	// LanternSecurityServiceListIssuersProcedure is the fully-qualified name of the
	// LanternSecurityService's ListIssuers RPC.
	LanternSecurityServiceListIssuersProcedure = "/graph.v1.LanternSecurityService/ListIssuers"
	// LanternSecurityServiceGetIssuerProcedure is the fully-qualified name of the
	// LanternSecurityService's GetIssuer RPC.
	LanternSecurityServiceGetIssuerProcedure = "/graph.v1.LanternSecurityService/GetIssuer"
	// LanternSecurityServiceListRolesProcedure is the fully-qualified name of the
	// LanternSecurityService's ListRoles RPC.
	LanternSecurityServiceListRolesProcedure = "/graph.v1.LanternSecurityService/ListRoles"
	// LanternSecurityServiceGetRoleProcedure is the fully-qualified name of the
	// LanternSecurityService's GetRole RPC.
	LanternSecurityServiceGetRoleProcedure = "/graph.v1.LanternSecurityService/GetRole"
	// LanternSecurityServiceListUsersProcedure is the fully-qualified name of the
	// LanternSecurityService's ListUsers RPC.
	LanternSecurityServiceListUsersProcedure = "/graph.v1.LanternSecurityService/ListUsers"
	// LanternSecurityServiceGetUserProcedure is the fully-qualified name of the
	// LanternSecurityService's GetUser RPC.
	LanternSecurityServiceGetUserProcedure = "/graph.v1.LanternSecurityService/GetUser"
	// LanternSecurityServiceListRoleAssignmentsProcedure is the fully-qualified name of the
	// LanternSecurityService's ListRoleAssignments RPC.
	LanternSecurityServiceListRoleAssignmentsProcedure = "/graph.v1.LanternSecurityService/ListRoleAssignments"
	// LanternSecurityServiceListSecurityAuditProcedure is the fully-qualified name of the
	// LanternSecurityService's ListSecurityAudit RPC.
	LanternSecurityServiceListSecurityAuditProcedure = "/graph.v1.LanternSecurityService/ListSecurityAudit"
	// LanternSecurityServiceGetRoleTemplatesProcedure is the fully-qualified name of the
	// LanternSecurityService's GetRoleTemplates RPC.
	LanternSecurityServiceGetRoleTemplatesProcedure = "/graph.v1.LanternSecurityService/GetRoleTemplates"
	// LanternSecurityServiceExplainAccessProcedure is the fully-qualified name of the
	// LanternSecurityService's ExplainAccess RPC.
	LanternSecurityServiceExplainAccessProcedure = "/graph.v1.LanternSecurityService/ExplainAccess"
	// LanternSecurityServiceValidateIssuerProcedure is the fully-qualified name of the
	// LanternSecurityService's ValidateIssuer RPC.
	LanternSecurityServiceValidateIssuerProcedure = "/graph.v1.LanternSecurityService/ValidateIssuer"
	// LanternSecurityServiceApplySecurityChangesProcedure is the fully-qualified name of the
	// LanternSecurityService's ApplySecurityChanges RPC.
	LanternSecurityServiceApplySecurityChangesProcedure = "/graph.v1.LanternSecurityService/ApplySecurityChanges"
	// LanternSecurityServiceApplySecurityChangeProcedure is the fully-qualified name of the
	// LanternSecurityService's ApplySecurityChange RPC.
	LanternSecurityServiceApplySecurityChangeProcedure = "/graph.v1.LanternSecurityService/ApplySecurityChange"
	// LanternSecurityServiceGetSecurityChangeStatusProcedure is the fully-qualified name of the
	// LanternSecurityService's GetSecurityChangeStatus RPC.
	LanternSecurityServiceGetSecurityChangeStatusProcedure = "/graph.v1.LanternSecurityService/GetSecurityChangeStatus"
)

// LanternSecurityServiceClient is a client for the graph.v1.LanternSecurityService service.
type LanternSecurityServiceClient interface {
	GetAuthCapabilities(context.Context, *connect.Request[v1.GetAuthCapabilitiesRequest]) (*connect.Response[v1.GetAuthCapabilitiesResponse], error)
	GetCurrentPrincipal(context.Context, *connect.Request[v1.GetCurrentPrincipalRequest]) (*connect.Response[v1.GetCurrentPrincipalResponse], error)
	ListIssuers(context.Context, *connect.Request[v1.ListIssuersRequest]) (*connect.Response[v1.ListIssuersResponse], error)
	GetIssuer(context.Context, *connect.Request[v1.GetIssuerRequest]) (*connect.Response[v1.GetIssuerResponse], error)
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
	GetRole(context.Context, *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error)
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
	ListRoleAssignments(context.Context, *connect.Request[v1.ListRoleAssignmentsRequest]) (*connect.Response[v1.ListRoleAssignmentsResponse], error)
	ListSecurityAudit(context.Context, *connect.Request[v1.ListSecurityAuditRequest]) (*connect.Response[v1.ListSecurityAuditResponse], error)
	GetRoleTemplates(context.Context, *connect.Request[v1.GetRoleTemplatesRequest]) (*connect.Response[v1.GetRoleTemplatesResponse], error)
	ExplainAccess(context.Context, *connect.Request[v1.ExplainAccessRequest]) (*connect.Response[v1.ExplainAccessResponse], error)
	ValidateIssuer(context.Context, *connect.Request[v1.ValidateIssuerRequest]) (*connect.Response[v1.ValidateIssuerResponse], error)
	// Plural is canonical and atomic, with request-index-aligned outcomes.
	ApplySecurityChanges(context.Context, *connect.Request[v1.ApplySecurityChangesRequest]) (*connect.Response[v1.ApplySecurityChangesResponse], error)
	ApplySecurityChange(context.Context, *connect.Request[v1.ApplySecurityChangeRequest]) (*connect.Response[v1.ApplySecurityChangeResponse], error)
	// Retained commit proof only; item outcomes and replay acknowledgement belong to Apply.
	GetSecurityChangeStatus(context.Context, *connect.Request[v1.GetSecurityChangeStatusRequest]) (*connect.Response[v1.GetSecurityChangeStatusResponse], error)
}

// NewLanternSecurityServiceClient constructs a client for the graph.v1.LanternSecurityService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLanternSecurityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LanternSecurityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lanternSecurityServiceMethods := v1.File_graph_v1_security_proto.Services().ByName("LanternSecurityService").Methods()
	return &lanternSecurityServiceClient{
		getAuthCapabilities: connect.NewClient[v1.GetAuthCapabilitiesRequest, v1.GetAuthCapabilitiesResponse](
			httpClient,
			baseURL+LanternSecurityServiceGetAuthCapabilitiesProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("GetAuthCapabilities")),
			connect.WithClientOptions(opts...),
		),
		getCurrentPrincipal: connect.NewClient[v1.GetCurrentPrincipalRequest, v1.GetCurrentPrincipalResponse](
			httpClient,
			baseURL+LanternSecurityServiceGetCurrentPrincipalProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("GetCurrentPrincipal")),
			connect.WithClientOptions(opts...),
		),
		listIssuers: connect.NewClient[v1.ListIssuersRequest, v1.ListIssuersResponse](
			httpClient,
			baseURL+LanternSecurityServiceListIssuersProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("ListIssuers")),
			connect.WithClientOptions(opts...),
		),
		getIssuer: connect.NewClient[v1.GetIssuerRequest, v1.GetIssuerResponse](
			httpClient,
			baseURL+LanternSecurityServiceGetIssuerProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("GetIssuer")),
			connect.WithClientOptions(opts...),
		),
		listRoles: connect.NewClient[v1.ListRolesRequest, v1.ListRolesResponse](
			httpClient,
			baseURL+LanternSecurityServiceListRolesProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("ListRoles")),
			connect.WithClientOptions(opts...),
		),
		getRole: connect.NewClient[v1.GetRoleRequest, v1.GetRoleResponse](
			httpClient,
			baseURL+LanternSecurityServiceGetRoleProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("GetRole")),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[v1.ListUsersRequest, v1.ListUsersResponse](
			httpClient,
			baseURL+LanternSecurityServiceListUsersProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		getUser: connect.NewClient[v1.GetUserRequest, v1.GetUserResponse](
			httpClient,
			baseURL+LanternSecurityServiceGetUserProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		listRoleAssignments: connect.NewClient[v1.ListRoleAssignmentsRequest, v1.ListRoleAssignmentsResponse](
			httpClient,
			baseURL+LanternSecurityServiceListRoleAssignmentsProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("ListRoleAssignments")),
			connect.WithClientOptions(opts...),
		),
		listSecurityAudit: connect.NewClient[v1.ListSecurityAuditRequest, v1.ListSecurityAuditResponse](
			httpClient,
			baseURL+LanternSecurityServiceListSecurityAuditProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("ListSecurityAudit")),
			connect.WithClientOptions(opts...),
		),
		getRoleTemplates: connect.NewClient[v1.GetRoleTemplatesRequest, v1.GetRoleTemplatesResponse](
			httpClient,
			baseURL+LanternSecurityServiceGetRoleTemplatesProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("GetRoleTemplates")),
			connect.WithClientOptions(opts...),
		),
		explainAccess: connect.NewClient[v1.ExplainAccessRequest, v1.ExplainAccessResponse](
			httpClient,
			baseURL+LanternSecurityServiceExplainAccessProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("ExplainAccess")),
			connect.WithClientOptions(opts...),
		),
		validateIssuer: connect.NewClient[v1.ValidateIssuerRequest, v1.ValidateIssuerResponse](
			httpClient,
			baseURL+LanternSecurityServiceValidateIssuerProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("ValidateIssuer")),
			connect.WithClientOptions(opts...),
		),
		applySecurityChanges: connect.NewClient[v1.ApplySecurityChangesRequest, v1.ApplySecurityChangesResponse](
			httpClient,
			baseURL+LanternSecurityServiceApplySecurityChangesProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("ApplySecurityChanges")),
			connect.WithClientOptions(opts...),
		),
		applySecurityChange: connect.NewClient[v1.ApplySecurityChangeRequest, v1.ApplySecurityChangeResponse](
			httpClient,
			baseURL+LanternSecurityServiceApplySecurityChangeProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("ApplySecurityChange")),
			connect.WithClientOptions(opts...),
		),
		getSecurityChangeStatus: connect.NewClient[v1.GetSecurityChangeStatusRequest, v1.GetSecurityChangeStatusResponse](
			httpClient,
			baseURL+LanternSecurityServiceGetSecurityChangeStatusProcedure,
			connect.WithSchema(lanternSecurityServiceMethods.ByName("GetSecurityChangeStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lanternSecurityServiceClient implements LanternSecurityServiceClient.
type lanternSecurityServiceClient struct {
	getAuthCapabilities     *connect.Client[v1.GetAuthCapabilitiesRequest, v1.GetAuthCapabilitiesResponse]
	getCurrentPrincipal     *connect.Client[v1.GetCurrentPrincipalRequest, v1.GetCurrentPrincipalResponse]
	listIssuers             *connect.Client[v1.ListIssuersRequest, v1.ListIssuersResponse]
	getIssuer               *connect.Client[v1.GetIssuerRequest, v1.GetIssuerResponse]
	listRoles               *connect.Client[v1.ListRolesRequest, v1.ListRolesResponse]
	getRole                 *connect.Client[v1.GetRoleRequest, v1.GetRoleResponse]
	listUsers               *connect.Client[v1.ListUsersRequest, v1.ListUsersResponse]
	getUser                 *connect.Client[v1.GetUserRequest, v1.GetUserResponse]
	listRoleAssignments     *connect.Client[v1.ListRoleAssignmentsRequest, v1.ListRoleAssignmentsResponse]
	listSecurityAudit       *connect.Client[v1.ListSecurityAuditRequest, v1.ListSecurityAuditResponse]
	getRoleTemplates        *connect.Client[v1.GetRoleTemplatesRequest, v1.GetRoleTemplatesResponse]
	explainAccess           *connect.Client[v1.ExplainAccessRequest, v1.ExplainAccessResponse]
	validateIssuer          *connect.Client[v1.ValidateIssuerRequest, v1.ValidateIssuerResponse]
	applySecurityChanges    *connect.Client[v1.ApplySecurityChangesRequest, v1.ApplySecurityChangesResponse]
	applySecurityChange     *connect.Client[v1.ApplySecurityChangeRequest, v1.ApplySecurityChangeResponse]
	getSecurityChangeStatus *connect.Client[v1.GetSecurityChangeStatusRequest, v1.GetSecurityChangeStatusResponse]
}

// GetAuthCapabilities calls graph.v1.LanternSecurityService.GetAuthCapabilities.
func (c *lanternSecurityServiceClient) GetAuthCapabilities(ctx context.Context, req *connect.Request[v1.GetAuthCapabilitiesRequest]) (*connect.Response[v1.GetAuthCapabilitiesResponse], error) {
	return c.getAuthCapabilities.CallUnary(ctx, req)
}

// GetCurrentPrincipal calls graph.v1.LanternSecurityService.GetCurrentPrincipal.
func (c *lanternSecurityServiceClient) GetCurrentPrincipal(ctx context.Context, req *connect.Request[v1.GetCurrentPrincipalRequest]) (*connect.Response[v1.GetCurrentPrincipalResponse], error) {
	return c.getCurrentPrincipal.CallUnary(ctx, req)
}

// ListIssuers calls graph.v1.LanternSecurityService.ListIssuers.
func (c *lanternSecurityServiceClient) ListIssuers(ctx context.Context, req *connect.Request[v1.ListIssuersRequest]) (*connect.Response[v1.ListIssuersResponse], error) {
	return c.listIssuers.CallUnary(ctx, req)
}

// GetIssuer calls graph.v1.LanternSecurityService.GetIssuer.
func (c *lanternSecurityServiceClient) GetIssuer(ctx context.Context, req *connect.Request[v1.GetIssuerRequest]) (*connect.Response[v1.GetIssuerResponse], error) {
	return c.getIssuer.CallUnary(ctx, req)
}

// ListRoles calls graph.v1.LanternSecurityService.ListRoles.
func (c *lanternSecurityServiceClient) ListRoles(ctx context.Context, req *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return c.listRoles.CallUnary(ctx, req)
}

// GetRole calls graph.v1.LanternSecurityService.GetRole.
func (c *lanternSecurityServiceClient) GetRole(ctx context.Context, req *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error) {
	return c.getRole.CallUnary(ctx, req)
}

// ListUsers calls graph.v1.LanternSecurityService.ListUsers.
func (c *lanternSecurityServiceClient) ListUsers(ctx context.Context, req *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// GetUser calls graph.v1.LanternSecurityService.GetUser.
func (c *lanternSecurityServiceClient) GetUser(ctx context.Context, req *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// ListRoleAssignments calls graph.v1.LanternSecurityService.ListRoleAssignments.
func (c *lanternSecurityServiceClient) ListRoleAssignments(ctx context.Context, req *connect.Request[v1.ListRoleAssignmentsRequest]) (*connect.Response[v1.ListRoleAssignmentsResponse], error) {
	return c.listRoleAssignments.CallUnary(ctx, req)
}

// ListSecurityAudit calls graph.v1.LanternSecurityService.ListSecurityAudit.
func (c *lanternSecurityServiceClient) ListSecurityAudit(ctx context.Context, req *connect.Request[v1.ListSecurityAuditRequest]) (*connect.Response[v1.ListSecurityAuditResponse], error) {
	return c.listSecurityAudit.CallUnary(ctx, req)
}

// GetRoleTemplates calls graph.v1.LanternSecurityService.GetRoleTemplates.
func (c *lanternSecurityServiceClient) GetRoleTemplates(ctx context.Context, req *connect.Request[v1.GetRoleTemplatesRequest]) (*connect.Response[v1.GetRoleTemplatesResponse], error) {
	return c.getRoleTemplates.CallUnary(ctx, req)
}

// ExplainAccess calls graph.v1.LanternSecurityService.ExplainAccess.
func (c *lanternSecurityServiceClient) ExplainAccess(ctx context.Context, req *connect.Request[v1.ExplainAccessRequest]) (*connect.Response[v1.ExplainAccessResponse], error) {
	return c.explainAccess.CallUnary(ctx, req)
}

// ValidateIssuer calls graph.v1.LanternSecurityService.ValidateIssuer.
func (c *lanternSecurityServiceClient) ValidateIssuer(ctx context.Context, req *connect.Request[v1.ValidateIssuerRequest]) (*connect.Response[v1.ValidateIssuerResponse], error) {
	return c.validateIssuer.CallUnary(ctx, req)
}

// ApplySecurityChanges calls graph.v1.LanternSecurityService.ApplySecurityChanges.
func (c *lanternSecurityServiceClient) ApplySecurityChanges(ctx context.Context, req *connect.Request[v1.ApplySecurityChangesRequest]) (*connect.Response[v1.ApplySecurityChangesResponse], error) {
	return c.applySecurityChanges.CallUnary(ctx, req)
}

// ApplySecurityChange calls graph.v1.LanternSecurityService.ApplySecurityChange.
func (c *lanternSecurityServiceClient) ApplySecurityChange(ctx context.Context, req *connect.Request[v1.ApplySecurityChangeRequest]) (*connect.Response[v1.ApplySecurityChangeResponse], error) {
	return c.applySecurityChange.CallUnary(ctx, req)
}

// GetSecurityChangeStatus calls graph.v1.LanternSecurityService.GetSecurityChangeStatus.
func (c *lanternSecurityServiceClient) GetSecurityChangeStatus(ctx context.Context, req *connect.Request[v1.GetSecurityChangeStatusRequest]) (*connect.Response[v1.GetSecurityChangeStatusResponse], error) {
	return c.getSecurityChangeStatus.CallUnary(ctx, req)
}

// LanternSecurityServiceHandler is an implementation of the graph.v1.LanternSecurityService
// service.
type LanternSecurityServiceHandler interface {
	GetAuthCapabilities(context.Context, *connect.Request[v1.GetAuthCapabilitiesRequest]) (*connect.Response[v1.GetAuthCapabilitiesResponse], error)
	GetCurrentPrincipal(context.Context, *connect.Request[v1.GetCurrentPrincipalRequest]) (*connect.Response[v1.GetCurrentPrincipalResponse], error)
	ListIssuers(context.Context, *connect.Request[v1.ListIssuersRequest]) (*connect.Response[v1.ListIssuersResponse], error)
	GetIssuer(context.Context, *connect.Request[v1.GetIssuerRequest]) (*connect.Response[v1.GetIssuerResponse], error)
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
	GetRole(context.Context, *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error)
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
	ListRoleAssignments(context.Context, *connect.Request[v1.ListRoleAssignmentsRequest]) (*connect.Response[v1.ListRoleAssignmentsResponse], error)
	ListSecurityAudit(context.Context, *connect.Request[v1.ListSecurityAuditRequest]) (*connect.Response[v1.ListSecurityAuditResponse], error)
	GetRoleTemplates(context.Context, *connect.Request[v1.GetRoleTemplatesRequest]) (*connect.Response[v1.GetRoleTemplatesResponse], error)
	ExplainAccess(context.Context, *connect.Request[v1.ExplainAccessRequest]) (*connect.Response[v1.ExplainAccessResponse], error)
	ValidateIssuer(context.Context, *connect.Request[v1.ValidateIssuerRequest]) (*connect.Response[v1.ValidateIssuerResponse], error)
	// Plural is canonical and atomic, with request-index-aligned outcomes.
	ApplySecurityChanges(context.Context, *connect.Request[v1.ApplySecurityChangesRequest]) (*connect.Response[v1.ApplySecurityChangesResponse], error)
	ApplySecurityChange(context.Context, *connect.Request[v1.ApplySecurityChangeRequest]) (*connect.Response[v1.ApplySecurityChangeResponse], error)
	// Retained commit proof only; item outcomes and replay acknowledgement belong to Apply.
	GetSecurityChangeStatus(context.Context, *connect.Request[v1.GetSecurityChangeStatusRequest]) (*connect.Response[v1.GetSecurityChangeStatusResponse], error)
}

// NewLanternSecurityServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLanternSecurityServiceHandler(svc LanternSecurityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lanternSecurityServiceMethods := v1.File_graph_v1_security_proto.Services().ByName("LanternSecurityService").Methods()
	lanternSecurityServiceGetAuthCapabilitiesHandler := connect.NewUnaryHandler(
		LanternSecurityServiceGetAuthCapabilitiesProcedure,
		svc.GetAuthCapabilities,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("GetAuthCapabilities")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceGetCurrentPrincipalHandler := connect.NewUnaryHandler(
		LanternSecurityServiceGetCurrentPrincipalProcedure,
		svc.GetCurrentPrincipal,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("GetCurrentPrincipal")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceListIssuersHandler := connect.NewUnaryHandler(
		LanternSecurityServiceListIssuersProcedure,
		svc.ListIssuers,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("ListIssuers")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceGetIssuerHandler := connect.NewUnaryHandler(
		LanternSecurityServiceGetIssuerProcedure,
		svc.GetIssuer,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("GetIssuer")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceListRolesHandler := connect.NewUnaryHandler(
		LanternSecurityServiceListRolesProcedure,
		svc.ListRoles,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("ListRoles")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceGetRoleHandler := connect.NewUnaryHandler(
		LanternSecurityServiceGetRoleProcedure,
		svc.GetRole,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("GetRole")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceListUsersHandler := connect.NewUnaryHandler(
		LanternSecurityServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceGetUserHandler := connect.NewUnaryHandler(
		LanternSecurityServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceListRoleAssignmentsHandler := connect.NewUnaryHandler(
		LanternSecurityServiceListRoleAssignmentsProcedure,
		svc.ListRoleAssignments,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("ListRoleAssignments")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceListSecurityAuditHandler := connect.NewUnaryHandler(
		LanternSecurityServiceListSecurityAuditProcedure,
		svc.ListSecurityAudit,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("ListSecurityAudit")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceGetRoleTemplatesHandler := connect.NewUnaryHandler(
		LanternSecurityServiceGetRoleTemplatesProcedure,
		svc.GetRoleTemplates,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("GetRoleTemplates")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceExplainAccessHandler := connect.NewUnaryHandler(
		LanternSecurityServiceExplainAccessProcedure,
		svc.ExplainAccess,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("ExplainAccess")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceValidateIssuerHandler := connect.NewUnaryHandler(
		LanternSecurityServiceValidateIssuerProcedure,
		svc.ValidateIssuer,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("ValidateIssuer")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceApplySecurityChangesHandler := connect.NewUnaryHandler(
		LanternSecurityServiceApplySecurityChangesProcedure,
		svc.ApplySecurityChanges,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("ApplySecurityChanges")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceApplySecurityChangeHandler := connect.NewUnaryHandler(
		LanternSecurityServiceApplySecurityChangeProcedure,
		svc.ApplySecurityChange,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("ApplySecurityChange")),
		connect.WithHandlerOptions(opts...),
	)
	lanternSecurityServiceGetSecurityChangeStatusHandler := connect.NewUnaryHandler(
		LanternSecurityServiceGetSecurityChangeStatusProcedure,
		svc.GetSecurityChangeStatus,
		connect.WithSchema(lanternSecurityServiceMethods.ByName("GetSecurityChangeStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graph.v1.LanternSecurityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LanternSecurityServiceGetAuthCapabilitiesProcedure:
			lanternSecurityServiceGetAuthCapabilitiesHandler.ServeHTTP(w, r)
		case LanternSecurityServiceGetCurrentPrincipalProcedure:
			lanternSecurityServiceGetCurrentPrincipalHandler.ServeHTTP(w, r)
		case LanternSecurityServiceListIssuersProcedure:
			lanternSecurityServiceListIssuersHandler.ServeHTTP(w, r)
		case LanternSecurityServiceGetIssuerProcedure:
			lanternSecurityServiceGetIssuerHandler.ServeHTTP(w, r)
		case LanternSecurityServiceListRolesProcedure:
			lanternSecurityServiceListRolesHandler.ServeHTTP(w, r)
		case LanternSecurityServiceGetRoleProcedure:
			lanternSecurityServiceGetRoleHandler.ServeHTTP(w, r)
		case LanternSecurityServiceListUsersProcedure:
			lanternSecurityServiceListUsersHandler.ServeHTTP(w, r)
		case LanternSecurityServiceGetUserProcedure:
			lanternSecurityServiceGetUserHandler.ServeHTTP(w, r)
		case LanternSecurityServiceListRoleAssignmentsProcedure:
			lanternSecurityServiceListRoleAssignmentsHandler.ServeHTTP(w, r)
		case LanternSecurityServiceListSecurityAuditProcedure:
			lanternSecurityServiceListSecurityAuditHandler.ServeHTTP(w, r)
		case LanternSecurityServiceGetRoleTemplatesProcedure:
			lanternSecurityServiceGetRoleTemplatesHandler.ServeHTTP(w, r)
		case LanternSecurityServiceExplainAccessProcedure:
			lanternSecurityServiceExplainAccessHandler.ServeHTTP(w, r)
		case LanternSecurityServiceValidateIssuerProcedure:
			lanternSecurityServiceValidateIssuerHandler.ServeHTTP(w, r)
		case LanternSecurityServiceApplySecurityChangesProcedure:
			lanternSecurityServiceApplySecurityChangesHandler.ServeHTTP(w, r)
		case LanternSecurityServiceApplySecurityChangeProcedure:
			lanternSecurityServiceApplySecurityChangeHandler.ServeHTTP(w, r)
		case LanternSecurityServiceGetSecurityChangeStatusProcedure:
			lanternSecurityServiceGetSecurityChangeStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLanternSecurityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLanternSecurityServiceHandler struct{}

func (UnimplementedLanternSecurityServiceHandler) GetAuthCapabilities(context.Context, *connect.Request[v1.GetAuthCapabilitiesRequest]) (*connect.Response[v1.GetAuthCapabilitiesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.GetAuthCapabilities is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) GetCurrentPrincipal(context.Context, *connect.Request[v1.GetCurrentPrincipalRequest]) (*connect.Response[v1.GetCurrentPrincipalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.GetCurrentPrincipal is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) ListIssuers(context.Context, *connect.Request[v1.ListIssuersRequest]) (*connect.Response[v1.ListIssuersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.ListIssuers is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) GetIssuer(context.Context, *connect.Request[v1.GetIssuerRequest]) (*connect.Response[v1.GetIssuerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.GetIssuer is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.ListRoles is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) GetRole(context.Context, *connect.Request[v1.GetRoleRequest]) (*connect.Response[v1.GetRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.GetRole is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.ListUsers is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.GetUser is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) ListRoleAssignments(context.Context, *connect.Request[v1.ListRoleAssignmentsRequest]) (*connect.Response[v1.ListRoleAssignmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.ListRoleAssignments is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) ListSecurityAudit(context.Context, *connect.Request[v1.ListSecurityAuditRequest]) (*connect.Response[v1.ListSecurityAuditResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.ListSecurityAudit is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) GetRoleTemplates(context.Context, *connect.Request[v1.GetRoleTemplatesRequest]) (*connect.Response[v1.GetRoleTemplatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.GetRoleTemplates is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) ExplainAccess(context.Context, *connect.Request[v1.ExplainAccessRequest]) (*connect.Response[v1.ExplainAccessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.ExplainAccess is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) ValidateIssuer(context.Context, *connect.Request[v1.ValidateIssuerRequest]) (*connect.Response[v1.ValidateIssuerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.ValidateIssuer is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) ApplySecurityChanges(context.Context, *connect.Request[v1.ApplySecurityChangesRequest]) (*connect.Response[v1.ApplySecurityChangesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.ApplySecurityChanges is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) ApplySecurityChange(context.Context, *connect.Request[v1.ApplySecurityChangeRequest]) (*connect.Response[v1.ApplySecurityChangeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.ApplySecurityChange is not implemented"))
}

func (UnimplementedLanternSecurityServiceHandler) GetSecurityChangeStatus(context.Context, *connect.Request[v1.GetSecurityChangeStatusRequest]) (*connect.Response[v1.GetSecurityChangeStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graph.v1.LanternSecurityService.GetSecurityChangeStatus is not implemented"))
}
