# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lantern_client._pb.graph.v1 import graph_pb2 as graph_dot_v1_dot_graph__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in graph/v1/graph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LanternServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Illuminate = channel.unary_unary(
                '/graph.v1.LanternService/Illuminate',
                request_serializer=graph_dot_v1_dot_graph__pb2.IlluminateRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.IlluminateResponse.FromString,
                _registered_method=True)
        self.GetVertex = channel.unary_unary(
                '/graph.v1.LanternService/GetVertex',
                request_serializer=graph_dot_v1_dot_graph__pb2.GetVertexRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.GetVertexResponse.FromString,
                _registered_method=True)
        self.GetVertices = channel.unary_unary(
                '/graph.v1.LanternService/GetVertices',
                request_serializer=graph_dot_v1_dot_graph__pb2.GetVerticesRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.GetVerticesResponse.FromString,
                _registered_method=True)
        self.PutVertex = channel.unary_unary(
                '/graph.v1.LanternService/PutVertex',
                request_serializer=graph_dot_v1_dot_graph__pb2.PutVertexRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.PutVertexResponse.FromString,
                _registered_method=True)
        self.PutVertices = channel.unary_unary(
                '/graph.v1.LanternService/PutVertices',
                request_serializer=graph_dot_v1_dot_graph__pb2.PutVerticesRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.PutVerticesResponse.FromString,
                _registered_method=True)
        self.DeleteVertex = channel.unary_unary(
                '/graph.v1.LanternService/DeleteVertex',
                request_serializer=graph_dot_v1_dot_graph__pb2.DeleteVertexRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.DeleteVertexResponse.FromString,
                _registered_method=True)
        self.DeleteVertices = channel.unary_unary(
                '/graph.v1.LanternService/DeleteVertices',
                request_serializer=graph_dot_v1_dot_graph__pb2.DeleteVerticesRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.DeleteVerticesResponse.FromString,
                _registered_method=True)
        self.ScanVertices = channel.unary_unary(
                '/graph.v1.LanternService/ScanVertices',
                request_serializer=graph_dot_v1_dot_graph__pb2.ScanVerticesRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.ScanVerticesResponse.FromString,
                _registered_method=True)
        self.CountVerticesByPrefix = channel.unary_unary(
                '/graph.v1.LanternService/CountVerticesByPrefix',
                request_serializer=graph_dot_v1_dot_graph__pb2.CountVerticesByPrefixRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.CountVerticesByPrefixResponse.FromString,
                _registered_method=True)
        self.DeleteVerticesByPrefix = channel.unary_unary(
                '/graph.v1.LanternService/DeleteVerticesByPrefix',
                request_serializer=graph_dot_v1_dot_graph__pb2.DeleteVerticesByPrefixRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.DeleteVerticesByPrefixResponse.FromString,
                _registered_method=True)
        self.GetEdge = channel.unary_unary(
                '/graph.v1.LanternService/GetEdge',
                request_serializer=graph_dot_v1_dot_graph__pb2.GetEdgeRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.GetEdgeResponse.FromString,
                _registered_method=True)
        self.GetEdges = channel.unary_unary(
                '/graph.v1.LanternService/GetEdges',
                request_serializer=graph_dot_v1_dot_graph__pb2.GetEdgesRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.GetEdgesResponse.FromString,
                _registered_method=True)
        self.AddEdge = channel.unary_unary(
                '/graph.v1.LanternService/AddEdge',
                request_serializer=graph_dot_v1_dot_graph__pb2.AddEdgeRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.AddEdgeResponse.FromString,
                _registered_method=True)
        self.AddEdges = channel.unary_unary(
                '/graph.v1.LanternService/AddEdges',
                request_serializer=graph_dot_v1_dot_graph__pb2.AddEdgesRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.AddEdgesResponse.FromString,
                _registered_method=True)
        self.PutEdge = channel.unary_unary(
                '/graph.v1.LanternService/PutEdge',
                request_serializer=graph_dot_v1_dot_graph__pb2.PutEdgeRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.PutEdgeResponse.FromString,
                _registered_method=True)
        self.PutEdges = channel.unary_unary(
                '/graph.v1.LanternService/PutEdges',
                request_serializer=graph_dot_v1_dot_graph__pb2.PutEdgesRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.PutEdgesResponse.FromString,
                _registered_method=True)
        self.DeleteEdge = channel.unary_unary(
                '/graph.v1.LanternService/DeleteEdge',
                request_serializer=graph_dot_v1_dot_graph__pb2.DeleteEdgeRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.DeleteEdgeResponse.FromString,
                _registered_method=True)
        self.DeleteEdges = channel.unary_unary(
                '/graph.v1.LanternService/DeleteEdges',
                request_serializer=graph_dot_v1_dot_graph__pb2.DeleteEdgesRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.DeleteEdgesResponse.FromString,
                _registered_method=True)
        self.ScanEdges = channel.unary_unary(
                '/graph.v1.LanternService/ScanEdges',
                request_serializer=graph_dot_v1_dot_graph__pb2.ScanEdgesRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_graph__pb2.ScanEdgesResponse.FromString,
                _registered_method=True)


class LanternServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Illuminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVertex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVertices(self, request, context):
        """GetVertices reads several vertices in one round trip.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutVertex(self, request, context):
        """PutVertex writes a single vertex. Thin facade over PutVertices.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutVertices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVertex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVertices(self, request, context):
        """DeleteVertices removes several vertices in one round trip.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanVertices(self, request, context):
        """ScanVertices streams vertices whose key starts with the given prefix in
        ascending order, page by page. Plural-only — prefix scan is inherently
        plural.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountVerticesByPrefix(self, request, context):
        """CountVerticesByPrefix returns the number of live vertices whose key
        starts with the given prefix.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVerticesByPrefix(self, request, context):
        """DeleteVerticesByPrefix deletes up to `limit` vertices whose key starts
        with the given prefix. Pass `dry_run = true` to preview the count
        without mutating state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEdges(self, request, context):
        """GetEdges reads several edges in one round trip.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddEdge(self, request, context):
        """AddEdge is non-idempotent (accumulates weight). Thin facade over AddEdges.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddEdges(self, request, context):
        """AddEdges is non-idempotent (accumulates weight). POST per REST conventions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutEdge(self, request, context):
        """PutEdge is idempotent (replaces weight). Thin facade over PutEdges.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutEdges(self, request, context):
        """PutEdges is idempotent (replaces weight). PUT per REST conventions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEdges(self, request, context):
        """DeleteEdges removes several edges in one round trip.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanEdges(self, request, context):
        """ScanEdges streams edges whose tail key starts with `tail_prefix` AND
        whose head key starts with `head_prefix`, in ascending (tail, head)
        order, page by page. Plural-only — prefix scan is inherently plural.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanternServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Illuminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Illuminate,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.IlluminateRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.IlluminateResponse.SerializeToString,
            ),
            'GetVertex': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVertex,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.GetVertexRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.GetVertexResponse.SerializeToString,
            ),
            'GetVertices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVertices,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.GetVerticesRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.GetVerticesResponse.SerializeToString,
            ),
            'PutVertex': grpc.unary_unary_rpc_method_handler(
                    servicer.PutVertex,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.PutVertexRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.PutVertexResponse.SerializeToString,
            ),
            'PutVertices': grpc.unary_unary_rpc_method_handler(
                    servicer.PutVertices,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.PutVerticesRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.PutVerticesResponse.SerializeToString,
            ),
            'DeleteVertex': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVertex,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.DeleteVertexRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.DeleteVertexResponse.SerializeToString,
            ),
            'DeleteVertices': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVertices,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.DeleteVerticesRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.DeleteVerticesResponse.SerializeToString,
            ),
            'ScanVertices': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanVertices,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.ScanVerticesRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.ScanVerticesResponse.SerializeToString,
            ),
            'CountVerticesByPrefix': grpc.unary_unary_rpc_method_handler(
                    servicer.CountVerticesByPrefix,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.CountVerticesByPrefixRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.CountVerticesByPrefixResponse.SerializeToString,
            ),
            'DeleteVerticesByPrefix': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVerticesByPrefix,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.DeleteVerticesByPrefixRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.DeleteVerticesByPrefixResponse.SerializeToString,
            ),
            'GetEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEdge,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.GetEdgeRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.GetEdgeResponse.SerializeToString,
            ),
            'GetEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEdges,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.GetEdgesRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.GetEdgesResponse.SerializeToString,
            ),
            'AddEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEdge,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.AddEdgeRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.AddEdgeResponse.SerializeToString,
            ),
            'AddEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEdges,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.AddEdgesRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.AddEdgesResponse.SerializeToString,
            ),
            'PutEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.PutEdge,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.PutEdgeRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.PutEdgeResponse.SerializeToString,
            ),
            'PutEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.PutEdges,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.PutEdgesRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.PutEdgesResponse.SerializeToString,
            ),
            'DeleteEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEdge,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.DeleteEdgeRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.DeleteEdgeResponse.SerializeToString,
            ),
            'DeleteEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEdges,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.DeleteEdgesRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.DeleteEdgesResponse.SerializeToString,
            ),
            'ScanEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanEdges,
                    request_deserializer=graph_dot_v1_dot_graph__pb2.ScanEdgesRequest.FromString,
                    response_serializer=graph_dot_v1_dot_graph__pb2.ScanEdgesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'graph.v1.LanternService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('graph.v1.LanternService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LanternService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Illuminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/Illuminate',
            graph_dot_v1_dot_graph__pb2.IlluminateRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.IlluminateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVertex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/GetVertex',
            graph_dot_v1_dot_graph__pb2.GetVertexRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.GetVertexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVertices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/GetVertices',
            graph_dot_v1_dot_graph__pb2.GetVerticesRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.GetVerticesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutVertex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/PutVertex',
            graph_dot_v1_dot_graph__pb2.PutVertexRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.PutVertexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutVertices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/PutVertices',
            graph_dot_v1_dot_graph__pb2.PutVerticesRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.PutVerticesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVertex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/DeleteVertex',
            graph_dot_v1_dot_graph__pb2.DeleteVertexRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.DeleteVertexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVertices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/DeleteVertices',
            graph_dot_v1_dot_graph__pb2.DeleteVerticesRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.DeleteVerticesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanVertices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/ScanVertices',
            graph_dot_v1_dot_graph__pb2.ScanVerticesRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.ScanVerticesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountVerticesByPrefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/CountVerticesByPrefix',
            graph_dot_v1_dot_graph__pb2.CountVerticesByPrefixRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.CountVerticesByPrefixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVerticesByPrefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/DeleteVerticesByPrefix',
            graph_dot_v1_dot_graph__pb2.DeleteVerticesByPrefixRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.DeleteVerticesByPrefixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/GetEdge',
            graph_dot_v1_dot_graph__pb2.GetEdgeRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.GetEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/GetEdges',
            graph_dot_v1_dot_graph__pb2.GetEdgesRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.GetEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/AddEdge',
            graph_dot_v1_dot_graph__pb2.AddEdgeRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.AddEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/AddEdges',
            graph_dot_v1_dot_graph__pb2.AddEdgesRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.AddEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/PutEdge',
            graph_dot_v1_dot_graph__pb2.PutEdgeRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.PutEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/PutEdges',
            graph_dot_v1_dot_graph__pb2.PutEdgesRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.PutEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/DeleteEdge',
            graph_dot_v1_dot_graph__pb2.DeleteEdgeRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.DeleteEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/DeleteEdges',
            graph_dot_v1_dot_graph__pb2.DeleteEdgesRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.DeleteEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternService/ScanEdges',
            graph_dot_v1_dot_graph__pb2.ScanEdgesRequest.SerializeToString,
            graph_dot_v1_dot_graph__pb2.ScanEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
