package security

import (
	"bytes"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/binary"
	"errors"
	"time"
)

const leasePrefix = "LNLEASE1\x00"
const leasePayloadBytes = len(leasePrefix) + 16 + 32 + 16 + 16 + 16 + 32 + 8 + 32 + 8 + 8
const maxLeaseLifetime = 30 * time.Second
const maxLeaseClockMargin = 5 * time.Second

var ErrInvalidLease = errors.New("invalid security serving lease")

// LeaseRequest binds one outstanding renewal to one receiver process. These
// bytes are generated by the receiver, never restored from a file or reused.
type LeaseRequest struct {
	Receiver  [16]byte
	BootNonce [16]byte
	Challenge [32]byte
}

type authorityLease struct {
	generation  [16]byte
	writer      [32]byte
	incarnation [16]byte
	request     LeaseRequest
	revision    uint64
	digest      [32]byte
	issuedAt    time.Time
	lifetime    time.Duration
}

func (l authorityLease) encode(key ed25519.PrivateKey) []byte {
	out := make([]byte, 0, leasePayloadBytes+ed25519.SignatureSize)
	out = append(out, leasePrefix...)
	out = append(out, l.generation[:]...)
	out = append(out, l.writer[:]...)
	out = append(out, l.incarnation[:]...)
	out = append(out, l.request.Receiver[:]...)
	out = append(out, l.request.BootNonce[:]...)
	out = append(out, l.request.Challenge[:]...)
	out = binary.BigEndian.AppendUint64(out, l.revision)
	out = append(out, l.digest[:]...)
	out = binary.BigEndian.AppendUint64(out, uint64(l.issuedAt.UnixNano()))
	out = binary.BigEndian.AppendUint64(out, uint64(l.lifetime))
	return append(out, ed25519.Sign(key, out)...)
}
func decodeAuthorityLease(encoded []byte, key ed25519.PublicKey) (authorityLease, error) {
	var l authorityLease
	if len(key) != ed25519.PublicKeySize || len(encoded) != leasePayloadBytes+ed25519.SignatureSize || !bytes.HasPrefix(encoded, []byte(leasePrefix)) || !ed25519.Verify(key, encoded[:leasePayloadBytes], encoded[leasePayloadBytes:]) {
		return l, ErrInvalidLease
	}
	i := len(leasePrefix)
	copy(l.generation[:], encoded[i:i+16])
	i += 16
	copy(l.writer[:], encoded[i:i+32])
	i += 32
	copy(l.incarnation[:], encoded[i:i+16])
	i += 16
	copy(l.request.Receiver[:], encoded[i:i+16])
	i += 16
	copy(l.request.BootNonce[:], encoded[i:i+16])
	i += 16
	copy(l.request.Challenge[:], encoded[i:i+32])
	i += 32
	l.revision = binary.BigEndian.Uint64(encoded[i : i+8])
	i += 8
	copy(l.digest[:], encoded[i:i+32])
	i += 32
	l.issuedAt = time.Unix(0, int64(binary.BigEndian.Uint64(encoded[i:i+8])))
	i += 8
	l.lifetime = time.Duration(binary.BigEndian.Uint64(encoded[i : i+8]))
	if l.generation == [16]byte{} || l.writer != sha256.Sum256(key) || l.incarnation == [16]byte{} || !l.request.valid() || l.revision == 0 || l.digest == [32]byte{} || l.lifetime <= 0 || l.lifetime > maxLeaseLifetime {
		return authorityLease{}, ErrInvalidLease
	}
	return l, nil
}
func (r LeaseRequest) valid() bool {
	return r.Receiver != [16]byte{} && r.BootNonce != [16]byte{} && r.Challenge != [32]byte{}
}
