package security

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"time"
)

// SessionRequest is writer-internal evidence after Code/PKCE/nonce verification.
// Session digests are generated by the Server. Issuer revision fences a login
// callback racing with disable/reconfiguration; no unknown subject is enrolled.
type SessionRequest struct {
	ChangeID             [16]byte
	Identity             Identity
	IssuerConfigRevision uint64
	Digest               string
	CSRFDigest           string
	ReplacesDigest       string
	AuthTime             time.Time
	RequireRecentAuth    bool
	Now                  time.Time
	Lifetime             time.Duration
}

func (s *Store) IssueSession(ctx context.Context, request SessionRequest) (ChangeResult, error) {
	if s == nil || s.faulted.Load() {
		return ChangeResult{}, ErrStoreUnavailable
	}
	if len(s.privateKey) == 0 {
		return ChangeResult{}, ErrReadOnlyWriter
	}
	if request.ChangeID == [16]byte{} || request.Identity.Kind != OIDCPrincipal || !request.Identity.valid() ||
		request.IssuerConfigRevision == 0 || !validHexDigest(request.Digest) || !validHexDigest(request.CSRFDigest) ||
		(request.ReplacesDigest != "" && (!validHexDigest(request.ReplacesDigest) || request.ReplacesDigest == request.Digest)) ||
		request.Now.IsZero() || request.AuthTime.After(request.Now) || request.Lifetime <= 0 || request.Lifetime > MaxSessionLifetime {
		return ChangeResult{}, ErrInvalidImage
	}
	// Ordinary login and rotation preserve unknown/old signed evidence. Only
	// Server-owned step-up intent requires freshness at the application cut.
	if request.RequireRecentAuth && (request.AuthTime.IsZero() || request.Now.Sub(request.AuthTime) > RecentAuthenticationLifetime) {
		return ChangeResult{}, ErrRecentAuthentication
	}
	// Keep request identity stable across a retry; the initial issuance time is
	// part of that session's fixed lifetime and must not slide on retry.
	encoded, err := json.Marshal(request)
	if err != nil {
		return ChangeResult{}, ErrInvalidImage
	}
	intent := sha256.Sum256(encoded)
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.faulted.Load() {
		return ChangeResult{}, ErrStoreUnavailable
	}
	if err := ctx.Err(); err != nil {
		return ChangeResult{}, err
	}
	current := s.current.Load()
	if current == nil {
		return ChangeResult{}, ErrStoreUnavailable
	}
	issuer, registered := current.snapshot.issuers[request.Identity.Issuer]
	if !registered || !issuer.Enabled || issuer.Deleted || issuer.ConfigRevision != request.IssuerConfigRevision {
		return ChangeResult{}, ErrRevisionConflict
	}
	if _, active := current.snapshot.AccessFor(request.Identity); !active {
		return ChangeResult{}, ErrPermissionDenied
	}
	if record, known := s.changes[request.ChangeID]; known {
		if record.intentDigest != intent {
			return ChangeResult{}, ErrChangeConflict
		}
		result := record.result
		result.Replayed = true
		return result, nil
	}
	if _, known := current.snapshot.sessions[request.Digest]; known {
		return ChangeResult{}, ErrChangeConflict
	}
	image := current.snapshot.Image()
	// This trusted entry point follows successful Code/PKCE/nonce verification.
	// Persist human qualification separately from the revocable session.
	for i := range image.Principals {
		if image.Principals[i].Identity == request.Identity {
			image.Principals[i].HumanIssuerConfigRevision = request.IssuerConfigRevision
		}
	}
	sessions := make([]Session, 0, len(image.Sessions)+1)
	replaced := request.ReplacesDigest == ""
	for _, session := range image.Sessions {
		if session.Digest == request.ReplacesDigest {
			if session.Identity != request.Identity || session.Revoked || !request.Now.Before(session.ExpiresAt) {
				return ChangeResult{}, ErrPermissionDenied
			}
			session.Revoked = true
			replaced = true
		}
		if request.Now.Before(session.ExpiresAt) {
			sessions = append(sessions, session)
		}
	}
	if !replaced {
		return ChangeResult{}, ErrPermissionDenied
	}
	image.Sessions = append(sessions, Session{Digest: request.Digest, CSRFDigest: request.CSRFDigest, IssuerConfigRevision: request.IssuerConfigRevision, Identity: request.Identity, CreatedAt: request.Now.UTC(), ExpiresAt: request.Now.Add(request.Lifetime).UTC(), AuthTime: request.AuthTime.UTC()})
	record := AuditRecord{Revision: current.sequence + 1, ChangeID: hex.EncodeToString(request.ChangeID[:]), IntentDigest: hex.EncodeToString(intent[:]), ActorDigest: redactedDigest(request.Identity), OccurredAt: request.Now.UTC(), Operation: "session.issue", TargetDigests: []string{redactedDigest(request.Digest)}, Outcome: "committed"}
	image.Audit = append(image.Audit, record)
	if len(image.Audit) > retainedChanges {
		image.Audit = image.Audit[len(image.Audit)-retainedChanges:]
	}
	snapshot, err := compileImage(image, s.limits, current.snapshot)
	if err != nil {
		return ChangeResult{}, err
	}
	if len(snapshot.image) > ordinaryImageMaxBytes {
		return ChangeResult{}, ErrControlReserve
	}
	revision, err := signRevisionWithHistory(s.generation, current.sequence+1, current.digest, request.ChangeID, snapshot, s.privateKey, s.checkpointHistory(), intent)
	if err != nil {
		return ChangeResult{}, err
	}
	if err := s.persistAndPublish(ctx, revision); err != nil {
		return ChangeResult{}, err
	}
	return ChangeResult{Revision: revision.sequence, Digest: revision.digest}, nil
}

// RevokeSession is writer-internal logout for an authenticated cookie holder.
// Revocation remains in the signed state through expiry; it never changes an
// independent API token's identity or adds/removes Role assignments.
func (s *Store) RevokeSession(ctx context.Context, actor Identity, digest string, changeID [16]byte, now time.Time) (ChangeResult, error) {
	if s == nil || s.faulted.Load() {
		return ChangeResult{}, ErrStoreUnavailable
	}
	if len(s.privateKey) == 0 {
		return ChangeResult{}, ErrReadOnlyWriter
	}
	if changeID == [16]byte{} || !actor.valid() || !validHexDigest(digest) || now.IsZero() {
		return ChangeResult{}, ErrInvalidImage
	}
	intent := sha256.Sum256([]byte("session.revoke\x00" + redactedDigest(actor) + "\x00" + digest))
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.faulted.Load() {
		return ChangeResult{}, ErrStoreUnavailable
	}
	if err := ctx.Err(); err != nil {
		return ChangeResult{}, err
	}
	current := s.current.Load()
	if current == nil {
		return ChangeResult{}, ErrStoreUnavailable
	}
	session, known := current.snapshot.sessions[digest]
	if !known || session.Identity != actor {
		return ChangeResult{}, ErrPermissionDenied
	}
	if record, known := s.changes[changeID]; known {
		if record.intentDigest != intent {
			return ChangeResult{}, ErrChangeConflict
		}
		result := record.result
		result.Replayed = true
		return result, nil
	}
	image := current.snapshot.Image()
	for i := range image.Sessions {
		if image.Sessions[i].Digest == digest {
			image.Sessions[i].Revoked = true
		}
	}
	audit := AuditRecord{Revision: current.sequence + 1, ChangeID: hex.EncodeToString(changeID[:]), IntentDigest: hex.EncodeToString(intent[:]), ActorDigest: redactedDigest(actor), OccurredAt: now.UTC(), Operation: "session.revoke", TargetDigests: []string{redactedDigest(digest)}, Outcome: "committed"}
	image.Audit = append(image.Audit, audit)
	if len(image.Audit) > retainedChanges {
		image.Audit = image.Audit[len(image.Audit)-retainedChanges:]
	}
	snapshot, err := compileImage(image, s.limits, current.snapshot)
	if err != nil {
		return ChangeResult{}, err
	}
	revision, err := signRevisionWithHistory(s.generation, current.sequence+1, current.digest, changeID, snapshot, s.privateKey, s.checkpointHistory(), intent)
	if err != nil {
		return ChangeResult{}, err
	}
	if err := s.persistAndPublish(ctx, revision); err != nil {
		return ChangeResult{}, err
	}
	return ChangeResult{Revision: revision.sequence, Digest: revision.digest}, nil
}
