// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/anaregdesign/lantern/server/provider"
	"github.com/anaregdesign/lantern/server/service"
)

// Injectors from wire.go:

func initializeApp() (*App, error) {
	config := provider.NewConfig()
	logger := provider.NewLogger(config)
	graphCache := provider.NewGraphCache(config)
	lanternService := service.NewLanternService(graphCache)
	registry := provider.NewPrometheusRegistry()
	serverMetrics := provider.NewGrpcServerMetrics(registry)
	v := provider.NewGrpcServerOptions(logger, serverMetrics)
	server := provider.NewGrpcServer(v)
	listener, err := provider.NewListener(config)
	if err != nil {
		return nil, err
	}
	duration := newGCInterval(config)
	lanternServer := service.NewLanternServer(lanternService, server, listener, logger, duration)
	metricsServer := provider.NewMetricsServer(config, registry, logger)
	healthServer := provider.NewHealthServer()
	mainRegisteredHealth := registerHealthAndReflection(config, server, healthServer)
	app := newApp(config, logger, lanternServer, metricsServer, healthServer, mainRegisteredHealth)
	return app, nil
}
