// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/anaregdesign/lantern/server/provider"
	"github.com/anaregdesign/lantern/server/service"
)

// Injectors from wire.go:

func initializeApp() (*App, error) {
	config := provider.NewConfig()
	observabilityConfig := provider.NewObservabilityConfig(config)
	logger := provider.NewLogger(observabilityConfig)
	cacheConfig := provider.NewCacheConfig(config)
	graphCache := provider.NewGraphCache(cacheConfig)
	scanConfig := provider.NewScanConfig(config)
	replicationConfig := provider.NewReplicationConfig(config)
	mutationLogConfig := provider.NewMutationLogConfig(config)
	registry := provider.NewPrometheusRegistry()
	domainMetrics := provider.NewDomainMetrics(registry, observabilityConfig, graphCache)
	log := provider.NewMutationLog(mutationLogConfig, domainMetrics)
	clock := provider.NewHLCClock(replicationConfig)
	lanternService := newLanternService(graphCache, scanConfig, replicationConfig, logger, log, clock, domainMetrics)
	lanternReplicationService := newLanternReplicationService(log, graphCache, clock, logger, domainMetrics, lanternService)
	netConfig := provider.NewNetConfig(config)
	tlsConfig := provider.NewTLSConfig(config)
	rateLimitConfig := provider.NewRateLimitConfig(config)
	validationLimits := provider.NewValidationLimits(config)
	serverMetrics := provider.NewGrpcServerMetrics(registry)
	v, err := provider.NewGrpcServerOptions(netConfig, tlsConfig, rateLimitConfig, validationLimits, logger, serverMetrics, domainMetrics)
	if err != nil {
		return nil, err
	}
	server := provider.NewGrpcServer(v)
	listener, err := provider.NewListener(netConfig)
	if err != nil {
		return nil, err
	}
	shutdownConfig := provider.NewShutdownConfig(config)
	lifecycleConfig := provider.NewLifecycleConfig(cacheConfig, shutdownConfig)
	healthServer := provider.NewHealthServer()
	lanternServer := service.NewLanternServer(lanternService, lanternReplicationService, server, listener, logger, lifecycleConfig, healthServer, graphCache)
	readinessConfig := provider.NewReadinessConfig(config)
	peerConfig := provider.NewPeerConfig(config)
	gate := provider.NewReadinessGate(readinessConfig, peerConfig, healthServer)
	metricsServer := provider.NewMetricsServer(observabilityConfig, registry, gate, logger)
	tracing, err := provider.NewTracing(logger)
	if err != nil {
		return nil, err
	}
	metrics := provider.NewPumpMetrics(domainMetrics, gate)
	pump := provider.NewReplicationPump(peerConfig, replicationConfig, lanternService, graphCache, metrics, logger)
	antiEntropyConfig := provider.NewAntiEntropyConfig(config)
	antiEntropyMetrics := provider.NewAntiEntropyMetrics(domainMetrics, gate)
	antiEntropy := provider.NewAntiEntropyDriver(peerConfig, replicationConfig, antiEntropyConfig, lanternService, graphCache, pump, antiEntropyMetrics, logger)
	mainRegisteredHealth := registerHealthAndReflection(observabilityConfig, server, healthServer)
	app := newApp(config, logger, lanternServer, metricsServer, tracing, domainMetrics, healthServer, pump, antiEntropy, mainRegisteredHealth)
	return app, nil
}
