use std::{
    env,
    error::Error,
    fs,
    path::{Path, PathBuf},
};

fn main() -> Result<(), Box<dyn Error>> {
    let mut args = env::args();
    match (args.next(), args.next().as_deref(), args.next()) {
        (Some(_), Some("codegen"), None) => codegen(),
        _ => Err("usage: cargo xtask codegen".into()),
    }
}

fn codegen() -> Result<(), Box<dyn Error>> {
    let crate_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .ok_or("xtask must be nested in sdks/rust")?;
    let proto_root = crate_root.join("../../proto");
    if proto_root.is_symlink() {
        return Err(format!("refusing symlinked proto root: {}", proto_root.display()).into());
    }
    let mut protos = Vec::new();
    collect_schemas(&proto_root, &mut protos)?;
    if protos.is_empty() {
        return Err(format!("no root schemas under {}", proto_root.display()).into());
    }
    protos.sort();

    let gen_dir = crate_root.join("src/generated");
    if gen_dir.is_symlink() {
        return Err(format!(
            "refusing to generate through symlink: {}",
            gen_dir.display()
        )
        .into());
    }
    fs::create_dir_all(&gen_dir)?;

    let generated = gen_dir.join("graph.v1.rs");
    check_generated_dir(&gen_dir, &generated)?;

    let mut config = prost_build::Config::new();
    config.protoc_executable(protoc_bin_vendored::protoc_bin_path()?);
    tonic_prost_build::configure()
        .build_server(false)
        .out_dir(&gen_dir)
        .compile_with_config(
            config,
            &protos,
            &[proto_root, protoc_bin_vendored::include_path()?],
        )?;

    check_generated_dir(&gen_dir, &generated)?;
    let source = fs::read_to_string(&generated)?;
    fs::write(
        &generated,
        format!("// Code generated by cargo xtask codegen. DO NOT EDIT.\n{source}"),
    )?;
    Ok(())
}

fn collect_schemas(dir: &Path, protos: &mut Vec<PathBuf>) -> Result<(), Box<dyn Error>> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let kind = entry.file_type()?;
        if kind.is_symlink() {
            return Err(format!("refusing symlinked schema: {}", path.display()).into());
        }
        if kind.is_dir() {
            collect_schemas(&path, protos)?;
        } else if kind.is_file() && path.extension().is_some_and(|ext| ext == "proto") {
            protos.push(path);
        }
    }
    Ok(())
}

fn check_generated_dir(dir: &Path, expected: &Path) -> Result<(), Box<dyn Error>> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_symlink() {
            return Err(format!("refusing generated-source symlink: {}", path.display()).into());
        }
        if path.extension().is_some_and(|ext| ext == "rs") && path != expected {
            return Err(format!("unexpected generated source: {}", path.display()).into());
        }
    }
    Ok(())
}
