# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lantern_client._pb.graph.v1 import replication_pb2 as graph_dot_v1_dot_replication__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in graph/v1/replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LanternReplicationServiceStub:
    """LanternReplicationService carries the peer-to-peer (and CDC) replication
    surface. It is intentionally a separate service from LanternService so
    that operators can route, throttle, secure, or even disable replication
    independently of the public read/write API.

    NOTE — deviation from the original RFC: the Subscribe RPC was originally
    specified to live on LanternService. The realised proto split introduces
    a cyclic file import between graph.proto and replication.proto when both
    the request/response messages and the RPC live on opposite sides of the
    boundary. Hosting Subscribe on a dedicated service keeps the import
    graph one-way (replication.proto → graph.proto) and is documented as
    part of #178's implementation in docs/replication.md.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/graph.v1.LanternReplicationService/Subscribe',
                request_serializer=graph_dot_v1_dot_replication__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_replication__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.Snapshot = channel.unary_stream(
                '/graph.v1.LanternReplicationService/Snapshot',
                request_serializer=graph_dot_v1_dot_replication__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_replication__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.PeerStatus = channel.unary_unary(
                '/graph.v1.LanternReplicationService/PeerStatus',
                request_serializer=graph_dot_v1_dot_replication__pb2.PeerStatusRequest.SerializeToString,
                response_deserializer=graph_dot_v1_dot_replication__pb2.PeerStatusResponse.FromString,
                _registered_method=True)


class LanternReplicationServiceServicer:
    """LanternReplicationService carries the peer-to-peer (and CDC) replication
    surface. It is intentionally a separate service from LanternService so
    that operators can route, throttle, secure, or even disable replication
    independently of the public read/write API.

    NOTE — deviation from the original RFC: the Subscribe RPC was originally
    specified to live on LanternService. The realised proto split introduces
    a cyclic file import between graph.proto and replication.proto when both
    the request/response messages and the RPC live on opposite sides of the
    boundary. Hosting Subscribe on a dedicated service keeps the import
    graph one-way (replication.proto → graph.proto) and is documented as
    part of #178's implementation in docs/replication.md.
    """

    def Subscribe(self, request, context):
        """Subscribe streams replicated mutations to a peer (or CDC consumer)
        starting at `from_seq` (inclusive). The server replays any in-buffer
        entries first, then streams live mutations as they are appended.

        If `from_seq` is below the server's first available seq the call
        fails with FAILED_PRECONDITION ("gapped") and the caller must
        snapshot + resubscribe. Slow consumers whose channel backs up may
        also have the stream terminated with FAILED_PRECONDITION — the
        remedy is the same.

        No HTTP gateway annotation: replication is intentionally gRPC-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Snapshot(self, request, context):
        """Snapshot streams a point-in-time, causally-consistent dump of every
        live vertex and edge to a bootstrapping peer. The first frame is a
        SnapshotHeader carrying the (cutoff_seq, cutoff_hlc) the server used
        to materialise the snapshot; the last frame is a SnapshotFooter with
        the actual vertex / edge counts streamed.

        Bootstrap stitch contract: after receiving the SnapshotFooter the
        peer MUST call `Subscribe(from_seq = cutoff_seq + 1)` on the same
        origin to pick up the live tail. Without that the snapshot and the
        live stream cannot be glued together without gap or overlap.

        No HTTP gateway annotation (parity with Subscribe).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PeerStatus(self, request, context):
        """PeerStatus returns the responder's per-origin (last_applied_seq,
        last_applied_hlc) map. Used by anti-entropy (#186) as the
        convergence safety net for the Subscribe pump: a periodic
        PeerStatus poll lets each node detect that the peer's view of
        some origin is ahead of its own and request the missing tail
        (via Subscribe(from_seq = local+1)) or — when that returns
        FailedPrecondition — fall back to Snapshot.

        The reply set always includes the responder's OWN origin (taken
        from its mutation log's last appended seq + hlc) plus every
        remote origin whose mutation has ever been applied via
        ApplyMutation since process start. Origins the responder has
        never seen are simply absent from the map.

        The RPC is intentionally unary and stateless — callers can
        multiplex it across many peers without holding any server-side
        resources. Returns Unavailable when the mutation log is unset
        (single-instance test path).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanternReplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=graph_dot_v1_dot_replication__pb2.SubscribeRequest.FromString,
                    response_serializer=graph_dot_v1_dot_replication__pb2.SubscribeResponse.SerializeToString,
            ),
            'Snapshot': grpc.unary_stream_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=graph_dot_v1_dot_replication__pb2.SnapshotRequest.FromString,
                    response_serializer=graph_dot_v1_dot_replication__pb2.SnapshotResponse.SerializeToString,
            ),
            'PeerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.PeerStatus,
                    request_deserializer=graph_dot_v1_dot_replication__pb2.PeerStatusRequest.FromString,
                    response_serializer=graph_dot_v1_dot_replication__pb2.PeerStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'graph.v1.LanternReplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('graph.v1.LanternReplicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LanternReplicationService:
    """LanternReplicationService carries the peer-to-peer (and CDC) replication
    surface. It is intentionally a separate service from LanternService so
    that operators can route, throttle, secure, or even disable replication
    independently of the public read/write API.

    NOTE — deviation from the original RFC: the Subscribe RPC was originally
    specified to live on LanternService. The realised proto split introduces
    a cyclic file import between graph.proto and replication.proto when both
    the request/response messages and the RPC live on opposite sides of the
    boundary. Hosting Subscribe on a dedicated service keeps the import
    graph one-way (replication.proto → graph.proto) and is documented as
    part of #178's implementation in docs/replication.md.
    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/graph.v1.LanternReplicationService/Subscribe',
            graph_dot_v1_dot_replication__pb2.SubscribeRequest.SerializeToString,
            graph_dot_v1_dot_replication__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/graph.v1.LanternReplicationService/Snapshot',
            graph_dot_v1_dot_replication__pb2.SnapshotRequest.SerializeToString,
            graph_dot_v1_dot_replication__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PeerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.v1.LanternReplicationService/PeerStatus',
            graph_dot_v1_dot_replication__pb2.PeerStatusRequest.SerializeToString,
            graph_dot_v1_dot_replication__pb2.PeerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
