name: __PROJECT_NAME__
publish_to: none
version: 0.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  __PACKAGE_NAME__:
    path: __PACKAGE_PATH__

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
