// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: graph/v1/changes.proto

package graphv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeProjection int32

const (
	ChangeProjection_CHANGE_PROJECTION_UNSPECIFIED ChangeProjection = 0
	ChangeProjection_CHANGE_PROJECTION_IDENTITY    ChangeProjection = 1
	ChangeProjection_CHANGE_PROJECTION_VALUE       ChangeProjection = 2
)

// Enum value maps for ChangeProjection.
var (
	ChangeProjection_name = map[int32]string{
		0: "CHANGE_PROJECTION_UNSPECIFIED",
		1: "CHANGE_PROJECTION_IDENTITY",
		2: "CHANGE_PROJECTION_VALUE",
	}
	ChangeProjection_value = map[string]int32{
		"CHANGE_PROJECTION_UNSPECIFIED": 0,
		"CHANGE_PROJECTION_IDENTITY":    1,
		"CHANGE_PROJECTION_VALUE":       2,
	}
)

func (x ChangeProjection) Enum() *ChangeProjection {
	p := new(ChangeProjection)
	*p = x
	return p
}

func (x ChangeProjection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeProjection) Descriptor() protoreflect.EnumDescriptor {
	return file_graph_v1_changes_proto_enumTypes[0].Descriptor()
}

func (ChangeProjection) Type() protoreflect.EnumType {
	return &file_graph_v1_changes_proto_enumTypes[0]
}

func (x ChangeProjection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeProjection.Descriptor instead.
func (ChangeProjection) EnumDescriptor() ([]byte, []int) {
	return file_graph_v1_changes_proto_rawDescGZIP(), []int{0}
}

type WatchChangesRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Prefix     string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // Literal logical prefix, applied to both Edge endpoints.
	Projection ChangeProjection       `protobuf:"varint,2,opt,name=projection,proto3,enum=graph.v1.ChangeProjection" json:"projection,omitempty"`
	// Bootstrap opens a tail at an atomic publication cut. Keep it open while
	// rebuilding the authorized resident cache with ordinary read RPCs.
	Bootstrap     bool   `protobuf:"varint,3,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	Cursor        []byte `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"` // Opaque, encrypted and bound to this Principal/policy/scope.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchChangesRequest) Reset() {
	*x = WatchChangesRequest{}
	mi := &file_graph_v1_changes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchChangesRequest) ProtoMessage() {}

func (x *WatchChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_changes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchChangesRequest.ProtoReflect.Descriptor instead.
func (*WatchChangesRequest) Descriptor() ([]byte, []int) {
	return file_graph_v1_changes_proto_rawDescGZIP(), []int{0}
}

func (x *WatchChangesRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *WatchChangesRequest) GetProjection() ChangeProjection {
	if x != nil {
		return x.Projection
	}
	return ChangeProjection_CHANGE_PROJECTION_UNSPECIFIED
}

func (x *WatchChangesRequest) GetBootstrap() bool {
	if x != nil {
		return x.Bootstrap
	}
	return false
}

func (x *WatchChangesRequest) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type ChangeInvalidation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identity:
	//
	//	*ChangeInvalidation_VertexKey
	//	*ChangeInvalidation_EdgeKey
	Identity isChangeInvalidation_Identity `protobuf_oneof:"identity"`
	// Only VALUE projection may include this current local live image. Omitted
	// image means invalidate/refetch, including deletes, TTL and concurrent writes.
	//
	// Types that are valid to be assigned to CurrentImage:
	//
	//	*ChangeInvalidation_Vertex
	//	*ChangeInvalidation_Edge
	CurrentImage  isChangeInvalidation_CurrentImage `protobuf_oneof:"current_image"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeInvalidation) Reset() {
	*x = ChangeInvalidation{}
	mi := &file_graph_v1_changes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeInvalidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeInvalidation) ProtoMessage() {}

func (x *ChangeInvalidation) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_changes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeInvalidation.ProtoReflect.Descriptor instead.
func (*ChangeInvalidation) Descriptor() ([]byte, []int) {
	return file_graph_v1_changes_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeInvalidation) GetIdentity() isChangeInvalidation_Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ChangeInvalidation) GetVertexKey() string {
	if x != nil {
		if x, ok := x.Identity.(*ChangeInvalidation_VertexKey); ok {
			return x.VertexKey
		}
	}
	return ""
}

func (x *ChangeInvalidation) GetEdgeKey() *EdgeKey {
	if x != nil {
		if x, ok := x.Identity.(*ChangeInvalidation_EdgeKey); ok {
			return x.EdgeKey
		}
	}
	return nil
}

func (x *ChangeInvalidation) GetCurrentImage() isChangeInvalidation_CurrentImage {
	if x != nil {
		return x.CurrentImage
	}
	return nil
}

func (x *ChangeInvalidation) GetVertex() *Vertex {
	if x != nil {
		if x, ok := x.CurrentImage.(*ChangeInvalidation_Vertex); ok {
			return x.Vertex
		}
	}
	return nil
}

func (x *ChangeInvalidation) GetEdge() *Edge {
	if x != nil {
		if x, ok := x.CurrentImage.(*ChangeInvalidation_Edge); ok {
			return x.Edge
		}
	}
	return nil
}

type isChangeInvalidation_Identity interface {
	isChangeInvalidation_Identity()
}

type ChangeInvalidation_VertexKey struct {
	VertexKey string `protobuf:"bytes,1,opt,name=vertex_key,json=vertexKey,proto3,oneof"`
}

type ChangeInvalidation_EdgeKey struct {
	EdgeKey *EdgeKey `protobuf:"bytes,2,opt,name=edge_key,json=edgeKey,proto3,oneof"`
}

func (*ChangeInvalidation_VertexKey) isChangeInvalidation_Identity() {}

func (*ChangeInvalidation_EdgeKey) isChangeInvalidation_Identity() {}

type isChangeInvalidation_CurrentImage interface {
	isChangeInvalidation_CurrentImage()
}

type ChangeInvalidation_Vertex struct {
	Vertex *Vertex `protobuf:"bytes,3,opt,name=vertex,proto3,oneof"`
}

type ChangeInvalidation_Edge struct {
	Edge *Edge `protobuf:"bytes,4,opt,name=edge,proto3,oneof"`
}

func (*ChangeInvalidation_Vertex) isChangeInvalidation_CurrentImage() {}

func (*ChangeInvalidation_Edge) isChangeInvalidation_CurrentImage() {}

type WatchChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invalidations []*ChangeInvalidation  `protobuf:"bytes,1,rep,name=invalidations,proto3" json:"invalidations,omitempty"`
	// Persist cursor only after applying every invalidation in this frame. A
	// mutation may span frames; only its final visible frame carries a cursor.
	Cursor []byte `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Bootstrap/periodic progress frames have no invalidations and fixed-sized
	// encrypted cursors. Hidden-only commits never cause an extra frame.
	Bootstrap     bool `protobuf:"varint,3,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchChangesResponse) Reset() {
	*x = WatchChangesResponse{}
	mi := &file_graph_v1_changes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchChangesResponse) ProtoMessage() {}

func (x *WatchChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_changes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchChangesResponse.ProtoReflect.Descriptor instead.
func (*WatchChangesResponse) Descriptor() ([]byte, []int) {
	return file_graph_v1_changes_proto_rawDescGZIP(), []int{2}
}

func (x *WatchChangesResponse) GetInvalidations() []*ChangeInvalidation {
	if x != nil {
		return x.Invalidations
	}
	return nil
}

func (x *WatchChangesResponse) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *WatchChangesResponse) GetBootstrap() bool {
	if x != nil {
		return x.Bootstrap
	}
	return false
}

var File_graph_v1_changes_proto protoreflect.FileDescriptor

const file_graph_v1_changes_proto_rawDesc = "" +
	"\n" +
	"\x16graph/v1/changes.proto\x12\bgraph.v1\x1a\x14graph/v1/graph.proto\"\x9f\x01\n" +
	"\x13WatchChangesRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12:\n" +
	"\n" +
	"projection\x18\x02 \x01(\x0e2\x1a.graph.v1.ChangeProjectionR\n" +
	"projection\x12\x1c\n" +
	"\tbootstrap\x18\x03 \x01(\bR\tbootstrap\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\fR\x06cursor\"\xd4\x01\n" +
	"\x12ChangeInvalidation\x12\x1f\n" +
	"\n" +
	"vertex_key\x18\x01 \x01(\tH\x00R\tvertexKey\x12.\n" +
	"\bedge_key\x18\x02 \x01(\v2\x11.graph.v1.EdgeKeyH\x00R\aedgeKey\x12*\n" +
	"\x06vertex\x18\x03 \x01(\v2\x10.graph.v1.VertexH\x01R\x06vertex\x12$\n" +
	"\x04edge\x18\x04 \x01(\v2\x0e.graph.v1.EdgeH\x01R\x04edgeB\n" +
	"\n" +
	"\bidentityB\x0f\n" +
	"\rcurrent_image\"\x90\x01\n" +
	"\x14WatchChangesResponse\x12B\n" +
	"\rinvalidations\x18\x01 \x03(\v2\x1c.graph.v1.ChangeInvalidationR\rinvalidations\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\fR\x06cursor\x12\x1c\n" +
	"\tbootstrap\x18\x03 \x01(\bR\tbootstrap*r\n" +
	"\x10ChangeProjection\x12!\n" +
	"\x1dCHANGE_PROJECTION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCHANGE_PROJECTION_IDENTITY\x10\x01\x12\x1b\n" +
	"\x17CHANGE_PROJECTION_VALUE\x10\x022g\n" +
	"\x14LanternChangeService\x12O\n" +
	"\fWatchChanges\x12\x1d.graph.v1.WatchChangesRequest\x1a\x1e.graph.v1.WatchChangesResponse0\x01B\x92\x01\n" +
	"\fcom.graph.v1B\fChangesProtoP\x01Z3github.com/anaregdesign/lantern/pb/graph/v1;graphv1\xa2\x02\x03GXX\xaa\x02\bGraph.V1\xca\x02\bGraph\\V1\xe2\x02\x14Graph\\V1\\GPBMetadata\xea\x02\tGraph::V1b\x06proto3"

var (
	file_graph_v1_changes_proto_rawDescOnce sync.Once
	file_graph_v1_changes_proto_rawDescData []byte
)

func file_graph_v1_changes_proto_rawDescGZIP() []byte {
	file_graph_v1_changes_proto_rawDescOnce.Do(func() {
		file_graph_v1_changes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_v1_changes_proto_rawDesc), len(file_graph_v1_changes_proto_rawDesc)))
	})
	return file_graph_v1_changes_proto_rawDescData
}

var file_graph_v1_changes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_graph_v1_changes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_graph_v1_changes_proto_goTypes = []any{
	(ChangeProjection)(0),        // 0: graph.v1.ChangeProjection
	(*WatchChangesRequest)(nil),  // 1: graph.v1.WatchChangesRequest
	(*ChangeInvalidation)(nil),   // 2: graph.v1.ChangeInvalidation
	(*WatchChangesResponse)(nil), // 3: graph.v1.WatchChangesResponse
	(*EdgeKey)(nil),              // 4: graph.v1.EdgeKey
	(*Vertex)(nil),               // 5: graph.v1.Vertex
	(*Edge)(nil),                 // 6: graph.v1.Edge
}
var file_graph_v1_changes_proto_depIdxs = []int32{
	0, // 0: graph.v1.WatchChangesRequest.projection:type_name -> graph.v1.ChangeProjection
	4, // 1: graph.v1.ChangeInvalidation.edge_key:type_name -> graph.v1.EdgeKey
	5, // 2: graph.v1.ChangeInvalidation.vertex:type_name -> graph.v1.Vertex
	6, // 3: graph.v1.ChangeInvalidation.edge:type_name -> graph.v1.Edge
	2, // 4: graph.v1.WatchChangesResponse.invalidations:type_name -> graph.v1.ChangeInvalidation
	1, // 5: graph.v1.LanternChangeService.WatchChanges:input_type -> graph.v1.WatchChangesRequest
	3, // 6: graph.v1.LanternChangeService.WatchChanges:output_type -> graph.v1.WatchChangesResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_graph_v1_changes_proto_init() }
func file_graph_v1_changes_proto_init() {
	if File_graph_v1_changes_proto != nil {
		return
	}
	file_graph_v1_graph_proto_init()
	file_graph_v1_changes_proto_msgTypes[1].OneofWrappers = []any{
		(*ChangeInvalidation_VertexKey)(nil),
		(*ChangeInvalidation_EdgeKey)(nil),
		(*ChangeInvalidation_Vertex)(nil),
		(*ChangeInvalidation_Edge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_v1_changes_proto_rawDesc), len(file_graph_v1_changes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_v1_changes_proto_goTypes,
		DependencyIndexes: file_graph_v1_changes_proto_depIdxs,
		EnumInfos:         file_graph_v1_changes_proto_enumTypes,
		MessageInfos:      file_graph_v1_changes_proto_msgTypes,
	}.Build()
	File_graph_v1_changes_proto = out.File
	file_graph_v1_changes_proto_goTypes = nil
	file_graph_v1_changes_proto_depIdxs = nil
}
