// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: graph/v1/graph.proto

package graphv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LanternService_Illuminate_FullMethodName             = "/graph.v1.LanternService/Illuminate"
	LanternService_GetVertex_FullMethodName              = "/graph.v1.LanternService/GetVertex"
	LanternService_GetVertices_FullMethodName            = "/graph.v1.LanternService/GetVertices"
	LanternService_PutVertex_FullMethodName              = "/graph.v1.LanternService/PutVertex"
	LanternService_PutVertices_FullMethodName            = "/graph.v1.LanternService/PutVertices"
	LanternService_DeleteVertex_FullMethodName           = "/graph.v1.LanternService/DeleteVertex"
	LanternService_DeleteVertices_FullMethodName         = "/graph.v1.LanternService/DeleteVertices"
	LanternService_ScanVertices_FullMethodName           = "/graph.v1.LanternService/ScanVertices"
	LanternService_CountVerticesByPrefix_FullMethodName  = "/graph.v1.LanternService/CountVerticesByPrefix"
	LanternService_DeleteVerticesByPrefix_FullMethodName = "/graph.v1.LanternService/DeleteVerticesByPrefix"
	LanternService_GetEdge_FullMethodName                = "/graph.v1.LanternService/GetEdge"
	LanternService_GetEdges_FullMethodName               = "/graph.v1.LanternService/GetEdges"
	LanternService_AddEdge_FullMethodName                = "/graph.v1.LanternService/AddEdge"
	LanternService_AddEdges_FullMethodName               = "/graph.v1.LanternService/AddEdges"
	LanternService_PutEdge_FullMethodName                = "/graph.v1.LanternService/PutEdge"
	LanternService_PutEdges_FullMethodName               = "/graph.v1.LanternService/PutEdges"
	LanternService_DeleteEdge_FullMethodName             = "/graph.v1.LanternService/DeleteEdge"
	LanternService_DeleteEdges_FullMethodName            = "/graph.v1.LanternService/DeleteEdges"
	LanternService_ScanEdges_FullMethodName              = "/graph.v1.LanternService/ScanEdges"
)

// LanternServiceClient is the client API for LanternService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LanternServiceClient interface {
	Illuminate(ctx context.Context, in *IlluminateRequest, opts ...grpc.CallOption) (*IlluminateResponse, error)
	GetVertex(ctx context.Context, in *GetVertexRequest, opts ...grpc.CallOption) (*GetVertexResponse, error)
	// GetVertices reads several vertices in one round trip.
	GetVertices(ctx context.Context, in *GetVerticesRequest, opts ...grpc.CallOption) (*GetVerticesResponse, error)
	// PutVertex writes a single vertex. Thin facade over PutVertices.
	PutVertex(ctx context.Context, in *PutVertexRequest, opts ...grpc.CallOption) (*PutVertexResponse, error)
	PutVertices(ctx context.Context, in *PutVerticesRequest, opts ...grpc.CallOption) (*PutVerticesResponse, error)
	DeleteVertex(ctx context.Context, in *DeleteVertexRequest, opts ...grpc.CallOption) (*DeleteVertexResponse, error)
	// DeleteVertices removes several vertices in one round trip.
	DeleteVertices(ctx context.Context, in *DeleteVerticesRequest, opts ...grpc.CallOption) (*DeleteVerticesResponse, error)
	// ScanVertices streams vertices whose key starts with the given prefix in
	// ascending order, page by page. Plural-only — prefix scan is inherently
	// plural.
	ScanVertices(ctx context.Context, in *ScanVerticesRequest, opts ...grpc.CallOption) (*ScanVerticesResponse, error)
	// CountVerticesByPrefix returns the number of live vertices whose key
	// starts with the given prefix.
	CountVerticesByPrefix(ctx context.Context, in *CountVerticesByPrefixRequest, opts ...grpc.CallOption) (*CountVerticesByPrefixResponse, error)
	// DeleteVerticesByPrefix deletes up to `limit` vertices whose key starts
	// with the given prefix. Pass `dry_run = true` to preview the count
	// without mutating state.
	DeleteVerticesByPrefix(ctx context.Context, in *DeleteVerticesByPrefixRequest, opts ...grpc.CallOption) (*DeleteVerticesByPrefixResponse, error)
	GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...grpc.CallOption) (*GetEdgeResponse, error)
	// GetEdges reads several edges in one round trip.
	GetEdges(ctx context.Context, in *GetEdgesRequest, opts ...grpc.CallOption) (*GetEdgesResponse, error)
	// AddEdge is non-idempotent (accumulates weight). Thin facade over AddEdges.
	AddEdge(ctx context.Context, in *AddEdgeRequest, opts ...grpc.CallOption) (*AddEdgeResponse, error)
	// AddEdges is non-idempotent (accumulates weight). POST per REST conventions.
	AddEdges(ctx context.Context, in *AddEdgesRequest, opts ...grpc.CallOption) (*AddEdgesResponse, error)
	// PutEdge is idempotent (replaces weight). Thin facade over PutEdges.
	PutEdge(ctx context.Context, in *PutEdgeRequest, opts ...grpc.CallOption) (*PutEdgeResponse, error)
	// PutEdges is idempotent (replaces weight). PUT per REST conventions.
	PutEdges(ctx context.Context, in *PutEdgesRequest, opts ...grpc.CallOption) (*PutEdgesResponse, error)
	DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*DeleteEdgeResponse, error)
	// DeleteEdges removes several edges in one round trip.
	DeleteEdges(ctx context.Context, in *DeleteEdgesRequest, opts ...grpc.CallOption) (*DeleteEdgesResponse, error)
	// ScanEdges streams edges whose tail key starts with `tail_prefix` AND
	// whose head key starts with `head_prefix`, in ascending (tail, head)
	// order, page by page. Plural-only — prefix scan is inherently plural.
	ScanEdges(ctx context.Context, in *ScanEdgesRequest, opts ...grpc.CallOption) (*ScanEdgesResponse, error)
}

type lanternServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLanternServiceClient(cc grpc.ClientConnInterface) LanternServiceClient {
	return &lanternServiceClient{cc}
}

func (c *lanternServiceClient) Illuminate(ctx context.Context, in *IlluminateRequest, opts ...grpc.CallOption) (*IlluminateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IlluminateResponse)
	err := c.cc.Invoke(ctx, LanternService_Illuminate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) GetVertex(ctx context.Context, in *GetVertexRequest, opts ...grpc.CallOption) (*GetVertexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVertexResponse)
	err := c.cc.Invoke(ctx, LanternService_GetVertex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) GetVertices(ctx context.Context, in *GetVerticesRequest, opts ...grpc.CallOption) (*GetVerticesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVerticesResponse)
	err := c.cc.Invoke(ctx, LanternService_GetVertices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) PutVertex(ctx context.Context, in *PutVertexRequest, opts ...grpc.CallOption) (*PutVertexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutVertexResponse)
	err := c.cc.Invoke(ctx, LanternService_PutVertex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) PutVertices(ctx context.Context, in *PutVerticesRequest, opts ...grpc.CallOption) (*PutVerticesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutVerticesResponse)
	err := c.cc.Invoke(ctx, LanternService_PutVertices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) DeleteVertex(ctx context.Context, in *DeleteVertexRequest, opts ...grpc.CallOption) (*DeleteVertexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVertexResponse)
	err := c.cc.Invoke(ctx, LanternService_DeleteVertex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) DeleteVertices(ctx context.Context, in *DeleteVerticesRequest, opts ...grpc.CallOption) (*DeleteVerticesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVerticesResponse)
	err := c.cc.Invoke(ctx, LanternService_DeleteVertices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) ScanVertices(ctx context.Context, in *ScanVerticesRequest, opts ...grpc.CallOption) (*ScanVerticesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanVerticesResponse)
	err := c.cc.Invoke(ctx, LanternService_ScanVertices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) CountVerticesByPrefix(ctx context.Context, in *CountVerticesByPrefixRequest, opts ...grpc.CallOption) (*CountVerticesByPrefixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountVerticesByPrefixResponse)
	err := c.cc.Invoke(ctx, LanternService_CountVerticesByPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) DeleteVerticesByPrefix(ctx context.Context, in *DeleteVerticesByPrefixRequest, opts ...grpc.CallOption) (*DeleteVerticesByPrefixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVerticesByPrefixResponse)
	err := c.cc.Invoke(ctx, LanternService_DeleteVerticesByPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...grpc.CallOption) (*GetEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEdgeResponse)
	err := c.cc.Invoke(ctx, LanternService_GetEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) GetEdges(ctx context.Context, in *GetEdgesRequest, opts ...grpc.CallOption) (*GetEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEdgesResponse)
	err := c.cc.Invoke(ctx, LanternService_GetEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) AddEdge(ctx context.Context, in *AddEdgeRequest, opts ...grpc.CallOption) (*AddEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEdgeResponse)
	err := c.cc.Invoke(ctx, LanternService_AddEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) AddEdges(ctx context.Context, in *AddEdgesRequest, opts ...grpc.CallOption) (*AddEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEdgesResponse)
	err := c.cc.Invoke(ctx, LanternService_AddEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) PutEdge(ctx context.Context, in *PutEdgeRequest, opts ...grpc.CallOption) (*PutEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutEdgeResponse)
	err := c.cc.Invoke(ctx, LanternService_PutEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) PutEdges(ctx context.Context, in *PutEdgesRequest, opts ...grpc.CallOption) (*PutEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutEdgesResponse)
	err := c.cc.Invoke(ctx, LanternService_PutEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*DeleteEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEdgeResponse)
	err := c.cc.Invoke(ctx, LanternService_DeleteEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) DeleteEdges(ctx context.Context, in *DeleteEdgesRequest, opts ...grpc.CallOption) (*DeleteEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEdgesResponse)
	err := c.cc.Invoke(ctx, LanternService_DeleteEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanternServiceClient) ScanEdges(ctx context.Context, in *ScanEdgesRequest, opts ...grpc.CallOption) (*ScanEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanEdgesResponse)
	err := c.cc.Invoke(ctx, LanternService_ScanEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LanternServiceServer is the server API for LanternService service.
// All implementations should embed UnimplementedLanternServiceServer
// for forward compatibility.
type LanternServiceServer interface {
	Illuminate(context.Context, *IlluminateRequest) (*IlluminateResponse, error)
	GetVertex(context.Context, *GetVertexRequest) (*GetVertexResponse, error)
	// GetVertices reads several vertices in one round trip.
	GetVertices(context.Context, *GetVerticesRequest) (*GetVerticesResponse, error)
	// PutVertex writes a single vertex. Thin facade over PutVertices.
	PutVertex(context.Context, *PutVertexRequest) (*PutVertexResponse, error)
	PutVertices(context.Context, *PutVerticesRequest) (*PutVerticesResponse, error)
	DeleteVertex(context.Context, *DeleteVertexRequest) (*DeleteVertexResponse, error)
	// DeleteVertices removes several vertices in one round trip.
	DeleteVertices(context.Context, *DeleteVerticesRequest) (*DeleteVerticesResponse, error)
	// ScanVertices streams vertices whose key starts with the given prefix in
	// ascending order, page by page. Plural-only — prefix scan is inherently
	// plural.
	ScanVertices(context.Context, *ScanVerticesRequest) (*ScanVerticesResponse, error)
	// CountVerticesByPrefix returns the number of live vertices whose key
	// starts with the given prefix.
	CountVerticesByPrefix(context.Context, *CountVerticesByPrefixRequest) (*CountVerticesByPrefixResponse, error)
	// DeleteVerticesByPrefix deletes up to `limit` vertices whose key starts
	// with the given prefix. Pass `dry_run = true` to preview the count
	// without mutating state.
	DeleteVerticesByPrefix(context.Context, *DeleteVerticesByPrefixRequest) (*DeleteVerticesByPrefixResponse, error)
	GetEdge(context.Context, *GetEdgeRequest) (*GetEdgeResponse, error)
	// GetEdges reads several edges in one round trip.
	GetEdges(context.Context, *GetEdgesRequest) (*GetEdgesResponse, error)
	// AddEdge is non-idempotent (accumulates weight). Thin facade over AddEdges.
	AddEdge(context.Context, *AddEdgeRequest) (*AddEdgeResponse, error)
	// AddEdges is non-idempotent (accumulates weight). POST per REST conventions.
	AddEdges(context.Context, *AddEdgesRequest) (*AddEdgesResponse, error)
	// PutEdge is idempotent (replaces weight). Thin facade over PutEdges.
	PutEdge(context.Context, *PutEdgeRequest) (*PutEdgeResponse, error)
	// PutEdges is idempotent (replaces weight). PUT per REST conventions.
	PutEdges(context.Context, *PutEdgesRequest) (*PutEdgesResponse, error)
	DeleteEdge(context.Context, *DeleteEdgeRequest) (*DeleteEdgeResponse, error)
	// DeleteEdges removes several edges in one round trip.
	DeleteEdges(context.Context, *DeleteEdgesRequest) (*DeleteEdgesResponse, error)
	// ScanEdges streams edges whose tail key starts with `tail_prefix` AND
	// whose head key starts with `head_prefix`, in ascending (tail, head)
	// order, page by page. Plural-only — prefix scan is inherently plural.
	ScanEdges(context.Context, *ScanEdgesRequest) (*ScanEdgesResponse, error)
}

// UnimplementedLanternServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLanternServiceServer struct{}

func (UnimplementedLanternServiceServer) Illuminate(context.Context, *IlluminateRequest) (*IlluminateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Illuminate not implemented")
}
func (UnimplementedLanternServiceServer) GetVertex(context.Context, *GetVertexRequest) (*GetVertexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVertex not implemented")
}
func (UnimplementedLanternServiceServer) GetVertices(context.Context, *GetVerticesRequest) (*GetVerticesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVertices not implemented")
}
func (UnimplementedLanternServiceServer) PutVertex(context.Context, *PutVertexRequest) (*PutVertexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutVertex not implemented")
}
func (UnimplementedLanternServiceServer) PutVertices(context.Context, *PutVerticesRequest) (*PutVerticesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutVertices not implemented")
}
func (UnimplementedLanternServiceServer) DeleteVertex(context.Context, *DeleteVertexRequest) (*DeleteVertexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVertex not implemented")
}
func (UnimplementedLanternServiceServer) DeleteVertices(context.Context, *DeleteVerticesRequest) (*DeleteVerticesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVertices not implemented")
}
func (UnimplementedLanternServiceServer) ScanVertices(context.Context, *ScanVerticesRequest) (*ScanVerticesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanVertices not implemented")
}
func (UnimplementedLanternServiceServer) CountVerticesByPrefix(context.Context, *CountVerticesByPrefixRequest) (*CountVerticesByPrefixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountVerticesByPrefix not implemented")
}
func (UnimplementedLanternServiceServer) DeleteVerticesByPrefix(context.Context, *DeleteVerticesByPrefixRequest) (*DeleteVerticesByPrefixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVerticesByPrefix not implemented")
}
func (UnimplementedLanternServiceServer) GetEdge(context.Context, *GetEdgeRequest) (*GetEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdge not implemented")
}
func (UnimplementedLanternServiceServer) GetEdges(context.Context, *GetEdgesRequest) (*GetEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdges not implemented")
}
func (UnimplementedLanternServiceServer) AddEdge(context.Context, *AddEdgeRequest) (*AddEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddEdge not implemented")
}
func (UnimplementedLanternServiceServer) AddEdges(context.Context, *AddEdgesRequest) (*AddEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddEdges not implemented")
}
func (UnimplementedLanternServiceServer) PutEdge(context.Context, *PutEdgeRequest) (*PutEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutEdge not implemented")
}
func (UnimplementedLanternServiceServer) PutEdges(context.Context, *PutEdgesRequest) (*PutEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutEdges not implemented")
}
func (UnimplementedLanternServiceServer) DeleteEdge(context.Context, *DeleteEdgeRequest) (*DeleteEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEdge not implemented")
}
func (UnimplementedLanternServiceServer) DeleteEdges(context.Context, *DeleteEdgesRequest) (*DeleteEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEdges not implemented")
}
func (UnimplementedLanternServiceServer) ScanEdges(context.Context, *ScanEdgesRequest) (*ScanEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanEdges not implemented")
}
func (UnimplementedLanternServiceServer) testEmbeddedByValue() {}

// UnsafeLanternServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LanternServiceServer will
// result in compilation errors.
type UnsafeLanternServiceServer interface {
	mustEmbedUnimplementedLanternServiceServer()
}

func RegisterLanternServiceServer(s grpc.ServiceRegistrar, srv LanternServiceServer) {
	// If the following call panics, it indicates UnimplementedLanternServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LanternService_ServiceDesc, srv)
}

func _LanternService_Illuminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IlluminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).Illuminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_Illuminate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).Illuminate(ctx, req.(*IlluminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_GetVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVertexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).GetVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_GetVertex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).GetVertex(ctx, req.(*GetVertexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_GetVertices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerticesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).GetVertices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_GetVertices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).GetVertices(ctx, req.(*GetVerticesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_PutVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutVertexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).PutVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_PutVertex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).PutVertex(ctx, req.(*PutVertexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_PutVertices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutVerticesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).PutVertices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_PutVertices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).PutVertices(ctx, req.(*PutVerticesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_DeleteVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVertexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).DeleteVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_DeleteVertex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).DeleteVertex(ctx, req.(*DeleteVertexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_DeleteVertices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVerticesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).DeleteVertices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_DeleteVertices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).DeleteVertices(ctx, req.(*DeleteVerticesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_ScanVertices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanVerticesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).ScanVertices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_ScanVertices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).ScanVertices(ctx, req.(*ScanVerticesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_CountVerticesByPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountVerticesByPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).CountVerticesByPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_CountVerticesByPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).CountVerticesByPrefix(ctx, req.(*CountVerticesByPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_DeleteVerticesByPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVerticesByPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).DeleteVerticesByPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_DeleteVerticesByPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).DeleteVerticesByPrefix(ctx, req.(*DeleteVerticesByPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_GetEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).GetEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_GetEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).GetEdge(ctx, req.(*GetEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_GetEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).GetEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_GetEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).GetEdges(ctx, req.(*GetEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_AddEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).AddEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_AddEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).AddEdge(ctx, req.(*AddEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_AddEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).AddEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_AddEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).AddEdges(ctx, req.(*AddEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_PutEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).PutEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_PutEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).PutEdge(ctx, req.(*PutEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_PutEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).PutEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_PutEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).PutEdges(ctx, req.(*PutEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_DeleteEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).DeleteEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_DeleteEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).DeleteEdge(ctx, req.(*DeleteEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_DeleteEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).DeleteEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_DeleteEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).DeleteEdges(ctx, req.(*DeleteEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanternService_ScanEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanternServiceServer).ScanEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanternService_ScanEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanternServiceServer).ScanEdges(ctx, req.(*ScanEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LanternService_ServiceDesc is the grpc.ServiceDesc for LanternService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LanternService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graph.v1.LanternService",
	HandlerType: (*LanternServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Illuminate",
			Handler:    _LanternService_Illuminate_Handler,
		},
		{
			MethodName: "GetVertex",
			Handler:    _LanternService_GetVertex_Handler,
		},
		{
			MethodName: "GetVertices",
			Handler:    _LanternService_GetVertices_Handler,
		},
		{
			MethodName: "PutVertex",
			Handler:    _LanternService_PutVertex_Handler,
		},
		{
			MethodName: "PutVertices",
			Handler:    _LanternService_PutVertices_Handler,
		},
		{
			MethodName: "DeleteVertex",
			Handler:    _LanternService_DeleteVertex_Handler,
		},
		{
			MethodName: "DeleteVertices",
			Handler:    _LanternService_DeleteVertices_Handler,
		},
		{
			MethodName: "ScanVertices",
			Handler:    _LanternService_ScanVertices_Handler,
		},
		{
			MethodName: "CountVerticesByPrefix",
			Handler:    _LanternService_CountVerticesByPrefix_Handler,
		},
		{
			MethodName: "DeleteVerticesByPrefix",
			Handler:    _LanternService_DeleteVerticesByPrefix_Handler,
		},
		{
			MethodName: "GetEdge",
			Handler:    _LanternService_GetEdge_Handler,
		},
		{
			MethodName: "GetEdges",
			Handler:    _LanternService_GetEdges_Handler,
		},
		{
			MethodName: "AddEdge",
			Handler:    _LanternService_AddEdge_Handler,
		},
		{
			MethodName: "AddEdges",
			Handler:    _LanternService_AddEdges_Handler,
		},
		{
			MethodName: "PutEdge",
			Handler:    _LanternService_PutEdge_Handler,
		},
		{
			MethodName: "PutEdges",
			Handler:    _LanternService_PutEdges_Handler,
		},
		{
			MethodName: "DeleteEdge",
			Handler:    _LanternService_DeleteEdge_Handler,
		},
		{
			MethodName: "DeleteEdges",
			Handler:    _LanternService_DeleteEdges_Handler,
		},
		{
			MethodName: "ScanEdges",
			Handler:    _LanternService_ScanEdges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "graph/v1/graph.proto",
}
