// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/v1/replication.proto

package graphv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HLCTimestamp is the wire form of core/hlc.Timestamp. All replicated
// mutations carry one of these as their causal coordinate.
//
//	wall_ns: physical wall-clock component, nanoseconds since Unix epoch.
//	logical: per-tick logical counter, incremented on collision.
//	node_id: 16-byte origin node identifier (matches core/hlc.NodeID).
//
// The triple (wall_ns, logical, node_id) gives a strict total order; see
// docs/replication.md §5 and core/hlc/hlc.go.
type HLCTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WallNs        int64                  `protobuf:"varint,1,opt,name=wall_ns,json=wallNs,proto3" json:"wall_ns,omitempty"`
	Logical       uint32                 `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HLCTimestamp) Reset() {
	*x = HLCTimestamp{}
	mi := &file_graph_v1_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HLCTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLCTimestamp) ProtoMessage() {}

func (x *HLCTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLCTimestamp.ProtoReflect.Descriptor instead.
func (*HLCTimestamp) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{0}
}

func (x *HLCTimestamp) GetWallNs() int64 {
	if x != nil {
		return x.WallNs
	}
	return 0
}

func (x *HLCTimestamp) GetLogical() uint32 {
	if x != nil {
		return x.Logical
	}
	return 0
}

func (x *HLCTimestamp) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

// MutationOp is the discriminated payload of a single mutation. Each
// variant mirrors the request message of the corresponding write RPC so the
// existing server handlers can be reused verbatim when applying replicated
// mutations.
//
// Singular variants (PutVertex, AddEdge, ...) are retained as distinct
// arms — they are the wire form chosen by the client and round-tripping
// them faithfully simplifies CDC consumers that mirror RPC semantics.
type MutationOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*MutationOp_PutVertex
	//	*MutationOp_PutVertices
	//	*MutationOp_DeleteVertex
	//	*MutationOp_DeleteVertices
	//	*MutationOp_DeleteVerticesByPrefix
	//	*MutationOp_AddEdge
	//	*MutationOp_AddEdges
	//	*MutationOp_PutEdge
	//	*MutationOp_PutEdges
	//	*MutationOp_DeleteEdge
	//	*MutationOp_DeleteEdges
	Op            isMutationOp_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationOp) Reset() {
	*x = MutationOp{}
	mi := &file_graph_v1_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationOp) ProtoMessage() {}

func (x *MutationOp) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationOp.ProtoReflect.Descriptor instead.
func (*MutationOp) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{1}
}

func (x *MutationOp) GetOp() isMutationOp_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *MutationOp) GetPutVertex() *PutVertexRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_PutVertex); ok {
			return x.PutVertex
		}
	}
	return nil
}

func (x *MutationOp) GetPutVertices() *PutVerticesRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_PutVertices); ok {
			return x.PutVertices
		}
	}
	return nil
}

func (x *MutationOp) GetDeleteVertex() *DeleteVertexRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_DeleteVertex); ok {
			return x.DeleteVertex
		}
	}
	return nil
}

func (x *MutationOp) GetDeleteVertices() *DeleteVerticesRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_DeleteVertices); ok {
			return x.DeleteVertices
		}
	}
	return nil
}

func (x *MutationOp) GetDeleteVerticesByPrefix() *DeleteVerticesByPrefixRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_DeleteVerticesByPrefix); ok {
			return x.DeleteVerticesByPrefix
		}
	}
	return nil
}

func (x *MutationOp) GetAddEdge() *AddEdgeRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_AddEdge); ok {
			return x.AddEdge
		}
	}
	return nil
}

func (x *MutationOp) GetAddEdges() *AddEdgesRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_AddEdges); ok {
			return x.AddEdges
		}
	}
	return nil
}

func (x *MutationOp) GetPutEdge() *PutEdgeRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_PutEdge); ok {
			return x.PutEdge
		}
	}
	return nil
}

func (x *MutationOp) GetPutEdges() *PutEdgesRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_PutEdges); ok {
			return x.PutEdges
		}
	}
	return nil
}

func (x *MutationOp) GetDeleteEdge() *DeleteEdgeRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_DeleteEdge); ok {
			return x.DeleteEdge
		}
	}
	return nil
}

func (x *MutationOp) GetDeleteEdges() *DeleteEdgesRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_DeleteEdges); ok {
			return x.DeleteEdges
		}
	}
	return nil
}

type isMutationOp_Op interface {
	isMutationOp_Op()
}

type MutationOp_PutVertex struct {
	PutVertex *PutVertexRequest `protobuf:"bytes,1,opt,name=put_vertex,json=putVertex,proto3,oneof"`
}

type MutationOp_PutVertices struct {
	PutVertices *PutVerticesRequest `protobuf:"bytes,2,opt,name=put_vertices,json=putVertices,proto3,oneof"`
}

type MutationOp_DeleteVertex struct {
	DeleteVertex *DeleteVertexRequest `protobuf:"bytes,3,opt,name=delete_vertex,json=deleteVertex,proto3,oneof"`
}

type MutationOp_DeleteVertices struct {
	DeleteVertices *DeleteVerticesRequest `protobuf:"bytes,4,opt,name=delete_vertices,json=deleteVertices,proto3,oneof"`
}

type MutationOp_DeleteVerticesByPrefix struct {
	DeleteVerticesByPrefix *DeleteVerticesByPrefixRequest `protobuf:"bytes,5,opt,name=delete_vertices_by_prefix,json=deleteVerticesByPrefix,proto3,oneof"`
}

type MutationOp_AddEdge struct {
	AddEdge *AddEdgeRequest `protobuf:"bytes,6,opt,name=add_edge,json=addEdge,proto3,oneof"`
}

type MutationOp_AddEdges struct {
	AddEdges *AddEdgesRequest `protobuf:"bytes,7,opt,name=add_edges,json=addEdges,proto3,oneof"`
}

type MutationOp_PutEdge struct {
	PutEdge *PutEdgeRequest `protobuf:"bytes,8,opt,name=put_edge,json=putEdge,proto3,oneof"`
}

type MutationOp_PutEdges struct {
	PutEdges *PutEdgesRequest `protobuf:"bytes,9,opt,name=put_edges,json=putEdges,proto3,oneof"`
}

type MutationOp_DeleteEdge struct {
	DeleteEdge *DeleteEdgeRequest `protobuf:"bytes,10,opt,name=delete_edge,json=deleteEdge,proto3,oneof"`
}

type MutationOp_DeleteEdges struct {
	DeleteEdges *DeleteEdgesRequest `protobuf:"bytes,11,opt,name=delete_edges,json=deleteEdges,proto3,oneof"`
}

func (*MutationOp_PutVertex) isMutationOp_Op() {}

func (*MutationOp_PutVertices) isMutationOp_Op() {}

func (*MutationOp_DeleteVertex) isMutationOp_Op() {}

func (*MutationOp_DeleteVertices) isMutationOp_Op() {}

func (*MutationOp_DeleteVerticesByPrefix) isMutationOp_Op() {}

func (*MutationOp_AddEdge) isMutationOp_Op() {}

func (*MutationOp_AddEdges) isMutationOp_Op() {}

func (*MutationOp_PutEdge) isMutationOp_Op() {}

func (*MutationOp_PutEdges) isMutationOp_Op() {}

func (*MutationOp_DeleteEdge) isMutationOp_Op() {}

func (*MutationOp_DeleteEdges) isMutationOp_Op() {}

// Mutation is the unit of replication: a sequenced, HLC-stamped,
// origin-tagged graph write. `seq` is assigned by the originating node's
// mutation log (see core/mutationlog) and is strictly monotone within a
// single origin.
//
//	seq:    per-origin monotone sequence number, assigned at append time.
//	hlc:    causal timestamp stamped at append time.
//	origin: 16-byte node identifier of the node that first accepted the
//	        write; mirrors hlc.node_id but is kept as an explicit field so
//	        anti-entropy can index by origin without inspecting the HLC.
//	op:     the actual write payload (see MutationOp).
type Mutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Hlc           *HLCTimestamp          `protobuf:"bytes,2,opt,name=hlc,proto3" json:"hlc,omitempty"`
	Origin        []byte                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Op            *MutationOp            `protobuf:"bytes,4,opt,name=op,proto3" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_graph_v1_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{2}
}

func (x *Mutation) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Mutation) GetHlc() *HLCTimestamp {
	if x != nil {
		return x.Hlc
	}
	return nil
}

func (x *Mutation) GetOrigin() []byte {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *Mutation) GetOp() *MutationOp {
	if x != nil {
		return x.Op
	}
	return nil
}

// SubscribeRequest opens a stream of replicated mutations starting at
// `from_seq` (inclusive). The server replays any in-buffer entries with
// seq >= from_seq, then streams live mutations as they are appended.
//
// If `from_seq` is below the server's first available seq the call fails
// with FAILED_PRECONDITION and the caller must snapshot + resubscribe.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromSeq       uint64                 `protobuf:"varint,1,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_graph_v1_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

// SubscribeResponse carries one replicated mutation per message.
type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutation      *Mutation              `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_graph_v1_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeResponse) GetMutation() *Mutation {
	if x != nil {
		return x.Mutation
	}
	return nil
}

// SnapshotRequest opens a server-streaming snapshot of the entire live
// graph state at a single causal cutoff. The request body is intentionally
// empty in this phase (#184); future revisions may add prefix / shard
// filters without breaking the wire contract.
type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_graph_v1_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{5}
}

// SnapshotHeader is always the FIRST SnapshotEntry on the wire. It freezes
// the (seq, hlc) cutoff the server used to materialise the snapshot. A
// bootstrapping peer MUST persist (cutoff_seq, cutoff_hlc) before applying
// any payload entries and MUST resume `Subscribe` from cutoff_seq + 1 so
// the snapshot and the live tail stitch without gap or overlap.
type SnapshotHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CutoffSeq     uint64                 `protobuf:"varint,1,opt,name=cutoff_seq,json=cutoffSeq,proto3" json:"cutoff_seq,omitempty"`
	CutoffHlc     *HLCTimestamp          `protobuf:"bytes,2,opt,name=cutoff_hlc,json=cutoffHlc,proto3" json:"cutoff_hlc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotHeader) Reset() {
	*x = SnapshotHeader{}
	mi := &file_graph_v1_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotHeader) ProtoMessage() {}

func (x *SnapshotHeader) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotHeader.ProtoReflect.Descriptor instead.
func (*SnapshotHeader) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{6}
}

func (x *SnapshotHeader) GetCutoffSeq() uint64 {
	if x != nil {
		return x.CutoffSeq
	}
	return 0
}

func (x *SnapshotHeader) GetCutoffHlc() *HLCTimestamp {
	if x != nil {
		return x.CutoffHlc
	}
	return nil
}

// SnapshotFooter is always the LAST SnapshotEntry on the wire. It carries
// the running counts the server actually streamed so receivers can detect
// truncation (channel-close, send-error mid-stream) without re-walking
// their freshly-imported state.
type SnapshotFooter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VertexCount   uint64                 `protobuf:"varint,1,opt,name=vertex_count,json=vertexCount,proto3" json:"vertex_count,omitempty"`
	EdgeCount     uint64                 `protobuf:"varint,2,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotFooter) Reset() {
	*x = SnapshotFooter{}
	mi := &file_graph_v1_replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotFooter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotFooter) ProtoMessage() {}

func (x *SnapshotFooter) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotFooter.ProtoReflect.Descriptor instead.
func (*SnapshotFooter) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{7}
}

func (x *SnapshotFooter) GetVertexCount() uint64 {
	if x != nil {
		return x.VertexCount
	}
	return 0
}

func (x *SnapshotFooter) GetEdgeCount() uint64 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

// SnapshotVertex is the snapshot-time representation of a single live
// vertex. The HLC field carries the last LWW timestamp the source node
// recorded for the key (zero when the vertex has never been touched by a
// replicated Put, i.e. local-only writes); receivers feed it back through
// PutVertexWithExpirationHLC so subsequent older replays (#182) are
// correctly rejected.
type SnapshotVertex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vertex        *Vertex                `protobuf:"bytes,1,opt,name=vertex,proto3" json:"vertex,omitempty"`
	Hlc           *HLCTimestamp          `protobuf:"bytes,2,opt,name=hlc,proto3" json:"hlc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotVertex) Reset() {
	*x = SnapshotVertex{}
	mi := &file_graph_v1_replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotVertex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotVertex) ProtoMessage() {}

func (x *SnapshotVertex) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotVertex.ProtoReflect.Descriptor instead.
func (*SnapshotVertex) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{8}
}

func (x *SnapshotVertex) GetVertex() *Vertex {
	if x != nil {
		return x.Vertex
	}
	return nil
}

func (x *SnapshotVertex) GetHlc() *HLCTimestamp {
	if x != nil {
		return x.Hlc
	}
	return nil
}

// SnapshotEdgeContribution is one additive (or LWW-imported) entry inside
// an edge's weight bucket. Snapshot preserves the per-contribution
// decomposition so that the receiver's ContribID dedup (#182) keeps
// suppressing duplicates when peer-pump later re-delivers the same
// contribution from the live tail.
//
//	contrib_id: 24-byte ContribID; empty/zero when the contribution
//	            originated from a local non-replicated AddEdge and dedup
//	            is disabled (the legacy zero-id semantics).
type SnapshotEdgeContribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        float32                `protobuf:"fixed32,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	ContribId     []byte                 `protobuf:"bytes,3,opt,name=contrib_id,json=contribId,proto3" json:"contrib_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEdgeContribution) Reset() {
	*x = SnapshotEdgeContribution{}
	mi := &file_graph_v1_replication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEdgeContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEdgeContribution) ProtoMessage() {}

func (x *SnapshotEdgeContribution) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEdgeContribution.ProtoReflect.Descriptor instead.
func (*SnapshotEdgeContribution) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{9}
}

func (x *SnapshotEdgeContribution) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SnapshotEdgeContribution) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *SnapshotEdgeContribution) GetContribId() []byte {
	if x != nil {
		return x.ContribId
	}
	return nil
}

// SnapshotEdge is the snapshot-time representation of a single live edge.
// `hlc` carries the bucket's lastHLC (the most recent Put-LWW position;
// zero when no LWW write has happened) so receivers can apply each
// contribution via AddEdgeWithExpirationContribHLC with the right LWW
// floor, keeping ContribID dedup intact.
type SnapshotEdge struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Tail          string                      `protobuf:"bytes,1,opt,name=tail,proto3" json:"tail,omitempty"`
	Head          string                      `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Hlc           *HLCTimestamp               `protobuf:"bytes,3,opt,name=hlc,proto3" json:"hlc,omitempty"`
	Contributions []*SnapshotEdgeContribution `protobuf:"bytes,4,rep,name=contributions,proto3" json:"contributions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEdge) Reset() {
	*x = SnapshotEdge{}
	mi := &file_graph_v1_replication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEdge) ProtoMessage() {}

func (x *SnapshotEdge) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEdge.ProtoReflect.Descriptor instead.
func (*SnapshotEdge) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{10}
}

func (x *SnapshotEdge) GetTail() string {
	if x != nil {
		return x.Tail
	}
	return ""
}

func (x *SnapshotEdge) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *SnapshotEdge) GetHlc() *HLCTimestamp {
	if x != nil {
		return x.Hlc
	}
	return nil
}

func (x *SnapshotEdge) GetContributions() []*SnapshotEdgeContribution {
	if x != nil {
		return x.Contributions
	}
	return nil
}

// SnapshotEntry is the union type streamed from `rpc Snapshot`. The frame
// order is always: exactly one SnapshotHeader, then zero or more
// SnapshotVertex frames, then zero or more SnapshotEdge frames, then
// exactly one SnapshotFooter. Receivers SHOULD treat any other order as a
// protocol violation.
type SnapshotEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entry:
	//
	//	*SnapshotEntry_Header
	//	*SnapshotEntry_Vertex
	//	*SnapshotEntry_Edge
	//	*SnapshotEntry_Footer
	Entry         isSnapshotEntry_Entry `protobuf_oneof:"entry"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEntry) Reset() {
	*x = SnapshotEntry{}
	mi := &file_graph_v1_replication_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEntry) ProtoMessage() {}

func (x *SnapshotEntry) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEntry.ProtoReflect.Descriptor instead.
func (*SnapshotEntry) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{11}
}

func (x *SnapshotEntry) GetEntry() isSnapshotEntry_Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *SnapshotEntry) GetHeader() *SnapshotHeader {
	if x != nil {
		if x, ok := x.Entry.(*SnapshotEntry_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *SnapshotEntry) GetVertex() *SnapshotVertex {
	if x != nil {
		if x, ok := x.Entry.(*SnapshotEntry_Vertex); ok {
			return x.Vertex
		}
	}
	return nil
}

func (x *SnapshotEntry) GetEdge() *SnapshotEdge {
	if x != nil {
		if x, ok := x.Entry.(*SnapshotEntry_Edge); ok {
			return x.Edge
		}
	}
	return nil
}

func (x *SnapshotEntry) GetFooter() *SnapshotFooter {
	if x != nil {
		if x, ok := x.Entry.(*SnapshotEntry_Footer); ok {
			return x.Footer
		}
	}
	return nil
}

type isSnapshotEntry_Entry interface {
	isSnapshotEntry_Entry()
}

type SnapshotEntry_Header struct {
	Header *SnapshotHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type SnapshotEntry_Vertex struct {
	Vertex *SnapshotVertex `protobuf:"bytes,2,opt,name=vertex,proto3,oneof"`
}

type SnapshotEntry_Edge struct {
	Edge *SnapshotEdge `protobuf:"bytes,3,opt,name=edge,proto3,oneof"`
}

type SnapshotEntry_Footer struct {
	Footer *SnapshotFooter `protobuf:"bytes,4,opt,name=footer,proto3,oneof"`
}

func (*SnapshotEntry_Header) isSnapshotEntry_Entry() {}

func (*SnapshotEntry_Vertex) isSnapshotEntry_Entry() {}

func (*SnapshotEntry_Edge) isSnapshotEntry_Entry() {}

func (*SnapshotEntry_Footer) isSnapshotEntry_Entry() {}

var File_graph_v1_replication_proto protoreflect.FileDescriptor

const file_graph_v1_replication_proto_rawDesc = "" +
	"\n" +
	"\x1agraph/v1/replication.proto\x12\bgraph.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14graph/v1/graph.proto\"Z\n" +
	"\fHLCTimestamp\x12\x17\n" +
	"\awall_ns\x18\x01 \x01(\x03R\x06wallNs\x12\x18\n" +
	"\alogical\x18\x02 \x01(\rR\alogical\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\fR\x06nodeId\"\xef\x05\n" +
	"\n" +
	"MutationOp\x12;\n" +
	"\n" +
	"put_vertex\x18\x01 \x01(\v2\x1a.graph.v1.PutVertexRequestH\x00R\tputVertex\x12A\n" +
	"\fput_vertices\x18\x02 \x01(\v2\x1c.graph.v1.PutVerticesRequestH\x00R\vputVertices\x12D\n" +
	"\rdelete_vertex\x18\x03 \x01(\v2\x1d.graph.v1.DeleteVertexRequestH\x00R\fdeleteVertex\x12J\n" +
	"\x0fdelete_vertices\x18\x04 \x01(\v2\x1f.graph.v1.DeleteVerticesRequestH\x00R\x0edeleteVertices\x12d\n" +
	"\x19delete_vertices_by_prefix\x18\x05 \x01(\v2'.graph.v1.DeleteVerticesByPrefixRequestH\x00R\x16deleteVerticesByPrefix\x125\n" +
	"\badd_edge\x18\x06 \x01(\v2\x18.graph.v1.AddEdgeRequestH\x00R\aaddEdge\x128\n" +
	"\tadd_edges\x18\a \x01(\v2\x19.graph.v1.AddEdgesRequestH\x00R\baddEdges\x125\n" +
	"\bput_edge\x18\b \x01(\v2\x18.graph.v1.PutEdgeRequestH\x00R\aputEdge\x128\n" +
	"\tput_edges\x18\t \x01(\v2\x19.graph.v1.PutEdgesRequestH\x00R\bputEdges\x12>\n" +
	"\vdelete_edge\x18\n" +
	" \x01(\v2\x1b.graph.v1.DeleteEdgeRequestH\x00R\n" +
	"deleteEdge\x12A\n" +
	"\fdelete_edges\x18\v \x01(\v2\x1c.graph.v1.DeleteEdgesRequestH\x00R\vdeleteEdgesB\x04\n" +
	"\x02op\"\x84\x01\n" +
	"\bMutation\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12(\n" +
	"\x03hlc\x18\x02 \x01(\v2\x16.graph.v1.HLCTimestampR\x03hlc\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\fR\x06origin\x12$\n" +
	"\x02op\x18\x04 \x01(\v2\x14.graph.v1.MutationOpR\x02op\"-\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\bfrom_seq\x18\x01 \x01(\x04R\afromSeq\"C\n" +
	"\x11SubscribeResponse\x12.\n" +
	"\bmutation\x18\x01 \x01(\v2\x12.graph.v1.MutationR\bmutation\"\x11\n" +
	"\x0fSnapshotRequest\"f\n" +
	"\x0eSnapshotHeader\x12\x1d\n" +
	"\n" +
	"cutoff_seq\x18\x01 \x01(\x04R\tcutoffSeq\x125\n" +
	"\n" +
	"cutoff_hlc\x18\x02 \x01(\v2\x16.graph.v1.HLCTimestampR\tcutoffHlc\"R\n" +
	"\x0eSnapshotFooter\x12!\n" +
	"\fvertex_count\x18\x01 \x01(\x04R\vvertexCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x02 \x01(\x04R\tedgeCount\"d\n" +
	"\x0eSnapshotVertex\x12(\n" +
	"\x06vertex\x18\x01 \x01(\v2\x10.graph.v1.VertexR\x06vertex\x12(\n" +
	"\x03hlc\x18\x02 \x01(\v2\x16.graph.v1.HLCTimestampR\x03hlc\"\x8d\x01\n" +
	"\x18SnapshotEdgeContribution\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x02R\x06weight\x12:\n" +
	"\n" +
	"expiration\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\x12\x1d\n" +
	"\n" +
	"contrib_id\x18\x03 \x01(\fR\tcontribId\"\xaa\x01\n" +
	"\fSnapshotEdge\x12\x12\n" +
	"\x04tail\x18\x01 \x01(\tR\x04tail\x12\x12\n" +
	"\x04head\x18\x02 \x01(\tR\x04head\x12(\n" +
	"\x03hlc\x18\x03 \x01(\v2\x16.graph.v1.HLCTimestampR\x03hlc\x12H\n" +
	"\rcontributions\x18\x04 \x03(\v2\".graph.v1.SnapshotEdgeContributionR\rcontributions\"\xe2\x01\n" +
	"\rSnapshotEntry\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x18.graph.v1.SnapshotHeaderH\x00R\x06header\x122\n" +
	"\x06vertex\x18\x02 \x01(\v2\x18.graph.v1.SnapshotVertexH\x00R\x06vertex\x12,\n" +
	"\x04edge\x18\x03 \x01(\v2\x16.graph.v1.SnapshotEdgeH\x00R\x04edge\x122\n" +
	"\x06footer\x18\x04 \x01(\v2\x18.graph.v1.SnapshotFooterH\x00R\x06footerB\a\n" +
	"\x05entry2\xa5\x01\n" +
	"\x19LanternReplicationService\x12F\n" +
	"\tSubscribe\x12\x1a.graph.v1.SubscribeRequest\x1a\x1b.graph.v1.SubscribeResponse0\x01\x12@\n" +
	"\bSnapshot\x12\x19.graph.v1.SnapshotRequest\x1a\x17.graph.v1.SnapshotEntry0\x01B\x96\x01\n" +
	"\fcom.graph.v1B\x10ReplicationProtoP\x01Z3github.com/anaregdesign/lantern/pb/graph/v1;graphv1\xa2\x02\x03GXX\xaa\x02\bGraph.V1\xca\x02\bGraph\\V1\xe2\x02\x14Graph\\V1\\GPBMetadata\xea\x02\tGraph::V1b\x06proto3"

var (
	file_graph_v1_replication_proto_rawDescOnce sync.Once
	file_graph_v1_replication_proto_rawDescData []byte
)

func file_graph_v1_replication_proto_rawDescGZIP() []byte {
	file_graph_v1_replication_proto_rawDescOnce.Do(func() {
		file_graph_v1_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_v1_replication_proto_rawDesc), len(file_graph_v1_replication_proto_rawDesc)))
	})
	return file_graph_v1_replication_proto_rawDescData
}

var file_graph_v1_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_graph_v1_replication_proto_goTypes = []any{
	(*HLCTimestamp)(nil),                  // 0: graph.v1.HLCTimestamp
	(*MutationOp)(nil),                    // 1: graph.v1.MutationOp
	(*Mutation)(nil),                      // 2: graph.v1.Mutation
	(*SubscribeRequest)(nil),              // 3: graph.v1.SubscribeRequest
	(*SubscribeResponse)(nil),             // 4: graph.v1.SubscribeResponse
	(*SnapshotRequest)(nil),               // 5: graph.v1.SnapshotRequest
	(*SnapshotHeader)(nil),                // 6: graph.v1.SnapshotHeader
	(*SnapshotFooter)(nil),                // 7: graph.v1.SnapshotFooter
	(*SnapshotVertex)(nil),                // 8: graph.v1.SnapshotVertex
	(*SnapshotEdgeContribution)(nil),      // 9: graph.v1.SnapshotEdgeContribution
	(*SnapshotEdge)(nil),                  // 10: graph.v1.SnapshotEdge
	(*SnapshotEntry)(nil),                 // 11: graph.v1.SnapshotEntry
	(*PutVertexRequest)(nil),              // 12: graph.v1.PutVertexRequest
	(*PutVerticesRequest)(nil),            // 13: graph.v1.PutVerticesRequest
	(*DeleteVertexRequest)(nil),           // 14: graph.v1.DeleteVertexRequest
	(*DeleteVerticesRequest)(nil),         // 15: graph.v1.DeleteVerticesRequest
	(*DeleteVerticesByPrefixRequest)(nil), // 16: graph.v1.DeleteVerticesByPrefixRequest
	(*AddEdgeRequest)(nil),                // 17: graph.v1.AddEdgeRequest
	(*AddEdgesRequest)(nil),               // 18: graph.v1.AddEdgesRequest
	(*PutEdgeRequest)(nil),                // 19: graph.v1.PutEdgeRequest
	(*PutEdgesRequest)(nil),               // 20: graph.v1.PutEdgesRequest
	(*DeleteEdgeRequest)(nil),             // 21: graph.v1.DeleteEdgeRequest
	(*DeleteEdgesRequest)(nil),            // 22: graph.v1.DeleteEdgesRequest
	(*Vertex)(nil),                        // 23: graph.v1.Vertex
	(*timestamppb.Timestamp)(nil),         // 24: google.protobuf.Timestamp
}
var file_graph_v1_replication_proto_depIdxs = []int32{
	12, // 0: graph.v1.MutationOp.put_vertex:type_name -> graph.v1.PutVertexRequest
	13, // 1: graph.v1.MutationOp.put_vertices:type_name -> graph.v1.PutVerticesRequest
	14, // 2: graph.v1.MutationOp.delete_vertex:type_name -> graph.v1.DeleteVertexRequest
	15, // 3: graph.v1.MutationOp.delete_vertices:type_name -> graph.v1.DeleteVerticesRequest
	16, // 4: graph.v1.MutationOp.delete_vertices_by_prefix:type_name -> graph.v1.DeleteVerticesByPrefixRequest
	17, // 5: graph.v1.MutationOp.add_edge:type_name -> graph.v1.AddEdgeRequest
	18, // 6: graph.v1.MutationOp.add_edges:type_name -> graph.v1.AddEdgesRequest
	19, // 7: graph.v1.MutationOp.put_edge:type_name -> graph.v1.PutEdgeRequest
	20, // 8: graph.v1.MutationOp.put_edges:type_name -> graph.v1.PutEdgesRequest
	21, // 9: graph.v1.MutationOp.delete_edge:type_name -> graph.v1.DeleteEdgeRequest
	22, // 10: graph.v1.MutationOp.delete_edges:type_name -> graph.v1.DeleteEdgesRequest
	0,  // 11: graph.v1.Mutation.hlc:type_name -> graph.v1.HLCTimestamp
	1,  // 12: graph.v1.Mutation.op:type_name -> graph.v1.MutationOp
	2,  // 13: graph.v1.SubscribeResponse.mutation:type_name -> graph.v1.Mutation
	0,  // 14: graph.v1.SnapshotHeader.cutoff_hlc:type_name -> graph.v1.HLCTimestamp
	23, // 15: graph.v1.SnapshotVertex.vertex:type_name -> graph.v1.Vertex
	0,  // 16: graph.v1.SnapshotVertex.hlc:type_name -> graph.v1.HLCTimestamp
	24, // 17: graph.v1.SnapshotEdgeContribution.expiration:type_name -> google.protobuf.Timestamp
	0,  // 18: graph.v1.SnapshotEdge.hlc:type_name -> graph.v1.HLCTimestamp
	9,  // 19: graph.v1.SnapshotEdge.contributions:type_name -> graph.v1.SnapshotEdgeContribution
	6,  // 20: graph.v1.SnapshotEntry.header:type_name -> graph.v1.SnapshotHeader
	8,  // 21: graph.v1.SnapshotEntry.vertex:type_name -> graph.v1.SnapshotVertex
	10, // 22: graph.v1.SnapshotEntry.edge:type_name -> graph.v1.SnapshotEdge
	7,  // 23: graph.v1.SnapshotEntry.footer:type_name -> graph.v1.SnapshotFooter
	3,  // 24: graph.v1.LanternReplicationService.Subscribe:input_type -> graph.v1.SubscribeRequest
	5,  // 25: graph.v1.LanternReplicationService.Snapshot:input_type -> graph.v1.SnapshotRequest
	4,  // 26: graph.v1.LanternReplicationService.Subscribe:output_type -> graph.v1.SubscribeResponse
	11, // 27: graph.v1.LanternReplicationService.Snapshot:output_type -> graph.v1.SnapshotEntry
	26, // [26:28] is the sub-list for method output_type
	24, // [24:26] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_graph_v1_replication_proto_init() }
func file_graph_v1_replication_proto_init() {
	if File_graph_v1_replication_proto != nil {
		return
	}
	file_graph_v1_graph_proto_init()
	file_graph_v1_replication_proto_msgTypes[1].OneofWrappers = []any{
		(*MutationOp_PutVertex)(nil),
		(*MutationOp_PutVertices)(nil),
		(*MutationOp_DeleteVertex)(nil),
		(*MutationOp_DeleteVertices)(nil),
		(*MutationOp_DeleteVerticesByPrefix)(nil),
		(*MutationOp_AddEdge)(nil),
		(*MutationOp_AddEdges)(nil),
		(*MutationOp_PutEdge)(nil),
		(*MutationOp_PutEdges)(nil),
		(*MutationOp_DeleteEdge)(nil),
		(*MutationOp_DeleteEdges)(nil),
	}
	file_graph_v1_replication_proto_msgTypes[11].OneofWrappers = []any{
		(*SnapshotEntry_Header)(nil),
		(*SnapshotEntry_Vertex)(nil),
		(*SnapshotEntry_Edge)(nil),
		(*SnapshotEntry_Footer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_v1_replication_proto_rawDesc), len(file_graph_v1_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_v1_replication_proto_goTypes,
		DependencyIndexes: file_graph_v1_replication_proto_depIdxs,
		MessageInfos:      file_graph_v1_replication_proto_msgTypes,
	}.Build()
	File_graph_v1_replication_proto = out.File
	file_graph_v1_replication_proto_goTypes = nil
	file_graph_v1_replication_proto_depIdxs = nil
}
