// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: graph/v1/replication.proto

package graphv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HLCTimestamp is the wire form of core/hlc.Timestamp. All replicated
// mutations carry one of these as their causal coordinate.
//
//	wall_ns: physical wall-clock component, nanoseconds since Unix epoch.
//	logical: per-tick logical counter, incremented on collision.
//	node_id: 16-byte origin node identifier (matches core/hlc.NodeID).
//
// The triple (wall_ns, logical, node_id) gives a strict total order; see
// docs/replication.md §5 and core/hlc/hlc.go.
type HLCTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WallNs        int64                  `protobuf:"varint,1,opt,name=wall_ns,json=wallNs,proto3" json:"wall_ns,omitempty"`
	Logical       uint32                 `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HLCTimestamp) Reset() {
	*x = HLCTimestamp{}
	mi := &file_graph_v1_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HLCTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLCTimestamp) ProtoMessage() {}

func (x *HLCTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLCTimestamp.ProtoReflect.Descriptor instead.
func (*HLCTimestamp) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{0}
}

func (x *HLCTimestamp) GetWallNs() int64 {
	if x != nil {
		return x.WallNs
	}
	return 0
}

func (x *HLCTimestamp) GetLogical() uint32 {
	if x != nil {
		return x.Logical
	}
	return 0
}

func (x *HLCTimestamp) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

// MutationOp is the discriminated payload of a single mutation. Each
// variant mirrors the request message of the corresponding write RPC so the
// existing server handlers can be reused verbatim when applying replicated
// mutations.
//
// Singular variants (PutVertex, AddEdge, ...) are retained as distinct
// arms — they are the wire form chosen by the client and round-tripping
// them faithfully simplifies CDC consumers that mirror RPC semantics.
type MutationOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*MutationOp_PutVertex
	//	*MutationOp_PutVertices
	//	*MutationOp_DeleteVertex
	//	*MutationOp_DeleteVertices
	//	*MutationOp_DeleteVerticesByPrefix
	//	*MutationOp_AddEdge
	//	*MutationOp_AddEdges
	//	*MutationOp_PutEdge
	//	*MutationOp_PutEdges
	//	*MutationOp_DeleteEdge
	//	*MutationOp_DeleteEdges
	Op            isMutationOp_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationOp) Reset() {
	*x = MutationOp{}
	mi := &file_graph_v1_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationOp) ProtoMessage() {}

func (x *MutationOp) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationOp.ProtoReflect.Descriptor instead.
func (*MutationOp) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{1}
}

func (x *MutationOp) GetOp() isMutationOp_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *MutationOp) GetPutVertex() *PutVertexRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_PutVertex); ok {
			return x.PutVertex
		}
	}
	return nil
}

func (x *MutationOp) GetPutVertices() *PutVerticesRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_PutVertices); ok {
			return x.PutVertices
		}
	}
	return nil
}

func (x *MutationOp) GetDeleteVertex() *DeleteVertexRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_DeleteVertex); ok {
			return x.DeleteVertex
		}
	}
	return nil
}

func (x *MutationOp) GetDeleteVertices() *DeleteVerticesRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_DeleteVertices); ok {
			return x.DeleteVertices
		}
	}
	return nil
}

func (x *MutationOp) GetDeleteVerticesByPrefix() *DeleteVerticesByPrefixRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_DeleteVerticesByPrefix); ok {
			return x.DeleteVerticesByPrefix
		}
	}
	return nil
}

func (x *MutationOp) GetAddEdge() *AddEdgeRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_AddEdge); ok {
			return x.AddEdge
		}
	}
	return nil
}

func (x *MutationOp) GetAddEdges() *AddEdgesRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_AddEdges); ok {
			return x.AddEdges
		}
	}
	return nil
}

func (x *MutationOp) GetPutEdge() *PutEdgeRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_PutEdge); ok {
			return x.PutEdge
		}
	}
	return nil
}

func (x *MutationOp) GetPutEdges() *PutEdgesRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_PutEdges); ok {
			return x.PutEdges
		}
	}
	return nil
}

func (x *MutationOp) GetDeleteEdge() *DeleteEdgeRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_DeleteEdge); ok {
			return x.DeleteEdge
		}
	}
	return nil
}

func (x *MutationOp) GetDeleteEdges() *DeleteEdgesRequest {
	if x != nil {
		if x, ok := x.Op.(*MutationOp_DeleteEdges); ok {
			return x.DeleteEdges
		}
	}
	return nil
}

type isMutationOp_Op interface {
	isMutationOp_Op()
}

type MutationOp_PutVertex struct {
	PutVertex *PutVertexRequest `protobuf:"bytes,1,opt,name=put_vertex,json=putVertex,proto3,oneof"`
}

type MutationOp_PutVertices struct {
	PutVertices *PutVerticesRequest `protobuf:"bytes,2,opt,name=put_vertices,json=putVertices,proto3,oneof"`
}

type MutationOp_DeleteVertex struct {
	DeleteVertex *DeleteVertexRequest `protobuf:"bytes,3,opt,name=delete_vertex,json=deleteVertex,proto3,oneof"`
}

type MutationOp_DeleteVertices struct {
	DeleteVertices *DeleteVerticesRequest `protobuf:"bytes,4,opt,name=delete_vertices,json=deleteVertices,proto3,oneof"`
}

type MutationOp_DeleteVerticesByPrefix struct {
	DeleteVerticesByPrefix *DeleteVerticesByPrefixRequest `protobuf:"bytes,5,opt,name=delete_vertices_by_prefix,json=deleteVerticesByPrefix,proto3,oneof"`
}

type MutationOp_AddEdge struct {
	AddEdge *AddEdgeRequest `protobuf:"bytes,6,opt,name=add_edge,json=addEdge,proto3,oneof"`
}

type MutationOp_AddEdges struct {
	AddEdges *AddEdgesRequest `protobuf:"bytes,7,opt,name=add_edges,json=addEdges,proto3,oneof"`
}

type MutationOp_PutEdge struct {
	PutEdge *PutEdgeRequest `protobuf:"bytes,8,opt,name=put_edge,json=putEdge,proto3,oneof"`
}

type MutationOp_PutEdges struct {
	PutEdges *PutEdgesRequest `protobuf:"bytes,9,opt,name=put_edges,json=putEdges,proto3,oneof"`
}

type MutationOp_DeleteEdge struct {
	DeleteEdge *DeleteEdgeRequest `protobuf:"bytes,10,opt,name=delete_edge,json=deleteEdge,proto3,oneof"`
}

type MutationOp_DeleteEdges struct {
	DeleteEdges *DeleteEdgesRequest `protobuf:"bytes,11,opt,name=delete_edges,json=deleteEdges,proto3,oneof"`
}

func (*MutationOp_PutVertex) isMutationOp_Op() {}

func (*MutationOp_PutVertices) isMutationOp_Op() {}

func (*MutationOp_DeleteVertex) isMutationOp_Op() {}

func (*MutationOp_DeleteVertices) isMutationOp_Op() {}

func (*MutationOp_DeleteVerticesByPrefix) isMutationOp_Op() {}

func (*MutationOp_AddEdge) isMutationOp_Op() {}

func (*MutationOp_AddEdges) isMutationOp_Op() {}

func (*MutationOp_PutEdge) isMutationOp_Op() {}

func (*MutationOp_PutEdges) isMutationOp_Op() {}

func (*MutationOp_DeleteEdge) isMutationOp_Op() {}

func (*MutationOp_DeleteEdges) isMutationOp_Op() {}

// Mutation is the unit of replication: a sequenced, HLC-stamped,
// origin-tagged graph write. `seq` is assigned by the originating node's
// mutation log (see core/mutationlog) and is strictly monotone within a
// single origin.
//
//	seq:    per-origin monotone sequence number, assigned at append time.
//	hlc:    causal timestamp stamped at append time.
//	origin: 16-byte node identifier of the node that first accepted the
//	        write; mirrors hlc.node_id but is kept as an explicit field so
//	        anti-entropy can index by origin without inspecting the HLC.
//	op:     the actual write payload (see MutationOp).
type Mutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Hlc           *HLCTimestamp          `protobuf:"bytes,2,opt,name=hlc,proto3" json:"hlc,omitempty"`
	Origin        []byte                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Op            *MutationOp            `protobuf:"bytes,4,opt,name=op,proto3" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_graph_v1_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{2}
}

func (x *Mutation) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Mutation) GetHlc() *HLCTimestamp {
	if x != nil {
		return x.Hlc
	}
	return nil
}

func (x *Mutation) GetOrigin() []byte {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *Mutation) GetOp() *MutationOp {
	if x != nil {
		return x.Op
	}
	return nil
}

// SubscribeRequest opens a stream of replicated mutations starting at
// `from_seq` (inclusive). The server replays any in-buffer entries with
// seq >= from_seq, then streams live mutations as they are appended.
//
// If `from_seq` is below the server's first available seq the call fails
// with FAILED_PRECONDITION and the caller must snapshot + resubscribe.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromSeq       uint64                 `protobuf:"varint,1,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_graph_v1_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

// SubscribeResponse carries one replicated mutation per message.
type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutation      *Mutation              `protobuf:"bytes,1,opt,name=mutation,proto3" json:"mutation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_graph_v1_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_graph_v1_replication_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeResponse) GetMutation() *Mutation {
	if x != nil {
		return x.Mutation
	}
	return nil
}

var File_graph_v1_replication_proto protoreflect.FileDescriptor

const file_graph_v1_replication_proto_rawDesc = "" +
	"\n" +
	"\x1agraph/v1/replication.proto\x12\bgraph.v1\x1a\x14graph/v1/graph.proto\"Z\n" +
	"\fHLCTimestamp\x12\x17\n" +
	"\awall_ns\x18\x01 \x01(\x03R\x06wallNs\x12\x18\n" +
	"\alogical\x18\x02 \x01(\rR\alogical\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\fR\x06nodeId\"\xef\x05\n" +
	"\n" +
	"MutationOp\x12;\n" +
	"\n" +
	"put_vertex\x18\x01 \x01(\v2\x1a.graph.v1.PutVertexRequestH\x00R\tputVertex\x12A\n" +
	"\fput_vertices\x18\x02 \x01(\v2\x1c.graph.v1.PutVerticesRequestH\x00R\vputVertices\x12D\n" +
	"\rdelete_vertex\x18\x03 \x01(\v2\x1d.graph.v1.DeleteVertexRequestH\x00R\fdeleteVertex\x12J\n" +
	"\x0fdelete_vertices\x18\x04 \x01(\v2\x1f.graph.v1.DeleteVerticesRequestH\x00R\x0edeleteVertices\x12d\n" +
	"\x19delete_vertices_by_prefix\x18\x05 \x01(\v2'.graph.v1.DeleteVerticesByPrefixRequestH\x00R\x16deleteVerticesByPrefix\x125\n" +
	"\badd_edge\x18\x06 \x01(\v2\x18.graph.v1.AddEdgeRequestH\x00R\aaddEdge\x128\n" +
	"\tadd_edges\x18\a \x01(\v2\x19.graph.v1.AddEdgesRequestH\x00R\baddEdges\x125\n" +
	"\bput_edge\x18\b \x01(\v2\x18.graph.v1.PutEdgeRequestH\x00R\aputEdge\x128\n" +
	"\tput_edges\x18\t \x01(\v2\x19.graph.v1.PutEdgesRequestH\x00R\bputEdges\x12>\n" +
	"\vdelete_edge\x18\n" +
	" \x01(\v2\x1b.graph.v1.DeleteEdgeRequestH\x00R\n" +
	"deleteEdge\x12A\n" +
	"\fdelete_edges\x18\v \x01(\v2\x1c.graph.v1.DeleteEdgesRequestH\x00R\vdeleteEdgesB\x04\n" +
	"\x02op\"\x84\x01\n" +
	"\bMutation\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12(\n" +
	"\x03hlc\x18\x02 \x01(\v2\x16.graph.v1.HLCTimestampR\x03hlc\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\fR\x06origin\x12$\n" +
	"\x02op\x18\x04 \x01(\v2\x14.graph.v1.MutationOpR\x02op\"-\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\bfrom_seq\x18\x01 \x01(\x04R\afromSeq\"C\n" +
	"\x11SubscribeResponse\x12.\n" +
	"\bmutation\x18\x01 \x01(\v2\x12.graph.v1.MutationR\bmutation2c\n" +
	"\x19LanternReplicationService\x12F\n" +
	"\tSubscribe\x12\x1a.graph.v1.SubscribeRequest\x1a\x1b.graph.v1.SubscribeResponse0\x01B\x96\x01\n" +
	"\fcom.graph.v1B\x10ReplicationProtoP\x01Z3github.com/anaregdesign/lantern/pb/graph/v1;graphv1\xa2\x02\x03GXX\xaa\x02\bGraph.V1\xca\x02\bGraph\\V1\xe2\x02\x14Graph\\V1\\GPBMetadata\xea\x02\tGraph::V1b\x06proto3"

var (
	file_graph_v1_replication_proto_rawDescOnce sync.Once
	file_graph_v1_replication_proto_rawDescData []byte
)

func file_graph_v1_replication_proto_rawDescGZIP() []byte {
	file_graph_v1_replication_proto_rawDescOnce.Do(func() {
		file_graph_v1_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_v1_replication_proto_rawDesc), len(file_graph_v1_replication_proto_rawDesc)))
	})
	return file_graph_v1_replication_proto_rawDescData
}

var file_graph_v1_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_graph_v1_replication_proto_goTypes = []any{
	(*HLCTimestamp)(nil),                  // 0: graph.v1.HLCTimestamp
	(*MutationOp)(nil),                    // 1: graph.v1.MutationOp
	(*Mutation)(nil),                      // 2: graph.v1.Mutation
	(*SubscribeRequest)(nil),              // 3: graph.v1.SubscribeRequest
	(*SubscribeResponse)(nil),             // 4: graph.v1.SubscribeResponse
	(*PutVertexRequest)(nil),              // 5: graph.v1.PutVertexRequest
	(*PutVerticesRequest)(nil),            // 6: graph.v1.PutVerticesRequest
	(*DeleteVertexRequest)(nil),           // 7: graph.v1.DeleteVertexRequest
	(*DeleteVerticesRequest)(nil),         // 8: graph.v1.DeleteVerticesRequest
	(*DeleteVerticesByPrefixRequest)(nil), // 9: graph.v1.DeleteVerticesByPrefixRequest
	(*AddEdgeRequest)(nil),                // 10: graph.v1.AddEdgeRequest
	(*AddEdgesRequest)(nil),               // 11: graph.v1.AddEdgesRequest
	(*PutEdgeRequest)(nil),                // 12: graph.v1.PutEdgeRequest
	(*PutEdgesRequest)(nil),               // 13: graph.v1.PutEdgesRequest
	(*DeleteEdgeRequest)(nil),             // 14: graph.v1.DeleteEdgeRequest
	(*DeleteEdgesRequest)(nil),            // 15: graph.v1.DeleteEdgesRequest
}
var file_graph_v1_replication_proto_depIdxs = []int32{
	5,  // 0: graph.v1.MutationOp.put_vertex:type_name -> graph.v1.PutVertexRequest
	6,  // 1: graph.v1.MutationOp.put_vertices:type_name -> graph.v1.PutVerticesRequest
	7,  // 2: graph.v1.MutationOp.delete_vertex:type_name -> graph.v1.DeleteVertexRequest
	8,  // 3: graph.v1.MutationOp.delete_vertices:type_name -> graph.v1.DeleteVerticesRequest
	9,  // 4: graph.v1.MutationOp.delete_vertices_by_prefix:type_name -> graph.v1.DeleteVerticesByPrefixRequest
	10, // 5: graph.v1.MutationOp.add_edge:type_name -> graph.v1.AddEdgeRequest
	11, // 6: graph.v1.MutationOp.add_edges:type_name -> graph.v1.AddEdgesRequest
	12, // 7: graph.v1.MutationOp.put_edge:type_name -> graph.v1.PutEdgeRequest
	13, // 8: graph.v1.MutationOp.put_edges:type_name -> graph.v1.PutEdgesRequest
	14, // 9: graph.v1.MutationOp.delete_edge:type_name -> graph.v1.DeleteEdgeRequest
	15, // 10: graph.v1.MutationOp.delete_edges:type_name -> graph.v1.DeleteEdgesRequest
	0,  // 11: graph.v1.Mutation.hlc:type_name -> graph.v1.HLCTimestamp
	1,  // 12: graph.v1.Mutation.op:type_name -> graph.v1.MutationOp
	2,  // 13: graph.v1.SubscribeResponse.mutation:type_name -> graph.v1.Mutation
	3,  // 14: graph.v1.LanternReplicationService.Subscribe:input_type -> graph.v1.SubscribeRequest
	4,  // 15: graph.v1.LanternReplicationService.Subscribe:output_type -> graph.v1.SubscribeResponse
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_graph_v1_replication_proto_init() }
func file_graph_v1_replication_proto_init() {
	if File_graph_v1_replication_proto != nil {
		return
	}
	file_graph_v1_graph_proto_init()
	file_graph_v1_replication_proto_msgTypes[1].OneofWrappers = []any{
		(*MutationOp_PutVertex)(nil),
		(*MutationOp_PutVertices)(nil),
		(*MutationOp_DeleteVertex)(nil),
		(*MutationOp_DeleteVertices)(nil),
		(*MutationOp_DeleteVerticesByPrefix)(nil),
		(*MutationOp_AddEdge)(nil),
		(*MutationOp_AddEdges)(nil),
		(*MutationOp_PutEdge)(nil),
		(*MutationOp_PutEdges)(nil),
		(*MutationOp_DeleteEdge)(nil),
		(*MutationOp_DeleteEdges)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_v1_replication_proto_rawDesc), len(file_graph_v1_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_v1_replication_proto_goTypes,
		DependencyIndexes: file_graph_v1_replication_proto_depIdxs,
		MessageInfos:      file_graph_v1_replication_proto_msgTypes,
	}.Build()
	File_graph_v1_replication_proto = out.File
	file_graph_v1_replication_proto_goTypes = nil
	file_graph_v1_replication_proto_depIdxs = nil
}
