// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: graph/v1/replication.proto

package graphv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LanternReplicationService_Subscribe_FullMethodName = "/graph.v1.LanternReplicationService/Subscribe"
	LanternReplicationService_Snapshot_FullMethodName  = "/graph.v1.LanternReplicationService/Snapshot"
)

// LanternReplicationServiceClient is the client API for LanternReplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LanternReplicationService carries the peer-to-peer (and CDC) replication
// surface. It is intentionally a separate service from LanternService so
// that operators can route, throttle, secure, or even disable replication
// independently of the public read/write API.
//
// NOTE — deviation from the original RFC: the Subscribe RPC was originally
// specified to live on LanternService. The realised proto split introduces
// a cyclic file import between graph.proto and replication.proto when both
// the request/response messages and the RPC live on opposite sides of the
// boundary. Hosting Subscribe on a dedicated service keeps the import
// graph one-way (replication.proto → graph.proto) and is documented as
// part of #178's implementation in docs/replication.md.
type LanternReplicationServiceClient interface {
	// Subscribe streams replicated mutations to a peer (or CDC consumer)
	// starting at `from_seq` (inclusive). The server replays any in-buffer
	// entries first, then streams live mutations as they are appended.
	//
	// If `from_seq` is below the server's first available seq the call
	// fails with FAILED_PRECONDITION ("gapped") and the caller must
	// snapshot + resubscribe. Slow consumers whose channel backs up may
	// also have the stream terminated with FAILED_PRECONDITION — the
	// remedy is the same.
	//
	// No HTTP gateway annotation: replication is intentionally gRPC-only.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error)
	// Snapshot streams a point-in-time, causally-consistent dump of every
	// live vertex and edge to a bootstrapping peer. The first frame is a
	// SnapshotHeader carrying the (cutoff_seq, cutoff_hlc) the server used
	// to materialise the snapshot; the last frame is a SnapshotFooter with
	// the actual vertex / edge counts streamed.
	//
	// Bootstrap stitch contract: after receiving the SnapshotFooter the
	// peer MUST call `Subscribe(from_seq = cutoff_seq + 1)` on the same
	// origin to pick up the live tail. Without that the snapshot and the
	// live stream cannot be glued together without gap or overlap.
	//
	// No HTTP gateway annotation (parity with Subscribe).
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotEntry], error)
}

type lanternReplicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLanternReplicationServiceClient(cc grpc.ClientConnInterface) LanternReplicationServiceClient {
	return &lanternReplicationServiceClient{cc}
}

func (c *lanternReplicationServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LanternReplicationService_ServiceDesc.Streams[0], LanternReplicationService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LanternReplicationService_SubscribeClient = grpc.ServerStreamingClient[SubscribeResponse]

func (c *lanternReplicationServiceClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LanternReplicationService_ServiceDesc.Streams[1], LanternReplicationService_Snapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotRequest, SnapshotEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LanternReplicationService_SnapshotClient = grpc.ServerStreamingClient[SnapshotEntry]

// LanternReplicationServiceServer is the server API for LanternReplicationService service.
// All implementations should embed UnimplementedLanternReplicationServiceServer
// for forward compatibility.
//
// LanternReplicationService carries the peer-to-peer (and CDC) replication
// surface. It is intentionally a separate service from LanternService so
// that operators can route, throttle, secure, or even disable replication
// independently of the public read/write API.
//
// NOTE — deviation from the original RFC: the Subscribe RPC was originally
// specified to live on LanternService. The realised proto split introduces
// a cyclic file import between graph.proto and replication.proto when both
// the request/response messages and the RPC live on opposite sides of the
// boundary. Hosting Subscribe on a dedicated service keeps the import
// graph one-way (replication.proto → graph.proto) and is documented as
// part of #178's implementation in docs/replication.md.
type LanternReplicationServiceServer interface {
	// Subscribe streams replicated mutations to a peer (or CDC consumer)
	// starting at `from_seq` (inclusive). The server replays any in-buffer
	// entries first, then streams live mutations as they are appended.
	//
	// If `from_seq` is below the server's first available seq the call
	// fails with FAILED_PRECONDITION ("gapped") and the caller must
	// snapshot + resubscribe. Slow consumers whose channel backs up may
	// also have the stream terminated with FAILED_PRECONDITION — the
	// remedy is the same.
	//
	// No HTTP gateway annotation: replication is intentionally gRPC-only.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error
	// Snapshot streams a point-in-time, causally-consistent dump of every
	// live vertex and edge to a bootstrapping peer. The first frame is a
	// SnapshotHeader carrying the (cutoff_seq, cutoff_hlc) the server used
	// to materialise the snapshot; the last frame is a SnapshotFooter with
	// the actual vertex / edge counts streamed.
	//
	// Bootstrap stitch contract: after receiving the SnapshotFooter the
	// peer MUST call `Subscribe(from_seq = cutoff_seq + 1)` on the same
	// origin to pick up the live tail. Without that the snapshot and the
	// live stream cannot be glued together without gap or overlap.
	//
	// No HTTP gateway annotation (parity with Subscribe).
	Snapshot(*SnapshotRequest, grpc.ServerStreamingServer[SnapshotEntry]) error
}

// UnimplementedLanternReplicationServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLanternReplicationServiceServer struct{}

func (UnimplementedLanternReplicationServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedLanternReplicationServiceServer) Snapshot(*SnapshotRequest, grpc.ServerStreamingServer[SnapshotEntry]) error {
	return status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedLanternReplicationServiceServer) testEmbeddedByValue() {}

// UnsafeLanternReplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LanternReplicationServiceServer will
// result in compilation errors.
type UnsafeLanternReplicationServiceServer interface {
	mustEmbedUnimplementedLanternReplicationServiceServer()
}

func RegisterLanternReplicationServiceServer(s grpc.ServiceRegistrar, srv LanternReplicationServiceServer) {
	// If the following call panics, it indicates UnimplementedLanternReplicationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LanternReplicationService_ServiceDesc, srv)
}

func _LanternReplicationService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LanternReplicationServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LanternReplicationService_SubscribeServer = grpc.ServerStreamingServer[SubscribeResponse]

func _LanternReplicationService_Snapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LanternReplicationServiceServer).Snapshot(m, &grpc.GenericServerStream[SnapshotRequest, SnapshotEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LanternReplicationService_SnapshotServer = grpc.ServerStreamingServer[SnapshotEntry]

// LanternReplicationService_ServiceDesc is the grpc.ServiceDesc for LanternReplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LanternReplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graph.v1.LanternReplicationService",
	HandlerType: (*LanternReplicationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _LanternReplicationService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Snapshot",
			Handler:       _LanternReplicationService_Snapshot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "graph/v1/replication.proto",
}
