// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: graph/v1/security_peer.proto

package graphv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenewPolicyLeaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must equal the authenticated workload's operator-approved stable ID.
	Receiver  []byte `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	BootNonce []byte `protobuf:"bytes,2,opt,name=boot_nonce,json=bootNonce,proto3" json:"boot_nonce,omitempty"`
	Challenge []byte `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`
	// Optional exact current signed revision digest; not an authorization proof.
	KnownDigest   []byte `protobuf:"bytes,4,opt,name=known_digest,json=knownDigest,proto3" json:"known_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewPolicyLeaseRequest) Reset() {
	*x = RenewPolicyLeaseRequest{}
	mi := &file_graph_v1_security_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewPolicyLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewPolicyLeaseRequest) ProtoMessage() {}

func (x *RenewPolicyLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_security_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewPolicyLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewPolicyLeaseRequest) Descriptor() ([]byte, []int) {
	return file_graph_v1_security_peer_proto_rawDescGZIP(), []int{0}
}

func (x *RenewPolicyLeaseRequest) GetReceiver() []byte {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *RenewPolicyLeaseRequest) GetBootNonce() []byte {
	if x != nil {
		return x.BootNonce
	}
	return nil
}

func (x *RenewPolicyLeaseRequest) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *RenewPolicyLeaseRequest) GetKnownDigest() []byte {
	if x != nil {
		return x.KnownDigest
	}
	return nil
}

type RenewPolicyLeaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Original writer signature, bound to receiver/boot/challenge and policy cut.
	SignedLease []byte `protobuf:"bytes,1,opt,name=signed_lease,json=signedLease,proto3" json:"signed_lease,omitempty"`
	// Complete original signed cut; omitted only for an identical known digest.
	SignedCheckpoint []byte `protobuf:"bytes,2,opt,name=signed_checkpoint,json=signedCheckpoint,proto3" json:"signed_checkpoint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RenewPolicyLeaseResponse) Reset() {
	*x = RenewPolicyLeaseResponse{}
	mi := &file_graph_v1_security_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewPolicyLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewPolicyLeaseResponse) ProtoMessage() {}

func (x *RenewPolicyLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_v1_security_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewPolicyLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewPolicyLeaseResponse) Descriptor() ([]byte, []int) {
	return file_graph_v1_security_peer_proto_rawDescGZIP(), []int{1}
}

func (x *RenewPolicyLeaseResponse) GetSignedLease() []byte {
	if x != nil {
		return x.SignedLease
	}
	return nil
}

func (x *RenewPolicyLeaseResponse) GetSignedCheckpoint() []byte {
	if x != nil {
		return x.SignedCheckpoint
	}
	return nil
}

var File_graph_v1_security_peer_proto protoreflect.FileDescriptor

const file_graph_v1_security_peer_proto_rawDesc = "" +
	"\n" +
	"\x1cgraph/v1/security_peer.proto\x12\bgraph.v1\"\x95\x01\n" +
	"\x17RenewPolicyLeaseRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\fR\breceiver\x12\x1d\n" +
	"\n" +
	"boot_nonce\x18\x02 \x01(\fR\tbootNonce\x12\x1c\n" +
	"\tchallenge\x18\x03 \x01(\fR\tchallenge\x12!\n" +
	"\fknown_digest\x18\x04 \x01(\fR\vknownDigest\"j\n" +
	"\x18RenewPolicyLeaseResponse\x12!\n" +
	"\fsigned_lease\x18\x01 \x01(\fR\vsignedLease\x12+\n" +
	"\x11signed_checkpoint\x18\x02 \x01(\fR\x10signedCheckpoint2w\n" +
	"\x1aLanternSecurityPeerService\x12Y\n" +
	"\x10RenewPolicyLease\x12!.graph.v1.RenewPolicyLeaseRequest\x1a\".graph.v1.RenewPolicyLeaseResponseB\x97\x01\n" +
	"\fcom.graph.v1B\x11SecurityPeerProtoP\x01Z3github.com/anaregdesign/lantern/pb/graph/v1;graphv1\xa2\x02\x03GXX\xaa\x02\bGraph.V1\xca\x02\bGraph\\V1\xe2\x02\x14Graph\\V1\\GPBMetadata\xea\x02\tGraph::V1b\x06proto3"

var (
	file_graph_v1_security_peer_proto_rawDescOnce sync.Once
	file_graph_v1_security_peer_proto_rawDescData []byte
)

func file_graph_v1_security_peer_proto_rawDescGZIP() []byte {
	file_graph_v1_security_peer_proto_rawDescOnce.Do(func() {
		file_graph_v1_security_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_v1_security_peer_proto_rawDesc), len(file_graph_v1_security_peer_proto_rawDesc)))
	})
	return file_graph_v1_security_peer_proto_rawDescData
}

var file_graph_v1_security_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_graph_v1_security_peer_proto_goTypes = []any{
	(*RenewPolicyLeaseRequest)(nil),  // 0: graph.v1.RenewPolicyLeaseRequest
	(*RenewPolicyLeaseResponse)(nil), // 1: graph.v1.RenewPolicyLeaseResponse
}
var file_graph_v1_security_peer_proto_depIdxs = []int32{
	0, // 0: graph.v1.LanternSecurityPeerService.RenewPolicyLease:input_type -> graph.v1.RenewPolicyLeaseRequest
	1, // 1: graph.v1.LanternSecurityPeerService.RenewPolicyLease:output_type -> graph.v1.RenewPolicyLeaseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_graph_v1_security_peer_proto_init() }
func file_graph_v1_security_peer_proto_init() {
	if File_graph_v1_security_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_v1_security_peer_proto_rawDesc), len(file_graph_v1_security_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_v1_security_peer_proto_goTypes,
		DependencyIndexes: file_graph_v1_security_peer_proto_depIdxs,
		MessageInfos:      file_graph_v1_security_peer_proto_msgTypes,
	}.Build()
	File_graph_v1_security_peer_proto = out.File
	file_graph_v1_security_peer_proto_goTypes = nil
	file_graph_v1_security_peer_proto_depIdxs = nil
}
